### PR TITLE
fix #4320 #4318: implementing release on cancel and fixing transitions

### LINKED ISSUE #4320: LeaderElection leader transitions
LeaderTransitions is resetting on a change of leadership, and incrementing while holding the lock.  I think this should instead be to increment on a change and to leave the value alone will renewing.

### PR DESCRIPTION
**Pull request by shawkins**
## Description
addresses #4320 #4318 for leader election.

@manusa @csviri in the previous refactoring I had already put in a call to onStopLeading when cancelled - however this is not strictly correct.  If you don't have release on cancel set you won't loose the leadership until after the duration has expired.  Should that be refined as well?

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
> @manusa @csviri in the previous refactoring I had already put in a call to onStopLeading when cancelled - however this is not strictly correct. If you don't have release on cancel set you won't loose the leadership until after the duration has expired. Should that be refined as well?

I discussed this internally with Attila. The Leader Election "extension" was implemented as a port of what was available in Client Go at the time.
The cancel functionality was added later on by you in scope of #2207 in #4125. I'm not sure if this was ported or not from Client-Go too.
- If the cancel behavior is available on Client-Go, then we should port **exactly** what's implemented there.
- If the cancel behavior is something exclusive of ours, then we can do as we please. It seems reasonable that if a leader actively cancels its leadership, it should also update the lease record (regardless of the Lock implementation).

OT: It would be nice to discuss what are good use-cases of this cancel behavior. Personally I don't see why a leader should decide to stop leading.

**Comment by shawkins** [comment]
> I'm not sure if this was ported or not from Client-Go too.

No, since it's base upon the CompletableFuture.

> If the cancel behavior is available on Client-Go, then we should port exactly what's implemented there.

It is available.  As part of the initial port the leader election configuration included releaseOnCancel - which was left as doing nothing.  This pr makes that config property meaningful.

> Personally I don't see why a leader should decide to stop leading.

If the leader is in some way out-of-date and wants to cede leadership to others, then you have a reason to cancel with a release.

**Comment by shawkins** [comment]
> Should that be refined as well?

To clarify this behavior is not new, it was carried over from the existing port.  Anytime the loop stopped it could call onStopLeading if it had been the leader.

The question is - without a successful call to release, this isn't necessarily true - so does it need to be refined?

**Comment by manusa** [comment]
> If the leader is in some way out-of-date and wants to cede leadership to others, then you have a reason to cancel with a release.

Yes, this is the obvious reason for the _"why a leader should decide to stop leading."_. However, it's unclear to me what the bigger picture would be here and why this should be relevant and what are the implications to the whole ecosystem. It's more of a discussion topic.

A use-case based on the outdated version would be an Operator or Controller that has a new version available. However, probably the Deployment controller would be taking care of rolling out the newer version of the workload by tearing down the leader and the outdated replicas. So it might make sense that the outdated workloads no longer participate on the leadership battle, but this might bring some unwanted problems (and would also require them to be aware of their outdated version state).

**Comment by shawkins** [comment]
> The question is - without a successful call to release, this isn't necessarily true - so does it need to be refined?

My reading of: https://github.com/kubernetes/kubernetes/blob/f0bd02ca5e1773396288149f4faab25d2f9c6dfe/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L202

is that onStoppedLeading is always called - even if you never obtain the leadership, so I think we can just leave our current logic.

**Comment by shawkins** [comment]
@manusa should be good now

**Review by manusa — APPROVED** [review]

**Pull request merged**
