### PR TITLE
Fixed failing unit test testSerializeYamlWithAlias.

### PR DESCRIPTION
**Pull request by DobromirM**
## Description
Fixes https://github.com/fabric8io/kubernetes-client/issues/4484

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by DobromirM** [comment]
Fixes #4484

**Comment by andreaTP** [comment]
the test is correctly passing in CI, we need to understand if there is a real issue here.

**Comment by DobromirM** [comment]
It seems that the test fails only when running with `Oracle OpenJDK`, switching my local SDK to `Eclipse Temurin` to match the CI has resolved the problem.

Might be a good idea to add that as a note in [CONTRIBUTING.md](https://github.com/fabric8io/kubernetes-client/blob/master/CONTRIBUTING.md)

**Comment by andreaTP** [comment]
cc. @manusa @rohanKanojia

**Comment by rohanKanojia** [comment]
@DobromirM : Which version of Oracle JDK are you using? I ran on JDK11 and it seems to be passing for me.

In my opinion it's okay to merge this PR if it fixes issue on both JDKs.

**Comment by DobromirM** [comment]
It was failing on my side with both JDK11 and the bundled JDK11 that comes with IntelliJ. https://github.com/JetBrains/JetBrainsRuntime

**Comment by shawkins** [comment]
Can confirm the test failure when using OpenJDK 17 as well.

**Comment by shawkins** [comment]
@DobromirM did you mean to close this pr?

**Comment by DobromirM** [comment]
> @DobromirM did you mean to close this pr?

Sorry, my bad.

**Review by manusa — APPROVED** [review]

**Pull request merged**
