### PR TITLE
Chore: Add Keycloak model as a dependency to crd-generator tests

### PR DESCRIPTION
**Pull request by xRodney**
And generate crd from it to verify that it can be done without StackOverwlows and other errors. No other verifications are performed.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change - I don't think it is needed
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by andreaTP** [comment]
@xRodney now it should be time to test this change in CI, isn't it? 🙂

**Comment by xRodney** [comment]
Looking good :D

**Comment by andreaTP** [comment]
Nice! Thanks a lot @xRodney !

I'm slightly inclined to get this in as a "regression test" against `sundrio` version bumps ...
@manusa wdyt?

**Review by manusa — APPROVED** [review]
LGTM, not sure if some additional assertions should be provided or if just making sure that a resource is generated is enough

**Comment by andreaTP** [comment]
Most of the regression we found, so far, have been causing StackOverflows or hard breaks of the generator.
We can add additional checks on top when needed.

**Pull request merged**
