### PR TITLE
feat: First draft of exposing port-forward via service DSL.

### LINKED ISSUE #1447: Portforward should also be accessible through the Service DSL
`kubectl` allows you to portforward to  a service. This is done by looking up for the pods that provide the service and then delagating to pod port-forward.

We should do the same.

### PR DESCRIPTION
**Pull request by iocanel**
Fixes #1447

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@iocanel : Could you please add an example/test for this?

**Comment by iocanel** [comment]
> @iocanel : Could you please add an example/test for this?

Port forwarding is an area where we are lacking tests, even in the pod dsl. 
Its no surprise as its pretty complicated and I am not sure if we can even mock it.

We should find a solution, but I wouldn't hold the PR for that.

**Comment by rohanKanojia** [comment]
@iocanel :pray:

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
