### PR TITLE
#503 Support LimitRange resource type

### PR DESCRIPTION
**Pull request by sanjana-bhat**
@jimmidyson @iocanel 
Can you please review this PR? Thanks!

### CODE REVIEW

**Comment by iocanel** [comment]
ok to test

**Comment by iocanel** [comment]
sorry for the delay!

I gave a quick glimpse and looks good to me! @jimmidyson: wdyt?

**Comment by jimmidyson** [comment]
LGTM [merge]

**Comment by sanjana-bhat** [comment]
Thanks! @iocanel @jimmidyson when will a new tag be released? I need to use that in my application.

**Pull request merged**
