### PR TITLE
Add direct support for Files for binary builds

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by rhuss** [comment]
@iocanel added a direct support for files (since this is directly supported by OkHttp, too).

In principle it works, however the build hangs in execute() in a socket.write() 

Don't know yet exactly why, the build itselfs has an error because of a missing registry, but the API server should at least close the connection and send back an error. Instead, it seems that the OpenShift API server is blocking.

I'll continue to investigate ....

**Comment by iocanel** [comment]
ok to test

**Comment by rhuss** [comment]
Thats the stacktrace, I got

<details>
  <summary>Stacktrace</summary>
````
"main" #1 prio=5 os_prio=31 tid=0x00007ffb7c00a800 nid=0x1703 runnable [0x0000700000217000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:864)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:835)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	- locked <0x000000076b58da00> (a sun.security.ssl.AppOutputStream)
	at okio.Okio$1.write(Okio.java:80)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
	at okio.RealBufferedSink.write(RealBufferedSink.java:46)
	at com.squareup.okhttp.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:288)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.java:104)
	at com.squareup.okhttp.RequestBody$3.writeTo(RequestBody.java:118)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:718)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:65)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:93)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
	at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromFile(BuildConfigOperationsImpl.java:227)
	at io.fabric8.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromFile(BuildConfigOperationsImpl.java:50)
	at io.fabric8.maven.plugin.BuildMojo.executeOpenShiftBuild(BuildMojo.java:147)
	at io.fabric8.maven.plugin.BuildMojo.buildAndTag(BuildMojo.java:96)
	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:45)
````
</details>

**Comment by iocanel** [comment]
@rhuss 

I can only think of 3 ways, why this can fail:

1.  wrong headers, media type etc.
2. okhttp magic required
3. openshift issue

I would try to eliminate (2) with something like:
                
                Source source = null;
                try {
                        source = Okio.source(inputStream);
                        sink.writeAll(source);
                    } finally {
                        Util.closeQuietly(source);
                    }

and then I would try to ping the openshift guys to see if there is something additional required that's not defined in the rest api.

**Comment by rhuss** [comment]
I just tried in on a 'real' OpenShift with a registry (the first test was on minishift), so that the build suceed. In that case, everything returns fine. I will try now also with an induced error and see whether it will hang here, too.

**Comment by iocanel** [comment]
so [merge] I guess.

**Comment by rhuss** [comment]
👍

**Comment by rhuss** [comment]
@iocanel I can verify that also for our Vagrant image, in case of an error like 

```
  30s		30s		1	{build-controller }			Warning		HandleBuildError	Build has error: the referenced output image stream default/fabric8/spring-boot-web could not be found by build default/spring-boot-web-build-1: invalid resource name "fabric8/spring-boot-web": name may not contain "/"
```

the request hangs forever. Only the success case everything works as expected. 

 I'll try you suggestion and then check the server code whats going on here.

Thanks a lot for your support ! ;-)

**Pull request merged**
