### PR TITLE
fix: TokenRefreshInterceptor throws when running incluster

### LINKED ISSUE #3312: reload token when kube config file does not exist, errors shows
we ran into a problem when the token is refreshed : 
```
Caused by: java.io.FileNotFoundException: /home/common/.kube/config (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:343) ~[jackson-dataformat-yaml-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:14) ~[jackson-dataformat-yaml-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413) ~[jackson-databind-2.12.2.jar:2.12.2]
        at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfig(KubeConfigUtils.java:42) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:44) ~[kubernetes-client-5.1.1.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.12.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.12.jar:?]
        at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[kubernetes-client-5.1.1.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.12.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.12.jar:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:282) ~[kubernetes-client-5.1.1.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.12.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.12.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) ~[okhttp-3.12.12.jar:?]
        at okhttp3.RealCall.execute(RealCall.java:93) ~[okhttp-3.12.12.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:472) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:402) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:384) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:925) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:220) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:85) ~[kubernetes-client-5.1.1.jar:?]
```

We checked the environment and found that the /.kube/config file not exist, so in function intercept() it throws out  an exception in KubeConfigUtils.parseConfig, and codes in else{} would not execute.

```
  public Response intercept(Chain chain) throws IOException {
    Request request = chain.request();
    Response response = chain.proceed(request);
    if (response.code() == HttpURLConnection.HTTP_UNAUTHORIZED) {
      **io.fabric8.kubernetes.api.model.Config kubeConfig = KubeConfigUtils.parseConfig(new File(Config.getKubeconfigFilename()));**
      Context currentContext = null;
      String currentContextName = null;
      if (config.getCurrentContext() != null) {
        currentContext = config.getCurrentContext().getContext();
        currentContextName = config.getCurrentContext().getName();
      }
      AuthInfo currentAuthInfo = KubeConfigUtils.getUserAuthInfo(kubeConfig, currentContext);
      // Check if AuthProvider is set or not
      if (currentAuthInfo != null) {
        response.close();
        String newAccessToken;
        // Check if AuthProvider is set to oidc
        if (currentAuthInfo.getAuthProvider() != null && currentAuthInfo.getAuthProvider().getName().equalsIgnoreCase("oidc")) {
          newAccessToken = OpenIDConnectionUtils.resolveOIDCTokenFromAuthConfig(currentAuthInfo.getAuthProvider().getConfig());
        } else {
          Config newestConfig = Config.autoConfigure(currentContextName);
          newAccessToken = newestConfig.getOauthToken();
        }
        // Delete old Authorization header and append new one
        Request authReqWithUpdatedToken = chain.request().newBuilder()
          .header("Authorization", "Bearer " + newAccessToken).build();
        config.setOauthToken(newAccessToken);
        return chain.proceed(authReqWithUpdatedToken);
      }
    }
```

While in autoConfigure() function, error is ignored if /.kube/config not exist, so it will continue to tryServiceAccount.

```
private static Config (Config config, String context) {
    if (!tryKubeConfig(config, context)) {
      tryServiceAccount(config);
      tryNamespaceFromPath(config);
    }
    configFromSysPropsOrEnvVars(config);

    config.masterUrl = ensureHttps(config.masterUrl, config);
    config.masterUrl = ensureEndsWithSlash(config.masterUrl);

    return config;
  }
```

Could you help to check  in intercept()  whether the error should be ignored if read kubeconfig file failed?

### PR DESCRIPTION
**Pull request by tsaarni**
## Description

Token refresh was unsuccessful after failed authentication when running incluster. The reason was that TokenRefreshInterceptor was expecting kubeconfig file to exists, even though in incluster mode it does not exist.

* Removes kubeconfig handling from TokenRefreshInterceptor and re-uses existing logic in autoconfig instead, which is prepared for both in/out-of-cluster use cases.
* Adds system property for previously hardcoded token path to facilitate unit testing.
* Adds copy of auth-provider from model to config to avoid config parsing in TokenRefreshInterceptor.

Fixes #3312

Signed-off-by: Tero Saarni <tero.saarni@est.tech>

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by tsaarni** [comment]
I've done some manual testing with token renewal as well. The procedure is documented [here](https://github.com/tsaarni/k8s-java-client-token-reload-test).

It seems OIDC path was never covered by a test case. Since I touched that line, SonarCloud alerted about it here. Should this PR introduce OIDC test case?

**Comment by rohanKanojia** [comment]
> It seems OIDC path was never covered by a test case. Since I touched that line, SonarCloud alerted about it here. Should this PR introduce OIDC renewal test case?

Yeah, Would be nice if you can write a test to cover this :-) .

**Comment by tsaarni** [comment]
> Yeah, Would be nice if you can write a test to cover this :-) . I don't mind it having in this PR

@rohanKanojia OK, I'll check if I can figure out an approach to test that part as well.

By the way, some checks seem bit flaky, is that to be expected? They seemed unrelated to the change.

**Comment by rohanKanojia** [comment]
You're right. I've restarted them for now. Somehow these failures only seem to happen on Github Actions.

**Comment by tsaarni** [comment]
I've now added a test case `shouldRefreshOIDCToken()` to ensure that `TokenRefreshInterceptor` also refreshes token in case of OIDC auth provider.

**Review by oscerd — APPROVED** [review]

**Comment by tsaarni** [comment]
Thank you @oscerd for the review.  I'd like to kindly ask if @manusa and @shawkins could review too?  
It would be nice to get this forward since this bug breaks applications on clusters with expiring service account tokens.

**Review by shawkins — APPROVED** [review]
The code changes seem good - if I understand correctly, we get an unauthorized response, then it won't assume kubeconfig exists and look to the AuthProvider if possible.

**Review by rohanKanojia — APPROVED** [review]

**Comment by tsaarni** [comment]
> if I understand correctly, we get an unauthorized response, then it won't assume kubeconfig exists and look to the AuthProvider if possible.

Yes when we get unauthorized, the logic in `Config.autoConfigure()` is first look to look for kubeconfig. If it exists, it might contain AuthProvider config for OIDC provider which is used to fetch refreshed token (in that case we execute branch on line 3), or just pure token (line 5).  If kubeconfig does not exist `Config.autoConfigure()` will look for service account token file and re-read the renewed token from there (we'll also end up in branch on line 5).

```
1 Config newestConfig = Config.autoConfigure(currentContextName);
2 if (newestConfig.getAuthProvider() != null && newestConfig.getAuthProvider().getName().equalsIgnoreCase("oidc")) {
3   newAccessToken = OpenIDConnectionUtils.resolveOIDCTokenFromAuthConfig(newestConfig.getAuthProvider().getConfig());
4 } else {
5   newAccessToken = newestConfig.getOauthToken();
6 }
```

**Comment by tsaarni** [comment]
One more observation: 

My PR continues using the approach from existing implementation where reloading is based on `401 Unauthorized` response. This postpones the reload to the very last possible moment, or one could also say it reloads "too late". While this works correctly, the service account token on disk is refreshed in advance and `401 Unauthorized` could be avoided. 

Looking at other implementations https://github.com/kubernetes-client/java/pull/967 reloads if 60 seconds has passed from previous reload. It seems to me this is not as straightforward to implement with `Config.autoConfigure()`, since it always goes through the whole process of checking the kubeconfig, falling back to service account if not successful.

Why would one use time based reloading?

To help transitioning to expiring tokens, [KEP 1205](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md) describes that tokens include `kubernetes.io/warnafter` field that is used to call out clients that do not reload often. Metrics `serviceaccount_stale_tokens_total` and audit annotation `authentication.k8s.io/stale-token` can be used for monitoring this (see [here](
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/serviceaccount/claims.go#L188-L195)). When client uses `401 Unauthorized` for reloading, it might cause some unnecessary concerns due to false "stale token" signals.

**Comment by manusa** [comment]
> Why would one use time based reloading?

I think we discussed this in some other issue.

I would only go for time based reloading if the expiration date is something known (e.g. `kubernetes.io/warnafter` is available).
Having a periodic check for something that might be unnecessary most of the times and that is easily solved by refreshing the token after the first unauthorized response, seems like an overhead to me.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
