### PR TITLE
Update E2E tests Kubernetes matrix

### PR DESCRIPTION
**Pull request by jorsol**
Update K8s versions to the latest patch release.
Update Minikube to 1.25.1

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by rohanKanojia** [comment]
All E2E workflows seem to be failing. From what I can remember I had added cache for building a snapshot jar version for current branch and E2E workflows would use shared cache for kubernetes-client snapshot dependency instead of rebuilding client again every time.

**Comment by jorsol** [comment]
Ok, I might have taken the commit for the precise moment when 5.12 was released and then the tests were trying to download that version from maven-central when it was actually not fully uploaded.

I have rebased this to see if it change anything.

**Comment by jorsol** [comment]
Ok, the cache was needed after all, now the e2e pass, other failures seem unrelated.

**Comment by manusa** [comment]
Required checks need to be updated after merging this PR

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
