### PR TITLE
Add an uberjar and an uberjar with versioned packages (majro / minor).

### PR DESCRIPTION
**Pull request by iocanel**
This addresses #720.

### CODE REVIEW

**Comment by iocanel** [comment]
@jimmidyson: If you have the cycles I'd like you to have a very quick look.

**Comment by jimmidyson** [comment]
How does this handle transitives?

**Comment by iocanel** [comment]
@jimmidyson: Transitives are maintained (as transitives) without being included in the uberjar itself. We could possibly include `okhttp` inside the uberjar, though since okhttp already includes the major version inside the package, we are relatively safe.

**Comment by jimmidyson** [comment]
OK let's try this for first cut and see if we need to shade more in future.

[merge]

**Pull request merged**
