### PR TITLE
enable Dependabot v2

### PR DESCRIPTION
**Pull request by sullis**
## Description

https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
I hate dependabot but it's fine

**Comment by rohanKanojia** [comment]
Could you please add license header using `mvn -N license:format`?

**Comment by sullis** [comment]
> Could you please add license header using `mvn -N license:format`?

Done.

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
We already have a dependabot integration enabled in the repo.

However, the integration is called "Dependabot Preview" and was installed 2 years ago.

https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#moving-forward-from-dependabot-com-and-dependabot-preview

**Comment by manusa** [comment]
I'll follow the procedure described in the previous link since we have custom configurations that we need to propagate and unfortunately aren't covered by this PR.

**Comment by manusa** [comment]
Superseded by #2862

**Comment by manusa** [comment]
Dashboard is now available here: https://github.com/fabric8io/kubernetes-client/network/updates

**Pull request closed without merging**
