### PR TITLE
fix ConcurrentModificationException in KubernetesCrudDispatcher

### PR DESCRIPTION
**Pull request by CatTail**
## Description

Fix https://github.com/fabric8io/kubernetes-client/issues/3429

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by rnorth** [comment]
Thank you so much @CatTail!

I've just run our test suite a number of times using the patched version and it seems to have solved #3429 for us.

**Review by shawkins — APPROVED** [review]
LGTM

**Comment by shawkins** [comment]
@manusa this looks good for 5.8

**Comment by manusa** [comment]
PR has been reopened in https://github.com/fabric8io/kubernetes-client/pull/3434

(I fixed merge conflicts, but since original PR came from a master branch and was protected, GH automatically closes is)

**Pull request closed without merging**
