### PR TITLE
Change badges for the list of client modules

### PR DESCRIPTION
**Pull request by jorsol**
This changes the badges for maven central from shields.io to maven-badges.herokuapp.com, the issue with shields.io is that they aren't updated correctly (or the cache fails to refresh) when there is a new release showing old versions. Also, they are now in a table instead of a list.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by manusa** [comment]
Thx, this was something very much needed.

The list of modules probably needs updating too (I for one see that volumesnapshot extension is missing)

**Comment by jorsol** [comment]
> Thx, this was something very much needed.
> 
> The list of modules probably needs updating too (I for one see that volumesnapshot extension is missing)

Is the `kubernetes-model-core` needed here?

**Comment by manusa** [comment]
> Is the `kubernetes-model-core` needed here?

:sweat_smile: No idea, as a consumer user you probably have a better idea of which modules make sense to expose here. I'm aware some users are just interested in model types, others in extensions, etc. Personally I think it doesn't belong to the set. @rohanKanojia ?

**Comment by jorsol** [comment]
> > Is the `kubernetes-model-core` needed here?
> 
> sweat_smile No idea, as a consumer user you probably have a better idea of which modules make sense to expose here. I'm aware some users are just interested in model types, others in extensions, etc. Personally I think it doesn't belong to the set. @rohanKanojia ?

I only use `kubernetes-client` 😅 , so I also think the model doesn't belong to the set.

I added `volumesnapshot-client` and removed `kubernetes-model-core`.

**Comment by rohanKanojia** [comment]
We have kubernetes-model related badged in kubernetes-model-generator README

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
