### PR TITLE
refactor: refactoring `TokenRefreshInterceptor` for code readability (#4401)

### LINKED ISSUE #4401: [refactor] refactoring `TokenRefreshInterceptor`
### Is your enhancement related to a problem? Please describe

I want to improve the TokenRefreshInterceptor code. :)

* Code improvements
  * `setLastRefresh` written for testing only
  * code readability

### Describe the solution you'd like

* refactoring purpose
  * should remove `setLastRefresh` method for testing only
  * should improve code readability

### Describe alternatives you've considered

_No response_

### PR DESCRIPTION
**Pull request by heesuk-ahn**
## Description

Fix #4401 

This pull-request is related to refactoring to 'TokenRefreshInterceptor'. :) 

* Code improvements points
  * [x] should remove setLastRefresh method for testing only
  * [x] should improve code readability

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
You need to run `mvn spotless:apply` to fix style check failures

**Comment by heesuk-ahn** [comment]
> 

Thanks you, I will apply it's command :)

**Review by rohanKanojia — APPROVED** [review]

**Review by shawkins — APPROVED** [review]
LGTM

**Comment by heesuk-ahn** [comment]
@rohanKanojia hi, :) Could this PR be Merged?

**Pull request merged**
