### PR TITLE
lets do a PR against fmp on release

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by rawlingsj** [comment]
Not sure about the dependency CI failure here.  Shall we just merge as it's just a PR on a downstream repo?

**Comment by jstrachan** [comment]
never sure about those dependency-ci checks TBH :) @iocanel you cool to just merge?

**Comment by iocanel** [comment]
@jstrachan: Of course!

**Comment by iocanel** [comment]
[merge]

**Comment by iocanel** [comment]
@jimmidyson: what do we use the dependenci-ci for?

**Comment by jimmidyson** [comment]
@iocanel Among other things, dependencyci is really useful to find license incompatibilities for dependencies. Unfortunately it looks a bit broken at the moment :(

**Pull request merged**
