### PR TITLE
OpenShiftOAuthInterceptor.authorize() should only throw IOException

### PR DESCRIPTION
**Pull request by gyoetam**
The authorize method should never wrap an underlying checked IOException
into an unchecked KubernetesClientException. The IOException is declared
in the calling method (intercept()) and is handled by okhttp's RealCall$
AsyncCall as part of the Interceptor contract. But a RuntimeException is
not handled and okhttp's Dispatcher thread simply exits in this case,
instead of notifying the listener through the onFailure() callback.

Specific scenario that fails without this fix:
A watch is connected via websocket and the authorization token times
out, so the server closes the connection. When the watch first tries to
reconnect, a socket read timeout occurs during the authorization phase.
- Without the fix. this timeout kills the Dispatcher thread and the
  WatchConnectionManager is never notified via the onFailure() callback.
- With the fix, RealCall$AsyncCall properly catches the IOException and
  calls onFailure(), allowing WatchConnectionManager to retry.

For other exceptions that may occur: KCE.launderThrowable() only wraps
checked exception; RuntimeException-s and Error-s simply passed through
the catch clause anyway. All checked exceptions thrown in the method are
IOExceptions now, which we are supposed to throw anyway.

### CODE REVIEW

**Comment by gyoetam** [comment]
@iocanel: Could you take a look at the pr-merge build for this on jenkins, maybe restart it manually? Clicking the details just gives "Not found" for me.

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
retest this please

**Comment by gyoetam** [comment]
I see the same "Something is wrong with the build of this commit" message for PR-800, while all other PRs have a "This commit cannot be built " message. Is this even related to the actual PR, or is it some general issue with the jenkins jobs?

**Comment by iocanel** [comment]
retest this please

**Comment by piyush1594** [comment]
Hey, @gyoetam Would you like to please rebase and push again. Thanks

**Comment by piyush1594** [comment]
@gyoetam Would you like to please take a look at this?

**Comment by rohanKanojia** [comment]
I've opened a new PR #1293 since I wasn't able to update this, hope you don't mind.

**Pull request closed without merging**
