### PR TITLE
Fix my mistake: Handle case for negative exponents while checking Quantity

### PR DESCRIPTION
**Pull request by rohanKanojia**
@turchenkoalex pointed this out in https://github.com/fabric8io/kubernetes-client/commit/c370d2628aa5da6b7217486373e16a35d7013df2#commitcomment-36713112

### CODE REVIEW

**Comment by rozuhlinh** [comment]
I have a Xr iPhone all of my social media accounts are hacked Facebook keeps redirecting me to do the same thing over and over.  My Instagram will not let me associate with friends Twitter is totally hacked and I can’t use my phone  number  on any accounts They act like or sign me up for Business accounts. They play fort nite and I do not have WiFi whoever it is lives close maps  is always off by 500 ft. My address is 4749 Wheeler  Rd. Louisville  Tn. 37777 Rosalyn Henry Littles 8654449406

**Comment by rozuhlinh** [comment]
I do not have a desk computer. No watch for Xr iPhone,earbuds or mac computer only the iPhone

**Comment by rohanKanojia** [comment]
[merge]

**Comment by jorsol** [comment]
Hi @rohanKanojia is there an ETA to release 4.7.1 with this fix?

**Comment by rohanKanojia** [comment]
@jorsol : Hi, I can release 4.7.1 if you're blocked on this

**Comment by jorsol** [comment]
Yes, it's a blocker for us. Thanks!

**Comment by rohanKanojia** [comment]
@jorsol : I've released [4.7.1](https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/4.7.1/). Please try it out whenever you get time :-)

**Pull request merged**
