### PR TITLE
Upgrade TLS Version in Mock Server to 1.2

### PR DESCRIPTION
**Pull request by caramelomartins**
## Description

As per #3038, this PR aims to upgrade the TLS version of `KubernetesMockServer`  to 1.2, given that Oracle deprecated 1.0 and 1.1 in some JDK versions. I ended up upgrading it in all mocks servers so that it remains consistent throughout the codebase.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by caramelomartins** [comment]
Any idea what the test failure in Sonar is all about? :thinking:

**Comment by rohanKanojia** [comment]
Sorry, we need to fix this flaky test https://github.com/fabric8io/kubernetes-client/issues/3036 . I've restarted workflow

**Comment by caramelomartins** [comment]
No worries. Not sure how I can improve the coverage on the code I've changed though. Any ideas?

**Comment by rohanKanojia** [comment]
I couldn't find a test for any of these classes. I'm not sure if we should add tests in the scope of this PR or not.

**Comment by caramelomartins** [comment]
@rohanKanojia I'm not sure I'm qualified (or have the knowledge) to write tests for all of the classes, to be honest...

**Comment by rohanKanojia** [comment]
No problem, your change is not so big. If required, maintainers can add tests as well.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
