### PR TITLE
[java-gen - chore] Automate code formatting on compile

### PR DESCRIPTION
**Pull request by andreaTP**
## Description

I found a solution for automating the code formatting on `compile`, to avoid spurious diffs in the future.
I'm not a Maven expert, so, any hint or suggestion is very welcome, this is the only configuration I got to work.
The problem is that the `license:format` goal should run from the root and `spotless` is slightly changing the headers :-S

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
From your PR, I understand you're talking about formatting the project code and not the generated code.

This probably belongs to a git hook or CI check (maybe checkstyle), and not a compile goal.

In addition, the current formatting for this modules is completely out of format as compared with the rest of the code-base (we really need to update the CONTRIBUTING.md file).

The first step should be to create some `ide-config` Eclipse config files that can be reused across most tools.

**Comment by andreaTP** [comment]
@manusa what you are saying is correct.
But there are codebases that are already using automatic formatting on `compile` (e.g. https://github.com/java-operator-sdk/java-operator-sdk or even Quarkus itself).

Since we are about to have a breaking release, if you want to enforce a style globally (and not in a single sub-module) checking it in CI I like it!

I don't have super strong opinions on the style to be used as long as it's consistent, if you can provide a configuration I can try to integrate it 🙂

**Comment by OneCricketeer** [comment]
Can't you bind `spotless:apply` to `prepare-package` lifecycle rather than a separate exec action / maven subprocess, essentially?

**Comment by andreaTP** [comment]
@OneCricketeer the problem is that running `spotless:apply` messes up the headers and we need to run a following `license:format` from the root of the project to fix it 😞 

Anyhow, not sure how to proceed on this one, @manusa would you like to apply a consistent style on the whole codebase?
Would you be able to provide a configuration file to start with?

**Pull request closed without merging**
