### PR TITLE
Update documentation to include dependencies

### PR DESCRIPTION
**Pull request by matteriben**
## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by matteriben** [comment]
@andreaTP How's this look?

**Review by andreaTP — CHANGES_REQUESTED** [review]
I might be wrong or outdated, but:
- `kubernetes-model` is already a transitive dependency of the client
- `openshift-client` is not needed, we can, rely only on the `kubernetes-client` (or a more fine grained dependency)

**Comment by matteriben** [comment]
> I might be wrong or outdated, but:
> 
> * `kubernetes-model` is already a transitive dependency of the client
> * `openshift-client` is not needed, we can, rely only on the `kubernetes-client` (or a more fine grained dependency)

You're not wrong.

**Comment by rohanKanojia** [comment]
@matteriben : Could you please resolve these minor conflicts and push again? Somehow CI checks seem stuck.

**Review by andreaTP — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
