### PR TITLE
fix #3831: creating a separate version class for the client

### LINKED ISSUE #3831: Version class after module split
### Is your task related to a problem? Please describe

Do we want just a single version class or multiple version classes - one for the api, and one for the impl?

### Describe the solution you'd like

I don't have a strong preference, but if the expectation is for the impl to provide its version, then it should do so in a way that doesn't require referencing a class in the impl - for example Client.getVerion

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
## Description
fix for #3831
This class is currently not used.  This is to avoid having the same class in multiple jars.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
Why don't we just remove it?

If this is moved to an internal package, and it's actually not used internally, what's the point of having it?

**Comment by shawkins** [comment]
> If this is moved to an internal package, and it's actually not used internally, what's the point of having it?

To be there proactively once someone mismatches the api and impl versions and wants a way to find the version of the impl at runtime.  Yes, just like any other internal usage it would be considered unsupported, so they would still need to request an enhancement moving forward.

> Why don't we just remove it?

If we discount the above case, then removing it is fine.

**Comment by manusa** [comment]
If the purpose is to be able to identify module versions, I'd at least, rename this one (or the other one) to something else.
- ApiVersion + Version
- Version + KubernetesClientVersion

**Comment by shawkins** [comment]
> If the purpose is to be able to identify module versions, I'd at least, rename this one (or the other one) to something else.

I had forgotten you could get the version information from the maven info in the jar - so there is a workaround already.  I'll just remove the -client class for now.

**Review by manusa — APPROVED** [review]

**Pull request merged**
