### PR TITLE
Use JsonFormat shape in crd-generator and java-generator

### LINKED ISSUE #5867: Generate a CRD with {type: string, format: date-time}
### Is your enhancement related to a problem? Please describe

I'd like to generate a CRD with a timestamp of type=string, and format=date-time.

I can generate code from a CRD with a string using date-time format, but when I generate a CRD from that code it generates something else entirely. For example:

Original CRD snippet:
```
                timestamp:
                  type: string
                  format: date-time
```

Java code snippet generated from above CRD snippet:
```
    @com.fasterxml.jackson.annotation.JsonProperty("timestamp")
    @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SKIP)
    private java.time.ZonedDateTime timestamp;

    @com.fasterxml.jackson.annotation.JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssVV")
    public java.time.ZonedDateTime getTimestamp() {
        return timestamp;
    }

    @com.fasterxml.jackson.annotation.JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss[XXX][VV]")
    public void setTimestamp(java.time.ZonedDateTime timestamp) {
        this.timestamp = timestamp;
    }
```

CRD snippet generated from above Java code snippet:
```
              timestamp:
                properties:
                  dateTime:
                    properties:
                      date:
                        properties:
                          year:
                            type: integer
                        type: object
                      time:
                        properties:
                          nano:
                            type: integer
                        type: object
                    type: object
                  offset:
                    properties:
                      id:
                        type: string
                      totalSeconds:
                        type: integer
                    type: object
                  zone:
                    type: object
                type: object
            type: object
```

### Describe the solution you'd like

I'd like for CRD fields of {type=string, format=date-time} to roundtrip from CRD to Java and back to CRD.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by matteriben**
## Description

Fixes #5867

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by matteriben** [comment]
@andreaTP Please take a look at this.

**Review by andreaTP — APPROVED** [review]
Thanks for this improvement!
LGTM

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by manusa** [comment]
@shawkins, is this OK?

**Review by shawkins — APPROVED** [review]
@manusa it is in that it fits with current sundrio based approach. If / when we continue down the path of leveraging jackson, then this is reflected in the schema already.

**Comment by msvticket** [comment]
This PR claims to be fixing #5867 whose title is: Generate a CRD with {type: string, format: date-time} 
I don't see how this PR fixes that. Am I missing something?

**Comment by rohanKanojia** [comment]
@msvticket : Do you think this is the correct PR fixing this issue? https://github.com/fabric8io/kubernetes-client/pull/5917

**Pull request merged**
