### PR TITLE
test(crd-generator): approval tests for crd-generator-api-v2

### PR DESCRIPTION
**Pull request by manusa**
## Description

Part of #5951 / #5948

Supersedes closes #5978

test(crd-generator): approval tests for crd-generator-api-v2

Relates to:
- #5948
- #5951
- #5850
- #5978
- #5980
- #5986
- #5989

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
Hi @shawkins,

Maybe you can help out here.

This PR adds the tests to ensure _feature parity_ for both versions of the crd-generator.

However, there's a misbehavior, but I'm unsure if this is because something is missing in the new implementation or there's a bug in the old one.

The approval file `CRDGeneratorApprovalTest.approvalTest.containingjsons.sample.fabric8.io.v1.approved.yml` contains the following lines:

https://github.com/fabric8io/kubernetes-client/blob/e3f2ae9e8bcf4338210479e74e651552ebcd66f1/crd-generator/test/src/test/resources/io/fabric8/crd/generator/approvaltests/CRDGeneratorApprovalTest.approvalTest.containingjsons.sample.fabric8.io.v1.approved.yml#L22-L30

which are not generated with the new implementation.

This fragment looks instead like:
```yaml
              foo:
                type: "object"
```

**Comment by shawkins** [comment]
@manusa the new one is correct with the default settings. We now have a CRDGenerator property to control whether x-kubernetes-preserve-unknown-fields is implicitly inferred from anyGetter/Setter - it defaults to false. It would need to use the crd annotation for preserve unknown or turn on the implicit setting for this to be seen as x-kubernetes-preserve-unknown-fields.

At the very least, the old one should not have been adding both a configAsMap property and setting x-kubernetes-preserve-unknown-fields - because that was derived from configAsMap.

**Comment by manusa** [comment]
Thx, yes, it looked more like a bug from the former implementation.
However, I'm not sure it's an easy fix (might break other stuff while fixing it). It might be better to just remove this part from the test (Class).

Thoughts? 

/cc @metacosm @andreaTP @baloo42

**Comment by baloo42** [comment]
IMHO fixing the test for now is better here than changing something in v1 or v2.

Maybe we can add some test cases later to show the differences or a Wiki page to document such things.

**Comment by manusa** [comment]
:+1: I removed the conflicting field + class.
The test case is still valid since it has a JsonNode field that properly maps to `x-kubernetes-preserve-unknown-fields: true`

**Review by rohanKanojia — APPROVED** [review]

**Review by shawkins — APPROVED** [review]
LGTM

**Pull request merged**
