### PR TITLE
Issue 1238: Renamed json test files to allow Windows pulls

### LINKED ISSUE #1238: Unable to pull full repository on Windows 10
When I try to pull this repository on my Windows 10 environment I get 2 issues around the filepath length and invalid filename characters.

Example filepath length issue:
kubernetes-model/vendor/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/client/clientset_generated/internalclientset/typed/settings/internalversion/fake/fake_settings_client.go: Filename too long

Setting "git config --system core.longpaths true" allows me to get to the next issue

Example invalid filename length issue:
error: unable to create file kubernetes-model/vendor/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/cmd/svcat/testdata/responses/clusterserviceclasses?fieldSelector=spec.externalName=user-provided-service.json: Invalid argument

This one is trickier - I can just not pull down the openshift origin, but I'm wary to trust the tests without the full repo.

Can anything be done to support us whacky Windows users?

### PR DESCRIPTION
**Pull request by traviswinter**
Fixes #1238 
Renamed various test files to allow for pulling the repo on Windows.  Ran the tests and didn't see any issues (are these files even used?).

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by traviswinter** [comment]
Are there any other reviewers available?  Not sure @iocanel is around :)

**Comment by rohanKanojia** [comment]
@traviswinter : Could you please add a line to CHANGELOG.md? Then we can proceed with merge.

**Comment by traviswinter** [comment]
Yes, sorry - missed that! Added it, as well as another ConfigTest fix

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
