### PR TITLE
fix #4590: only using a builder if there are visitors

### LINKED ISSUE #4590: Deserializing Kube and custom resources from the same template
### Is your enhancement related to a problem? Please describe

[View initial discussion](https://github.com/fabric8io/kubernetes-client/discussions/4585)

Deserializing a template containing both Kube objects and custom resources fails with: 
`io.fabric8.kubernetes.client.KubernetesClientException: Cannot edit with visitors, no builder was found at io.fabric8.kubernetes.client.ResourceHandlerImpl.edit(ResourceHandlerImpl.java:59) at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:292) at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.lambda$getItems$1(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:112) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.getItems(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:114) at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.resources(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:119) at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.getResources(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:124) at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.performOperation(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:327) at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:224) at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:62)`

### Describe the solution you'd like

Comment from @shawkins in original discussion:

> Ok yes that exception is currently expected when resource does not have a builder, but it actually wouldn't take much to make this go away - a builder isn't really required to just change the namespace which is what it's trying to do here. Feel free to open an issue for this.

### Describe alternatives you've considered

_No response_

### Additional context

Version 6.1.1

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Fixes #4590 - the namespace modification is no longer needed in the NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl because the logic in resource(item) will already handle that.  This removes the need to construct a builder for just simple operations.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
Maybe I'm not following it OK, but this PR seems to change the current behavior.

It now changes the namespace of the context as opposed to changing the namespace of the item in the context.

If this is the case, I'm not really sure of the possible side-effects this might have.

**Comment by shawkins** [comment]
> It now changes the namespace of the context as opposed to changing the namespace of the item in the context.

The logic for changing the item namespace at the list level was redundant - it was simply preserved from the original logic.  The responsibility for changing the namespace is now handled as part of the resource(item) method, which is called by the logic to perform any of the operations.

**Comment by manusa** [comment]
> > It now changes the namespace of the context as opposed to changing the namespace of the item in the context.
> 
> The logic for changing the item namespace at the list level was redundant - it was simply preserved from the original logic. The responsibility for changing the namespace is now handled as part of the resource(item) method, which is called by the logic to perform any of the operations.

Yes, I understand, but considering a maybe very random use-case (related to #4574) where a user might be doing:

```java
kubernetesClient.resource($resource).inNamespace("new-namespace").get();
// or
kubernetesClient.load($resource).inNamespace("new-namespace").get();
// or the #4574 proposal
kubernetesClient.resource($resource).inNamespace("new-namespace").item();
```

The behavior won't be the same (AFAIU)

I'm not opposing to this change, I'm just highlighting the possible side-effects and repercussions.

**Comment by shawkins** [comment]
> The behavior won't be the same (AFAIU)

No, the behavior is the same - if needed the item namespace will reflect the namespace specified in inNamespace.  The only case that is different is if the item does not have a namespace, then the namespace won't be set - the resource(item) logic will leave the resource alone in that case.

**Comment by manusa** [comment]
> at the **list** level was redundant

OK, I was missing the important part here: NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicable***List***Impl

**Pull request merged**
