### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by jimmidyson** [comment]
This adds `apply`? What logic have you implemented?

**Comment by iocanel** [comment]
@jimmidyson: It doesn't add apply. Apply has been added long ago. It replaces existing items, unless the user asks for explicit delete:

client.load(is).deletingExisting().apply();

**Comment by iocanel** [comment]
[merge]

**Comment by jimmidyson** [comment]
Hmm OK don't remember apply existing before... oops!

**Comment by iocanel** [comment]
Haven't you read the updated documentation? Oooops!

**Comment by iocanel** [comment]
[merge]

**Pull request merged**
