### PR TITLE
Fix #3805: Implement support for finalizers and `deletionTimestamp`s

### LINKED ISSUE #3805: DeletionTimestamp and Finalizer support in Mock server
### Is your enhancement related to a problem? Please describe

I'm writing an operator and would like to test how it behaves when deleting a resource. In CRUD mode, when a resource is deleted, it is remove even if finalizers is not empty.

### Describe the solution you'd like

I expect delete to update the resource with a deletionTimestamp if finalizers collection is not empty. When the operator will remove its finalizer and update the CR, if the finalizers collection is empty, the resource should be deleted.

I should be able to wait for the resource to be deleted (wait while get CR is not null) and assert the operator does its cleanup job.

### Describe alternatives you've considered

I tried to update the resource with edit to set a deletionTimestamp but is seems to be not saved.

```
client.resources(CRD.class).inNamespace("foo").withName("bar").edit(p -> {
    p.getMetadata().setDeletionTimestamp("2022-02-06T14:21:44.719489Z");
    return p;
});
```

what works is to replace the CR.

```
var cr = client.resources(CRD.class).inNamespace("foo").withName("bar").get();
cr.getMetadata().setDeletionTimestamp("2022-02-06T14:21:44.719489Z");
client.resource(cr).createOrReplace();
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LucaMertens**
## Description

Fix #3805

Hello there :wave:  I tried my hand on fixing this issue: https://github.com/fabric8io/kubernetes-client/issues/3805

I'm not sure why the `io.fabric8.kubernetes.client.server.mock.MasterProtocolTest::testWithSSL` fails, but I think that I didn't introduce this error.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [X] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes (not applicable, I think)
 - [x] I tested my code in OpenShift (not applicable, I think)

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by LucaMertens** [comment]
Sorry for the duplicate pipeline runs. I thought that I had removed the changes to the Utils in the last commit, put that change seems to have been lost

**Comment by LucaMertens** [comment]
Hey, could someone approve the pipeline run? :) I think the Quality Gate should be green after the last two commits

**Comment by LucaMertens** [comment]
My bad, I forgot to run mvn spotless.

Also, the [MasterProtocolTest::testWithSSL](https://github.com/fabric8io/kubernetes-client/blob/6f6558b15ba9ef5f27a39e077e9205a7f214ccfb/junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/MasterProtocolTest.java#L31) fails on my machine.
It seems to internally throw the following exception when initializing the SSLContext and then falls back to HTTP [here](https://github.com/fabric8io/kubernetes-client/blob/6f6558b15ba9ef5f27a39e077e9205a7f214ccfb/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java#L64):
```
JcaPEMKeyConverter is provided by BouncyCastle, an optional dependency. To use support for EC Keys you must explicitly add this dependency to classpath.
```

Is this an error on my side (e.g., do I need to manually add the dependency)? I think we should at least log the exception when silently falling back to http

**Review by shawkins — APPROVED** [review]
LGTM

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by scrocquesel** [comment]
@LucaMertens thank you

**Pull request merged**
