### PR TITLE
service-catalog generator rewrite

### PR DESCRIPTION
**Pull request by Fabian-K**
[service-catalog]
- generate java classes using shared generator logic
- remove model-annotator and replace with shared model-annotator
- flatten model project setup
- add missing entrypoints for CRD ServiceBroker, ServiceClass and ServicePlan
- fix formatting of DefaultServiceCatalogClient & ServiceCatalogResourceMappingProvider

[generator]
- allow manually overwriting types like []byte

⚠️ other than the existing unit tests, I did not verify the changes on a real cluster.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
add to whitelist

**Comment by Fabian-K** [comment]
Ups 😄

**Comment by manusa** [comment]
[merge]

**Pull request merged**
