### PR TITLE
handling the indexer delete with DeletedFinalStateUnknown

### LINKED ISSUE #2994: SharedIndexInformer delete event handled via resync does not update the indexer state
If for whatever reason a delete event is missed by the ReflectorWatcher, the delete event generated by DeltaFIFO.replace will not update the indexer state.

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Possible fix for #2994 - updating the indexer state for deletes generated by resync
Fix #2994 

## Type of change
 - [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes

### CODE REVIEW

**Comment by shawkins** [comment]
Any pointers on what would be desirable as a test here would be good.

**Comment by rohanKanojia** [comment]
We have mock test here: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DefaultSharedIndexInformerTest.java

We also have got an E2E test here: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-itests/src/test/java/io/fabric8/kubernetes/DefaultSharedIndexInformerIT.java

**Review by oscerd — APPROVED** [review]

**Comment by shawkins** [comment]
@rohanKanojia I've updated the tests.

**Comment by shawkins** [comment]
Also can this be part of 5.3.x as well?  We'd like to get this fix with quarkus 1.13.x.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
Relates to: #2010

**Pull request merged**
