### PR TITLE
This will fix the issue of securityContextConstraints are not getting created

### PR DESCRIPTION
**Pull request by piyush1594**
Added an example of Security Context Constraints

Updated the docs regarding how to change apiVersion.

#962

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
add to whitelist

**Comment by rohanKanojia** [comment]
ok to test

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
@iocanel WDYT about this?

**Comment by oscerd** [comment]
Since https://github.com/fabric8io/kubernetes-model/pull/273 has been closed, I believe this one too must be closed.

**Comment by piyush1594** [comment]
@oscerd That issue is closed because of different reason. I am trying to fix this issue in the model. If that works, then we will close this, otherwise, this can be the solution for the problem.

That PR is closed right now, because of the wrong approach.

Thanks

**Comment by oscerd** [comment]
Sorry about that, I supposed it was related :-)

By the way the fix is ok, lets wait for others review.

**Comment by piyush1594** [comment]
@oscerd [#274](https://github.com/fabric8io/kubernetes-model/pull/274) will ix ths issue for SecurityContextConstraints

This PR is now adding an example of SCC and handling document changes only.

Thanks

**Comment by piyush1594** [comment]
@oscerd can you please comment retest and also review this PR now.

**Comment by oscerd** [comment]
Retest this please

**Comment by oscerd** [comment]
Maybe add an entry to the changelog forma this fix. We need to track changes better.

**Comment by oscerd** [comment]
Not sure why, but 3.6.1 job didn't restart. Maybe we can close and reopen the PR

**Comment by oscerd** [comment]
ok to test

**Comment by piyush1594** [comment]
@oscerd 

Let's keep this PR on hold, I am currently working on #969 .

As we already added the support for PodSecurityPolicy in Model. I think after resolving #969, if everything works fine, we can do a release of the model project and subsequent model version changes in client and this will only get fixed after using the latest model.

WDYT?

Thanks

**Comment by oscerd** [comment]
Yeah, lets do in this way. I forgot that we aren't using snapshot of kube-model here.

**Comment by oscerd** [comment]
retest this please

**Pull request merged**
