### PR TITLE
Migrate to SnakeYAML Engine

### PR DESCRIPTION
**Pull request by manusa**
## Description

Supersedes closes #4753

> Migrate from SnakeYAML to [SnakeYAML Engine](https://bitbucket.org/snakeyaml/snakeyaml-engine)

_Originally posted by @asomov in https://github.com/fabric8io/kubernetes-client/pull/4753_

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by asomov** [comment]
@manusa do you expect anything from me or you can continue ?

**Comment by manusa** [comment]
> @manusa do you expect anything from me or you can continue ?

Hi @asomov,

I created a new PR because I couldn't push to your branch, the CI failures are unrelated to these changes. I'll merge once they're green.

Thanks a lot for these changes :raised_hands:

**Comment by asomov** [comment]
@manusa can you please clarify why a dependency to SnakeYAML was added back ? I removed it to use the SnakeYAML Engine

**Comment by manusa** [comment]
The dependency is **only** added for the Karaf Bundle.

Jackson Dataformat YAML has a transitive dependency to SnakeYAML (2.14.2 -> 1.33). Karaf requires to add the bundle to the container in order to be able to run the **test** application.

So yes, our internal usage of SnakeYAML has now shifted to SnakeYAML Engine thanks to your changes. However, I guess Jackson is still using the regular SnakeYAML.

_I'm also assuming that Jackson does a responsible use of SnakeYAML internally._

**Comment by asomov** [comment]
@manusa thank you for the clarification.

> I'm also assuming that Jackson does a responsible use of SnakeYAML internally.

correct assumption (but the quasi-security tooling still creates a false positive for Jackson)

Jackson already migrated to SnakewYAML Engine in version 3.0

**Comment by manusa** [comment]
> Jackson already migrated to SnakewYAML Engine in version 3.0

I guess someone had something to do with that :) https://github.com/FasterXML/jackson-dataformats-text/pull/106

Looking forward for the 3.0 release

**Pull request merged**
