### PR TITLE
add non-running informer to Informable interface

### PR DESCRIPTION
**Pull request by pH14**
## Description

We make heavy use of CRDs and are in the process of migrating from 5.0 to the latest. One thing we've run into in transitioning from the deprecated `client.informer().sharedIndexInformerFor(...)` family of methods to `client.resource(...).inform(...)` is that the new methods / `Informable` interface always return an Informer that is already running, whereas the deprecated methods return Informers that need an explicit `run()`. The primary difference for us is that we pass around the Informer and add a bunch of event handlers / indexers after it's created, which can't be done if the Informer is already running.

This PR adds a `runnableInformer` method to `Informable` that gives the option of returning an `Informer` that is not already running. We're running this patch on our operators internally already and it's been looking good so far 😄 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by shawkins** [comment]
We debated about whether it made sense to add something like this initially.  The idea was that simplicity and consistency with something like a watch was desirable.

What about a signature like informer(long resync) or runnableInformer(long resync) - and omit the handler, that would be the most consistent with the old factory method.

**Comment by pH14** [comment]
Updated the method to simply be `runnableInformer(long resync)` + added a changelog entry. LMK if anything else is needed, and thank you for the quick response! 🙇

**Review by shawkins — COMMENTED** [review]
LGTM

>  The primary difference for us is that we pass around the Informer and add a bunch of event handlers / indexers after it's created, which can't be done if the Informer is already running.

You should be able to add handlers after an informer is running.  There is currently no facility to remove them though.

If it makes sense for your usage, adding indexers to a running informer seems like a pretty small set of changes.

**Review by rohanKanojia — APPROVED** [review]

**Review by shawkins — APPROVED** [review]
Marking as approved this time.

**Comment by manusa** [comment]
Hi, there are merge conflicts. Since the branch belongs to HubSpot and I don't have permissions I cannot resolve them myself. Could you rebase please?

**Comment by pH14** [comment]
Resolved the changelog entry. 

I don't have merge permissions, so if the change looks good could someone merge it in?

**Pull request merged**
