### PR TITLE
PodPreset Support

### PR DESCRIPTION
**Pull request by rohanKanojia**
Added support for PodPreset in client

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@oscerd : Somehow I was wasn't able to set up `PodPreset` on my minikube. Would it be ok to let this in without being actually tested on real cluster? Wdyt?

**Comment by oscerd** [comment]
What minikube version do you have? I'm not sure if it can be a problem related to this.

**Comment by rohanKanojia** [comment]
I'm using v0.30.0

**Comment by oscerd** [comment]
Did you try this?
https://github.com/kubernetes/minikube/issues/2209
In particular this?
https://github.com/kubernetes/minikube/issues/2209#issuecomment-380089059
and here too:
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use

**Comment by oscerd** [comment]
What's the status on this?

**Comment by rohanKanojia** [comment]
@oscerd : ah, sorry. Almost forgot this, Will test it and provide an update in 1-2 working days

**Comment by rohanKanojia** [comment]
@oscerd : Looks like I was having issues due to slow internet connection ;-) . Just tested it and it seems to work.

**Comment by oscerd** [comment]
[merge]

**Pull request merged**
