### PR TITLE
Fix #4312: fix timestamp can't be deserialized for IstioCondition

### LINKED ISSUE #4312: istio Timestamp type should be mapped to String type in java
### Describe the bug

in istio generators, there's such code block that converts istio Timestamp to Long
```go
manualTypeMap := map[reflect.Type]string{
		reflect.TypeOf(types.BoolValue{}):   "java.lang.Boolean",
		reflect.TypeOf(types.DoubleValue{}): "java.lang.Double",
		reflect.TypeOf(types.Duration{}):    "java.lang.String",
		reflect.TypeOf(types.Timestamp{}):   "java.lang.Long",
		reflect.TypeOf(types.Int32Value{}):  "java.lang.Integer",
		reflect.TypeOf(types.UInt32Value{}): "java.lang.Integer",
	}
```

according to istio doc, it will be marshaled to string in RFC-3339 string
and one example is `lastTransitionTime` on [istio offical site](https://istio.io/latest/docs/reference/config/config-status/#the-conditions-field:~:text=%3A%0A%20%20%2D%20lastProbeTime%3A%20null-,lastTransitionTime,-%3A%20%222019%2D12%2D26T22%3A06)

strings can't be deserialized into java Long type

### Fabric8 Kubernetes Client version

6.0.0

### Steps to reproduce

copy yaml
```yaml
  - lastProbeTime: null
    lastTransitionTime: "2019-12-26T22:06:34Z"
    message: "61/122 complete"
    reason: "stillPropagating"
    status: "False"
    type: Reconciled
```
and do deserialization with type IstioCondition

### Expected behavior

successful deserialization

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell
enterprise-customized k8s
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yimoucao**
## Description
Fix #4312

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by manusa** [comment]
cc/ @Sgitario

**Review by manusa — CHANGES_REQUESTED** [review]
You will need to regenearte de model and persist the applicable generated classes changes.

You can read more about this at https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-model-generator

**Review by Sgitario — APPROVED** [review]

**Comment by yimoucao** [comment]
@manusa thx. I ll do it during some spare time

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
