### PR TITLE
Fix #1361: Kubernetes was relax restrictions on environment variable names.

### LINKED ISSUE #1361: Kubernetes was relax restrictions on environment variable names.
Reopen: #447 
[Kubernetes was relax restrictions on environment variable names.](https://github.com/kubernetes/kubernetes/pull/48986)
Sample code:
```yaml
          env:
            - name: "cluster.name"
              value: "elasticsearch-cluster-1550544058281"
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: "discovery.zen.ping.unicast.hosts"
              value: "elasticsearch-discovery-1550544058281"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms8192m -Xmx8192m"
```
Error message:
```
javax.validation.ConstraintViolationException: Constraint Validations: name must match "^[A-Za-z_][A-Za-z0-9_]*$" on bean: EnvVar(name=cluster.name, value=elasticsearch-cluster-1550544067656, valueFrom=null, additionalProperties={})
```

### PR DESCRIPTION
**Pull request by chenlein**
@rohanKanojia : 
Fixes #1361

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@chenlein : Thanks, Will look into this as soon as I get time ;-)

**Comment by chenlein** [comment]
@rohanKanojia : I modified the DeploymentTest.java to test EnvName, and the `DeploymentTest` can passed:
```
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.656 s - in io.fabric8.kubernetes.api.model.DeploymentTest
[INFO] Running io.fabric8.kubernetes.api.model.ValidationTest
```

But the tests failed, the error message:
```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.829 s <<< FAILURE! - in io.fabric8.kubernetes.RoleBindingIT
[ERROR] delete(io.fabric8.kubernetes.RoleBindingIT)  Time elapsed: 0.225 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
	at io.fabric8.kubernetes.RoleBindingIT.delete(RoleBindingIT.java:177)
```
and
```
[ERROR] Tests run: 6, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 94.052 s <<< FAILURE! - in io.fabric8.kubernetes.DeploymentIT
[ERROR] delete(io.fabric8.kubernetes.DeploymentIT)  Time elapsed: 30.952 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition io.fabric8.commons.ReadyEntity was not fulfilled within 30 seconds.
	at io.fabric8.kubernetes.DeploymentIT.delete(DeploymentIT.java:131)

[ERROR] update(io.fabric8.kubernetes.DeploymentIT)  Time elapsed: 30.64 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition io.fabric8.commons.ReadyEntity was not fulfilled within 30 seconds.
	at io.fabric8.kubernetes.DeploymentIT.update(DeploymentIT.java:121)

[ERROR] waitTest(io.fabric8.kubernetes.DeploymentIT)  Time elapsed: 30.594 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition io.fabric8.commons.ReadyEntity was not fulfilled within 30 seconds.
	at io.fabric8.kubernetes.DeploymentIT.waitTest(DeploymentIT.java:139)
```
I don't know why DeploymentTest's change will cause RoleBindingIT's failure. Can you give me some hints?

**Comment by rohanKanojia** [comment]
@chenlein : Our tests are flaky ;-( . It's not you, it's us.

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
