### PR TITLE
fix: #843 Use a blocking stream pumper for logging and a non blocking…

### PR DESCRIPTION
**Pull request by iocanel**
… stream pumper for exec.

### CODE REVIEW

**Comment by iocanel** [comment]
@jwendell: Wanna have a look and tell me if this works for you?

**Comment by jwendell** [comment]
sure

**Comment by jwendell** [comment]
@iocanel it's working in the sense I'm now getting the data. But in the end of the connection I get (running the PodLogExample):
```
14:42:12.984 [pool-2-thread-1] ERROR java.io.InputStreamReader - Error while pumping stream.
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230) ~[okio-1.13.0.jar:?]
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285) ~[okio-1.13.0.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241) ~[okio-1.13.0.jar:?]
	at okio.RealBufferedSource.request(RealBufferedSource.java:67) ~[okio-1.13.0.jar:?]
	at okio.RealBufferedSource.require(RealBufferedSource.java:60) ~[okio-1.13.0.jar:?]
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:294) ~[okio-1.13.0.jar:?]
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444) ~[okhttp-3.8.1.jar:?]
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425) ~[okhttp-3.8.1.jar:?]
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:430) ~[okio-1.13.0.jar:?]
	at java.io.InputStream.read(InputStream.java:101) ~[?:1.8.0_144]
	at io.fabric8.kubernetes.client.utils.BlockingInputStreamPumper.run(BlockingInputStreamPumper.java:53) [kubernetes-client-2.6-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_144]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_144]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_144]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_144]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_144]
	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_144]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[?:1.8.0_144]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940) ~[?:1.8.0_144]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[?:1.8.0_144]
	at okio.Okio$2.read(Okio.java:139) ~[okio-1.13.0.jar:?]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.13.0.jar:?]
	... 13 more
```

**Comment by iocanel** [comment]
I don't know why but it seems that the pod log example doesn't work at all for me. I never get a response back. Maybe I just need a clear head :-)

**Comment by jwendell** [comment]
@iocanel Take a look at https://github.com/fabric8io/kubernetes-client/pull/873
It might be the log level. Try setting it to INFO.

**Comment by iocanel** [comment]
[merge]

**Pull request merged**
