### PR TITLE
Adding the missing statefulset handler

### PR DESCRIPTION
**Pull request by nicolaferraro**
Cannot perform e.g. delete without this.

### CODE REVIEW

**Comment by jimmidyson** [comment]
retest this please

**Comment by pavolloffay** [comment]
I hit the same issue. What is missing to merge this?

**Comment by pavolloffay** [comment]
I have submitted improved version readiness check https://github.com/fabric8io/kubernetes-client/pull/814

**Comment by iocanel** [comment]
@nicolaferraro: I am really really sorry! I didn't realize that your pull request was prior to @pavolloffay.

**Comment by iocanel** [comment]
I will merge anyway

**Pull request merged**
