### PR TITLE
Resolve certificate files relative to the config file directory.

### LINKED ISSUE #468: Files from kube configs should be resolved relative to the kube config
Given `~/.kube/config`
```
...
- cluster:
    certificate-authority: stage/ca.pem
...
```

When searching for the certificate authority, `kubectl` attempts to read `~/.kube/stage/ca.pem`. Unfortunately `kubernetes-client` currently attempts to read `$CWD/stage/ca.pem` instead, where `$CWD` is wherever you happen to be running your binary.

### PR DESCRIPTION
**Pull request by mikekap**
Fixes #468

### CODE REVIEW

**Comment by mikekap** [comment]
@jimmidyson as requested, I think this PR has the fix.

**Comment by jimmidyson** [comment]
LGTM - thanks!

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
