### PR TITLE
Iss 3538

### LINKED ISSUE #3538: Prometheus API doesn't work
I installed Prometheus-Operator on Openshift server v4.8, then I created an Openshift client and call Prometheus API to generate a Prometheus server on Openshift project.

```
OpenShiftClient osClient = new DefaultOpenShiftClient();
Prometheus prometheus = load(template);
osClient.monitoring().prometheuses().inNamespace(namespace).create(prometheus);
```
It doesn't work and return an exception.

`
Resolved [io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.openshift.example.com:6443/apis/monitoring.coreos.com/v1/namespaces/test/prometheus. Message: 404 page not found
`

I tried to debug and found that the Pluralize returns the wrong plural for Prometheus type. It should be **_prometheuses_**, not **_prometheus_**

This issue will happen on other version of Openshift, too.

### PR DESCRIPTION
**Pull request by nautiam**
Signed-off-by: Hoang Anh Tuan <anhtuan0105@gmail.com>

## Description

Fix #3538
Fix the issue [#3538](https://github.com/fabric8io/kubernetes-client/issues/3538)
Add a new rule for Prometheus Plural
## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Could you please add a test in `kubernetes-tests` also to verify if correct URL is hit after this change? For Example: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/openshift/client/server/mock/PrometheusRuleTest.java#L68

**Review by rohanKanojia — APPROVED** [review]

**Review by shawkins — APPROVED** [review]
LGTM

@manusa @rohanKanojia I'm not familiar enough to know off-hand if it's available, but is there any chance that the Plural annotation could be added generation logic?

**Comment by rohanKanojia** [comment]
+1 to adding this to generation logic. Annotation seems to be there in model(was introduced by Chris during his CustomResource API refactor) but I don't see it being added in core types.

**Comment by manusa** [comment]
I really dislike the way we are doing this right now. I'm not sure if the plural information can be extracted from the Go sources. If it can, then that's the way for sure.
The annotation is there for the plural. Moreover, we should be using the rest of annotations (if possible) and make everything more consistent.

**Review by manusa — APPROVED** [review]

**Pull request merged**
