### PR TITLE
(Chore) : Update okhttp version to 3.12.0

### PR DESCRIPTION
**Pull request by rohanKanojia**

### CODE REVIEW

**Comment by oscerd** [comment]
This is because the test is trying to install the snapshot in a Karaf container.. So you need to check the Karaf feature and update the feature dependency accordingly to okhttp-client 3.12.0

**Comment by oscerd** [comment]
And Welcome to OSGi!

**Comment by rohanKanojia** [comment]
@oscerd : What's OSG?

**Comment by oscerd** [comment]
This https://www.osgi.org/

Karaf is an OSGi container.

**Comment by rohanKanojia** [comment]
ok, thanks. let me check and update

**Comment by oscerd** [comment]
https://github.com/fabric8io/kubernetes-client/blob/master/platforms/karaf/features/src/main/resources/feature.xml

You have to work on this mainly

**Comment by rohanKanojia** [comment]
I've updated pom with the latest version of mockwebserver `0.1.1`

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
