### PR TITLE
Fix #2684: Update Kubernetes Model to v1.20.2

### LINKED ISSUE #2684: Update Kubernetes Model to Kubernetes 1.20.0
Kubernetes 1.20.0 got released[0] a few weeks ago. We should update our model in the upcoming releases. Here is the release announcement blog[1]

[0] https://github.com/kubernetes/kubernetes/releases/tag/v1.20.0
[1] https://kubernetes.io/blog/2020/12/08/kubernetes-1-20-release-announcement/

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #2684
- Updated Kubernetes Model to v1.20.2
- Remove kubernetes-model-settings as v1alpha1 PodPreset API got removed
  in Kubernetes 1.20.x
- Remove client.settings() DSL and related classes from KubernetesClient interface
- Added v1 models for scheduling, certificates, event, and admission

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [X] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx

**Comment by manusa** [comment]
[merge]

**Comment by zhengbin163** [comment]
When will it be released this future, that support the kubernetes 1.20?

**Comment by manusa** [comment]
Already released: https://github.com/fabric8io/kubernetes-client/releases/tag/v5.1.0

image

**Comment by zhengbin163** [comment]
# thank you

**Comment by zhengbin163** [comment]
# thank you

**Comment by zhengbin163** [comment]
# thank you

> Already released: https://github.com/fabric8io/kubernetes-client/releases/tag/v5.1.0
> 
> image

**Pull request merged**
