### PR TITLE
Various fixes:

### PR DESCRIPTION
**Pull request by jimmidyson**
* Connection pooling fixes
* Exception handling fix
* Rolling update better error handling

### CODE REVIEW

**Comment by jimmidyson** [comment]
@iocanel Could you take a look please, especially at the WatchConnectionManager changes - this now reconnects in new thread so that existing connections are closed properly (hopefully).

**Comment by jimmidyson** [comment]
@iocanel Any more thoughts? Want to get this merged if you're happy with it.

**Comment by jimmidyson** [comment]
I'm going to merge this as I'm pretty confident it fixes the issues. Can always revert or fix any other bugs it introduces.

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
[merge]

**Comment by hsaputra** [comment]
Hello, what version of the library does this fix included?

**Comment by iocanel** [comment]
@hsaputra: 1.3.75 onward should contain the fix. The current is 1.3.86.

**Comment by hsaputra** [comment]
Thanks @iocanel !

**Comment by hsaputra** [comment]
@iocanel : Is there any compatibility versions between the client and Kubernetes APIs?

I am using 1.3.86 and seemed like getting 400 to connect to Kubernetes 1.1

**Comment by hsaputra** [comment]
What is the latest release of kubernetes-client that will work well with k8s 1.1 and not have thread leaks?

**Comment by iocanel** [comment]
@hsaputra: sorry for the delayed response. Can you please provide some more issue on the thread leak?

**Comment by hsaputra** [comment]
@iocanel : It looks like the problem from our side to not close the watch whenever we create client instance.

**Comment by iocanel** [comment]
@hsaputra: phew :-)

**Pull request merged**
