### PR TITLE
Added Boomerang Flow to the list of communities

### PR DESCRIPTION
**Pull request by tlawrie**
## Description
Added Boomerang Flow to the list of communities using Fabric8. Boomerang Flow is a cloud-native workflow automation tool that uses the Fabric8 Kubernetes Client and Fabric8 Tekton Client under the covers.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by manusa** [comment]
I'm failing to see where the client is actually used within the Boomerang organization.

The only reference I could find was in an issue in the Roadmap: https://github.com/boomerang-io/roadmap/issues/119

**Comment by manusa** [comment]
I'm also seeing this: https://github.com/boomerang-io/flow.service.controller/blob/47f5c3c1380d2efe7c26342141f105a5540a49ac/pom.xml#L128

Is the main branch going to be updated too?

**Comment by tlawrie** [comment]
Hi @manusa yes. The repository that implements it is the controller and currently on a feature branch where we have migrated from the standard kubernetes client using Kubernetes Jobs to the Fabric8 client with the Tekton extension.

This will be merged in as part of Flow 3.3 (June)

**Comment by manusa** [comment]
Given this fact, we can delay the merge to your 3.3 release so that we don't confuse users.
There's already a lot of confusion between the official client and ours and we don't to increase this confusion.

**Comment by tlawrie** [comment]
Hi @manusa this has now been merged in.

**Review by manusa — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
