### PR TITLE
Cloning http client in the watch method to fix #205.

### LINKED ISSUE #205: Kubernetes client should use cloned OkHttpClient in watch method
I wanted to watch kubernetes endpoints using the java client:

```java
watch = client.endpoints().withLabels(labels).watch(watcher);
// Once I'm fine with watching, it should discard the watch
watch.close();
```

This code snippet worked fine until it performed second watch. Following exception was thrown:

```
java.util.concurrent.RejectedExecutionException: Task com.squareup.okhttp.Call$AsyncCall@35ca42f1 rejected from java.util.concurrent.ThreadPoolExecutor@72f61470[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[?:1.8.0_45-internal]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_45-internal]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_45-internal]
	at com.squareup.okhttp.Dispatcher.enqueue(Dispatcher.java:110) ~[okhttp-2.5.0.jar:?]
	at com.squareup.okhttp.Call.enqueue(Call.java:113) ~[okhttp-2.5.0.jar:?]
	at com.squareup.okhttp.OkHttpClient$1.callEnqueue(OkHttpClient.java:133) ~[okhttp-2.5.0.jar:?]
	at com.squareup.okhttp.ws.WebSocketCall.enqueue(WebSocketCall.java:113) ~[okhttp-ws-2.5.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:105) ~[kubernetes-client-1.3.57.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:75) ~[kubernetes-client-1.3.57.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:438) ~[kubernetes-client-1.3.57.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:433) ~[kubernetes-client-1.3.57.jar:?]
```

The root cause of this exception is terminated dispatcher' ThreadPoolExecutor. How it could happen?

```java
watch.close();
```

The close method just calls ...

```java
clonedClient.getDispatcher().getExecutorService().shutdown();
```

... which means that the dispatcher is now discarded. 

According to the watch method source code:

```java
  public Watch watch(String resourceVersion, final Watcher<T> watcher) throws KubernetesClientException {
    try {
      return new WatchConnectionManager(client, this, resourceVersion, watcher, config.getWatchReconnectInterval(), config.getWatchReconnectLimit());
    } catch (MalformedURLException | InterruptedException | ExecutionException e) {
      throw KubernetesClientException.launderThrowable(e);
    }
  }
```

and the ctor ...

```java
public WatchConnectionManager(final OkHttpClient clonedClient ...
```

... I would say that the client should be cloned e.g.:

```java
eturn new WatchConnectionManager(client.clone() ...
```

as the clone method is implemented.

### PR DESCRIPTION
**Pull request by MartinPodval**

### CODE REVIEW

**Comment by jimmidyson** [comment]
OK to test

**Comment by jimmidyson** [comment]
LGTM thanks!

**Comment by iocanel** [comment]
LGTM too :-)

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
