### PR TITLE
Fixes for #218

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by jimmidyson** [comment]
So how do we ensure the underlying `ThreadPoolExecutor` doesn't get closed when apapted client gets closed?

**Comment by iocanel** [comment]
We don't! The question is should we?

**Comment by jimmidyson** [comment]
Yes! We close the thread pool on `client.close()` so any adapted client close would close thread pool for all clients. This is not a good thing.

**Comment by iocanel** [comment]
The only problem I see in this is that we change the existing behaviour it might break code people upgrading. Besides that I think that this is the idea way of working (more like a cast not less like a factory).

**Comment by jimmidyson** [comment]
As long as we protect the thread pool then I don't see how it would break existing behaviour?

**Comment by iocanel** [comment]
and how do you propose we do that?

**Comment by iocanel** [comment]
I think I have an idea.

**Comment by iocanel** [comment]
which was not a very good one.

honestly I can't think of anything that doesn't classify as "Micky Mouse" hacks.

**Comment by jimmidyson** [comment]
I knew you would if I waited long enough :-b

**Comment by jimmidyson** [comment]
Damn. All I could think of is some kind of reference counter. Or perhaps we forget about doing this & not worry about multiple thread pools being created...

**Comment by jimmidyson** [comment]
If it's helpful we could create our own `ExecutorService` & pass it to the first original `OkHttpClient` created.

**Comment by jimmidyson** [comment]
So a custom `ExecutorService` that holds a reference count that we could increment/decrement  on clone/close & shutdown when zero?

**Comment by iocanel** [comment]
I'd rather knowingly break forward compatibility, than do it by mistake while counting refs :-)

**Comment by jimmidyson** [comment]
What's your idea that would break forwards compatibility?

**Comment by jimmidyson** [comment]
Discussed on IRC - happy with this approach now as long as we also document that only the original client should be `close`d.

**Comment by iocanel** [comment]
[merge]

**Comment by jimmidyson** [comment]
:+1:

**Pull request merged**
