### PR TITLE
Fix #1957: Build Failing on CI Due to Central repository moving to HTTPS

### LINKED ISSUE #1957: Build Failing on CI Due to Central repository moving to HTTPS
We're getting 501 while downloading dependencies during build. 

Beginning January 15, 2020, The Central Repository will no longer support communication over HTTP. Any attempts to access http://repo1.maven.org and http://repo.maven.apache.org/ will result in an error, and users will need to update their builds to resolve dependencies over HTTPS. @oscerd pointed this out when builds started failing 

https://support.sonatype.com/hc/en-us/articles/360041287334

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #1957 
Changed url in Karaf tests to https

### CODE REVIEW

**Comment by rohanKanojia** [comment]
retest this please

**Comment by manusa** [comment]
Karaf test has been failing for the past few days in every other PR.

**Comment by rohanKanojia** [comment]
@manusa : hmm, I see. Let me try to get this merged as soon as I can. The problem is it's intermittent. To reproduce it you need to remove local maven cache every time

**Comment by manusa** [comment]
Builds are failing in my local environment for some days now. We need to update the karaf test, it looks like it launches some  container with Karaf but it's not able to connect, probably something changed in the launched image and our connection params are no longer valid.

**Comment by rohanKanojia** [comment]
retest this please

**Comment by rohanKanojia** [comment]
okay, upgrading maven seems to fix this

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
