### PR TITLE
Support unmarshalling multiple yaml documents the same way as json documents

### PR DESCRIPTION
**Pull request by Vlatombe**
There was an inconsistency between how `unmarshal(InputStream is, Map<String, String> parameters)` and `unmarshal(InputStream is, ObjectMapper mapper, Map<String, String> parameters)` were implemented.

This fixes the inconsistency and allows to unmarshal several yaml documents into Kubernetes resources easily.

### CODE REVIEW

**Comment by piyush1594** [comment]
ok to test

**Comment by piyush1594** [comment]
retest this please

**Comment by Vlatombe** [comment]
@rohanKanojia 'test' build doesn't exist anymore and I have no idea on how to get the results for the Openshift runs.

**Comment by rohanKanojia** [comment]
retest this please

**Comment by rohanKanojia** [comment]
@Vlatombe : CircleCi builds run whenever you update your PR ;-) . bdw, you can check for these failing tests locally also. I also tried running them on my machine ... but they were failing. Would really appreciate if you could check.

**Comment by rohanKanojia** [comment]
@Vlatombe : They are running fine. I just checked. Could you please check again if you have missed something? Try running `mvn clean install` on top of your tree.

**Comment by Vlatombe** [comment]
These 2 are consistently failing for me on master with a clean build.

```
[ERROR] Errors:
[ERROR]   ServiceTest.io.fabric8.kubernetes.karaf.itests.ServiceTest » Runtime Cannot ge...
[ERROR]   JUnit4Provider.invoke:160->executeTestSet:239->executeWithRerun:275->execute:369 » Runtime

[ERROR] Tests run: 5, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by rohanKanojia** [comment]
@Vlatombe : that's strange, as it seems to be passing for me. Here are the [logs](https://paste.fedoraproject.org/paste/ucS3gDXLX73~M3lbH-36fw).

**Comment by rohanKanojia** [comment]
@Vlatombe : Yeah, you're right. I cleaned up my `.m2` directory and now I'm facing it too :-(

**Comment by rohanKanojia** [comment]
@Vlatombe : I rebased and pushed your PR and I see some test failures. Would really appreciate if you could find time to update this.

**Pull request closed without merging**
