### PR TITLE
#2389: Use https value with crud mode in KubernetesServer

### PR DESCRIPTION
**Pull request by coopstah13**
Fix for #2389 

When using the KubernetesServer JUnit rule in crud mode the KubernetesMockServer is using a hardcoded value of true for https instead of using the value of https provided to the JUnit rule.

I did select this is a breaking change, because I guess technically it is. If people were specifying false here, they were still getting https in their mock server.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
retest this please

**Comment by rohanKanojia** [comment]
@coopstah13 : Could you please rebase with master and push? The failing test has been fixed in #2393

**Comment by manusa** [comment]
[merge]

**Pull request merged**
