### PR TITLE
fix #4885: addressing a potential hang with jdk streams

### LINKED ISSUE #4885: JDK client hanging on PodIT
Some of the e2e tests with the jdk client are hanging during the run of PodIT - it's not clear which test is the issue.  It should be one of the ones that deals with a stream read or other action that has an indefinite timeout.

### PR DESCRIPTION
**Pull request by shawkins**
## Description

Fix #4885

Addresses PodIT hanging failure with jdk by checking for complete prior to waiting - the issue is that the request for more with jdk will be executed in the calling thread which already holds the lock and can modify the complete flag prior to the wait.

There are also some failures on the JobIT log - but I have not been able to reproduce that.  There are a couple of changes here to help with that logic in general - one is better localize when more is requested.  That should be done inline with the processing call, rather than in a completion handler because it looks like they can be executed in parallel.  The other is that I don't see now anywhere in the jdk client that guarantees the supplied buffers won't change after be passed to consume.  Since we already handled that case with jetty we should do the same here.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by shawkins** [comment]
> There are also some failures on the JobIT log - but I have not been able to reproduce that.

I think I see how that is possible now - the initial speculative change was wrong.  We need to handle the done in the serialexecutor as well to ensure that the buffers that have already been sent are processed first - otherwise we're risking dropping some of that.  This seems to be more prevalent with jdk / jetty than okhttp likely due to the threading model of how consume is handled - it's an async task for okhttp.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by shawkins** [comment]
@manusa things look better with the latest e2e run.  There is a familiar looking podit failure with vertx, but on 1.25 - so that shouldn't be using containerd correct? https://github.com/fabric8io/kubernetes-client/actions/runs/4200862573/jobs/7287316314#step:5:1022

I'll see if that can be reproduced.

**Comment by manusa** [comment]
> @manusa things look better with the latest e2e run. There is a familiar looking podit failure with vertx, but on 1.25 - so that shouldn't be using containerd correct? https://github.com/fabric8io/kubernetes-client/actions/runs/4200862573/jobs/7287316314#step:5:1022
> 
> I'll see if that can be reproduced.

Nope, that one is using Minikube on baremetal with Docker.

**Comment by shawkins** [comment]
> Nope, that one is using Minikube on baremetal with Docker.

It did spawn #4891

**Pull request merged**
