### PR TITLE
NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl extends ServerSideApplicable

### PR DESCRIPTION
**Pull request by pan3793**
## Description

`CreateOrReplaceable#createOrReplace` is deprecated, and the suggestion is 
```
@deprecated please user {@link ServerSideApplicable#serverSideApply()} or attempt a create and edit/patch operation.
```

This change allows the following usage easy to migrate
```
kubernetesClient.resourceList(resources).createOrReplace()
```

```
kubernetesClient.resourceList(resources).forceConflicts().serverSideApply()
```

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by pan3793** [comment]
cc @shawkins, is the following migration right? 

```
resources.createOrReplace()
```

```
resources.forceConflicts().serverSideApply()
```

**Comment by rohanKanojia** [comment]
@pan3793 : Is this PR related to https://github.com/fabric8io/kubernetes-client/discussions/5071 ?

**Comment by pan3793** [comment]
> @pan3793 : Is this PR related to #5071 ?

Just a little. I found some issues(#5071) in `createOrReplace`, but since it was deprecated, I move to migrate instead of fixing. And found this issue on investigating migration to the suggested API

**Comment by shawkins** [comment]
> cc @shawkins, is the following migration right?

With the caveat that the user may choose not to use forcing if they want to know when there are conflicting changes.

Also unlike createOrReplace if the resourceVersion is set on the resource and a replace is attempted, it will be optimistically locked.

> This change allows the following usage easy to migrate

I was mixed on how many of these composite operations to expose.  The user also has access to resources(), so one can do whatever with resources().forEach(...) - including error handling, which is non-existent in performOperation.  

Tests are needed for this pr - you'll notice when this is executed that the fieldManager and forceConflicts are lost.  This is because a new context is created for each resource and we're specifically propagating what is applicable to the write operations in https://github.com/fabric8io/kubernetes-client/blob/7104c6f7c2f0a8a7e11ec6f974947f1a75cc2955/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationContext.java#L506

**Comment by pan3793** [comment]
> This is because a new context is created for each resource and we're specifically propagating what is applicable to the write operations

@shawkins thanks, but where can I find the definition of "what is applicable to the write operations"?

**Comment by shawkins** [comment]
> thanks, but where can I find the definition of "what is applicable to the write operations"?

In this case you are making forceConflicts and fieldManager applicable.  They would need to be added to the context https://github.com/fabric8io/kubernetes-client/blob/7104c6f7c2f0a8a7e11ec6f974947f1a75cc2955/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationContext.java#L511

**Comment by pan3793** [comment]
> I was mixed on how many of these composite operations to expose.

I would say it's a little hard for me to figure out how to handle the deprecated method invocation of this library, many suggestions in deprecated's description link to a totally different class, w/o examples. Not like the following common case

```
class Foo {

  @deprecated use `barV2` instead
  void bar() { ... }

  void barV2() { ... }
}
```

So, I think implementing this interface makes user easy to migrate.

**Comment by pan3793** [comment]
> Tests are needed for this pr - you'll notice when this is executed that the fieldManager and forceConflicts are lost.

Thanks for the tips, UT `ServerSideApplyTest` is added.

**Comment by shawkins** [comment]
Was there a reason to copy the test logic, rather than calling the methods that were already on PatchTest?

**Comment by pan3793** [comment]
@shawkins moved test case into `PatchTest`

**Review by rohanKanojia — APPROVED** [review]

**Comment by pan3793** [comment]
Test failure seems irrelevant.

**Review by shawkins — APPROVED** [review]
LGTM

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
> @shawkins @manusa is there anything I can do before it gets in?

Looks good, thx. Releasing today.

**Pull request merged**
