### PR TITLE
Fix slash missing when client config from  Config.loadFromKubeconfig

### LINKED ISSUE #1309: kubernetes versionInfo returns null
The below always returns null because the implementation is not constructing the endpoint properly and is failing to complete the HTTP request correctly.
`VersionInfo versionInfo = kubernetesClient.getVersion();`

In the ClusterOperationsImpl#fetchVersion method, it should be 
`Builder requestBuilder = (new Builder()).get().url(this.config.getMasterUrl() + "/" + this.versionEndpoint);`
The path separator is missing.

Line 43:
https://github.com/fabric8io/kubernetes-client/blob/59e5b9d0f318f4f78f417efaec34050ed8122b8f/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterOperationsImpl.java

### PR DESCRIPTION
**Pull request by candyleer**
Fixes #1309

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@candyleer : Thanks, Could you please add a line to CHANGELOG.md regarding this? I think we're good to merge this

**Comment by candyleer** [comment]
@rohanKanojia ok, wait a moment

**Comment by candyleer** [comment]
CHANGELOG has been added.BTW. do you have schedule to release `4.1.2`?

**Comment by rohanKanojia** [comment]
@candyleer : I'm planning to release in first week of February

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
