### PR TITLE
chore: create Jandex index

### PR DESCRIPTION
**Pull request by gastaldi**
This makes lookup of classes faster in environments that use Jandex, providing better performance in some environments

### CODE REVIEW

**Comment by gastaldi** [comment]
@rohanKanojia tests passed but I don't know why the `license-check` and the `test` check are still on `Expected - Waiting for status to be reported` status

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@gastaldi : we have to whitelist PRs first ;-)

**Comment by gastaldi** [comment]
Ok to test

**Comment by rohanKanojia** [comment]
[merge]

**Comment by iocanel** [comment]
@gastaldi: I like the way you think!

**Pull request merged**
