### PR TITLE
OSFUSE-143: Use snakeyaml 1.8 on the redhat branches

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by davsclaus** [comment]
Okay snake 1.8 is not an osgi bundle, so we have to use 1.16 etc.

**Comment by iocanel** [comment]
Wrap protocol isn't installed OOTB in the minimal distribution of karaf that is used for testing.
We need to configure the test distro to include the wrap protocol in the startup, so that we can get this working. 

Something like this: https://github.com/iocanel/kubernetes-client/commit/9f3261bbaf1e5b0d3aa497d962e6e903c800affe

**Comment by jimmidyson** [comment]
I think it best we upgrade to align with EAP7's dependency version: 1.15

**Comment by davsclaus** [comment]
closing as 1.8 is not osgi compliant

**Pull request closed without merging**
