### PR TITLE
Fix #3506: Add Extension for Open Cluster Management

### LINKED ISSUE #3506: Request to extend model to cover ACM
Hi team,

I would like to request the extension of the model to cover also Advanced Cluster Management. Currently our team is using the library in order to deploy clusters with ACM and it was required to extend the model to some of the following objects:
- ClusterDeployment
- ClusterDeploymentControlPlaneConfig
- ClusterDeploymentPlatform
- InstallConfig
- ManagedCluster
- etc.

In addition, would it be ideal to take advantage of the different functions available out of the box by RHACM as Java methods:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html-single/apis/index#rhacm-docs_apis_cluster_jsoncreatecluster

Thanks

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #3506: 

+ Add Extension for [Open Cluster Management](https://open-cluster-management.io/)
+ Add OpenShift Hive and Installer Model Modules and DSL support
  Add two new openshift model modules to Kubernetes Model Generator
    - OpenShift Hive: contains resources in `hive.openshift.io` apiGroup
    - OpenShift Installer: contains `InstallConfig` resource which is required by OpenShift installer and is referenced in ClusterDeployment
    
    These resources are not directly available in fresh OpenShift install. They are enabled by installing their respective operators. I added them in OpenShift Model instead of Open Cluster Management because they are in OpenShift repository and their resources have `*.openshift.io` apiGroup

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [X] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [X] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by AbrahamArellano** [comment]
Hi Rohan, sorry for my late reply. 
Thanks for the amazing effort the commit looks great, however after checking the overall commit I find some points that are missing from the configuration point of view. In our case we saw those objects after using the API to create new clusters and in order to fine tune the configuration with Java objects is necessary to have a list of objects like below:

- How to create (definition) the following main objects in Java
  - ManagedCluster
     - ManagedClusterCondition
     - ManagedClusterSpec
     - ManagedClusterStatus
     
  - ClusterDeployment
     + Attributes: "baseDomain, clusterName, installed, pullSecretRef"
     - ClusterDeploymentSpec
     - ClusterDeploymentControlPlaneConfig ("controlPlaneConfig")
         - ClusterDeploymentControlPlaneConfigServingCertificates
     - ClusterDeploymentPlatform ("platform")
         - ClusterDeploymentPlatformOpenStack (is our current scenario)
              + Attributes: "cloud, credentialsSecretRef, certificatesSecretRef"
     - ClusterDeploymentProvisioning ("provisioning")
          + Attributes: "imageSetRef, installConfigSecretRef, sshPrivateKeySecretRef"

  - InstallConfig
    + Attributes: "additionalTrustBundle, baseDomain, metadata, pullSecret, sshKey"
    - InstallConfigProxy ("proxy")
       - Attributes ("httpProxy, httpsProxy, noProxy")
    - InstallConfigCompute ("compute")
        - Attributes ("name, platform, replicas")
    - InstallConfigCompute ("controlPlane")
         - Attributes ("name, platform, replicas")
    - InstallConfigNetworking ("networking")
         + Attributes: "networkType, serviceNetwork"
         - InstallConfigNetworkingClusterNetwork ("clusterNetwork")
         - InstallConfigNetworkingMachineNetwork ("machineNetwork")
    - InstallConfigPlatform ("platform")
         - InstallConfigPlatformOpenstack ("openstack")
     
- MachinePool
   - Attributes: kind, metadata
   - MachinePoolSpec ("spec")
       - Attributes: "clusterDeploymentRef, name, replicas"
       - MachinePoolPlatform ("platform")
            - MachinePoolPlatformOpenstack ("openstack")
                - Attributes: flavor

- KlusterletAddonConfig
    - Attributes: "kind, metadata"
    - KlusterletAddonConfigSpec ("spec")
        - Attributes: "clusterName, clusterNamespace, clusterLabels, applicationManager, policyController, searchCollector, certPolicyController, iamPolicyController, version"

**Comment by rohanKanojia** [comment]
I think for ManagedCluster is available via `ocmClient.clusters().managedClusters()`. I couldn't find ClusterDeployment, InstallConfig, MachinePool, KlusterletAddonConfig resources in the doc you shared[0]. I'll check them again.

Would it be possible for you to point me to the Github repo for these missing resources?

[0] https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html-single/apis/index#rhacm-docs_apis_cluster_jsoncreatecluster

**Comment by AbrahamArellano** [comment]
Hi Rohan,
I don't think there is any representation of such objects available. 

So for example, the customer is using the library to create such cluster deployments, defining a custom Resource through the library:

```
client
      .customResources(ClusterDeployment.class)
      .inNamespace(clusterConfig.getProjectName())
      .createOrReplace(clusterConfig);
```

So the object definition is not explicitly anywhere, but I tried to set the yaml "attributes" to which corresponds to the Java object we created. 

You could use the following doc as a reference too:
https://github.com/openshift/hive/blob/master/docs/using-hive.md#clusterdeployment

**Comment by rohanKanojia** [comment]
Thanks a lot, looks like these resources are in repositories in OpenShift Organization. I was able to find go structs for the following resources:

- ClusterDeployment https://github.com/openshift/hive/blob/master/apis/hive/v1/clusterdeployment_types.go#L515
- InstallConfig https://github.com/openshift/installer/blob/master/pkg/types/installconfig.go#L70
- MachinePool https://github.com/openshift/hive/blob/master/apis/hive/v1/machinepool_types.go#L181

But unlike Open Cluster Management which has `*.open-cluster-management.io` apiGroup. These resources have a different apiGroup (`hive.openshift.io`). Should I add them as part of this extension or a new extension?

**Comment by rohanKanojia** [comment]
@AbrahamArellano : Hi, I've added `ClusterDeployment`, `MachinePool` and all related resources in `hive.openshift.io` apiGroup in OpenShift Model as a module named `openshift-model-hive`. I've added `InstallConfig` in another module `openshift-model-installer`. 

I've added `KlusterletAddonConfig` to Open Cluster Management extension model.

I've created a demo project for examples of the resources you've mentioned above: https://github.com/rohankanojia-forks/fabric8-open-cluster-management-extension-demo . Please let me know if it's as per your expectations whenever you get some time to review this again.

**Review by manusa — APPROVED** [review]

**Pull request merged**
