### PR TITLE
fix: allowing the usage of authenticated http proxies for https

### LINKED ISSUE #6350: Proxy authentication does not work with vertx client and https endpoint
### Describe the bug

The code is using the generic proxy authentication, but vertx needs the username and password passed to it via the proxy options.

### Fabric8 Kubernetes Client version

6.13.3

### Steps to reproduce

Use proxy.usernam and proxy.password with the vertx client

### Expected behavior

Proxy authentication should work

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manusa**
## Description

Precedes (or supersedes) #6352 
Fixes #6350

This is an adaptation of #6352 with no breaking changes.

We can go forward with the changes in the HttpClient interfaces for proxy authorization credentials once this one is merged.

Please @shawkins, check everything aligns with the expected fix.

/cc @cescoffier

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by shawkins** [comment]
> Please @shawkins, check everything aligns with the expected fix.

Just a couple of thoughts - if anyone is using non-basic proxy authorization with Jetty or vert.x these changes will break that - you'll have to add back the usage of the built-in header interceptor for that to work. It would also be good to document the difference in support that Jetty and vert.x don't support non-basic http proxy authorization with https endpoints.

I'm also looking at the vertx implementation to see how easy of a fix it would be for it to consider the current header values when making the connect request. It is possible, but without changes in Netty it will report the wrong auth scheme in logging / exceptions. 

Beyond the scope of the http proxy case, the header based strategy doesn't work for socks4/5 (socks5 is talked about in the kube docs https://kubernetes.io/docs/tasks/extend-kubernetes/socks5-proxy-access-api/). For username/password authentication to work there for okhttp and jdk, we'll need to utilize their respective built-in support for authentication.

**Comment by manusa** [comment]
This should be good to go now.
It preserves the previous behavior for non-basic proxy authorization headers, in addition to including the fix for Jetty and Vert.x to be able to use basic authorization within the proxy.

Further changes in the 7.x.x release are covered in the scope of #6373 and #6372.

**Review by shawkins — CHANGES_REQUESTED** [review]
Looks good, just one small clean up.

**Comment by cescoffier** [comment]
Awesome! Thanks!

**Pull request merged**
