### PR TITLE
#1490: Fix from server resource loading

### LINKED ISSUE #1490: Resource could not be loaded
Im using client for load generic resource from server:

```java
HasMetadata oldVersion = client.resource(item).fromServer().get();
```

And got error:
```
io.fabric8.kubernetes.client.KubernetesClientException: No handler found for object:Deployment(apiVersion=apps/v1, kind=Deployment,...
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:116)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient$4.(DefaultKubernetesClient.java:144)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.resource(DefaultKubernetesClient.java:144)
```

Handler getter return null for keys exists in `RESOURCE_HANDLER_MAP`:

```
ResourceHandler<HasMetadata, ? extends VisitableBuilder<?, ?>> h = Handlers.get("deployment", "apps/v1");
```

image

I think its happend because `Key` class does not implements `equals` and `hashCode` methods

Load resource handler by `ServiceLoader` does not work because i develop Jenkins plugin which has a [custom class loading mechanics](https://jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/)

### PR DESCRIPTION
**Pull request by izhigalko**
Fix #1490

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@izhigalko : Could you please resolve conflicts and fix license headers via issuing `mvn -N license:format`

**Comment by izhigalko** [comment]
> @izhigalko : Could you please resolve conflicts and fix license headers via issuing `mvn -N license:format`

done

**Comment by rohanKanojia** [comment]
there is a conflict in changelog. Could u please rebase your branch with latest master?

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
