### PR TITLE
Adding vCommander to the list of "used by"

### PR DESCRIPTION
**Pull request by traviswinter**
Embotics vCommander uses the Kubernetes Client to connect to, inventory, and deploy objects to a host of Kubernetes clusters.

### CODE REVIEW

**Comment by oscerd** [comment]
Is vCommander open source or closed source?

**Comment by traviswinter** [comment]
Closed source - if being open source is a prerequisite for this page then
no worries! Just wanted to make sure this project gets the recognition :)

**Comment by oscerd** [comment]
@rohanKanojia @iocanel maybe we can list closed source projects too? in a different list?

**Comment by rohanKanojia** [comment]
@oscerd : +1

**Comment by oscerd** [comment]
@traviswinter can you please create a closed source list in your PR?

**Comment by traviswinter** [comment]
Sure, any preference on terminology? Open Source/Closed Source? Proprietary?

**Comment by oscerd** [comment]
Proprietary would be better. @rohanKanojia ?

**Comment by traviswinter** [comment]
How about "Propriety Platforms"?

**Comment by rohanKanojia** [comment]
@oscerd @traviswinter : Yeah, Proprietary platforms sounds nice.

**Comment by rohanKanojia** [comment]
@traviswinter : Did you close this by accident, or?

**Pull request closed without merging**
