### PR TITLE
Fix a bug where a test client is not closed in `KubernetesMockServerExtension`

### PR DESCRIPTION
**Pull request by ikhoon**
## Description

In `KubernetesMockServerExtension`, a `KubernetesClient` created by `beforeAll()` and a `KubernetesClient` created by `beforeEach()` share the same member field.

Say we have a test code that has a non-staic client field. A `KubernetesClient` created by `beforeAll()` gets overridden by a client created by `beforeEach()`. As a result, we lose the former client's reference, resulting in a leak.

```java
@EnableKubernetesMockClient
class KubernetesMockServerTest {
    private KubernetesClient client;

    ...
}
```

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@ikhoon : Could you please take a look at the sonar code smells?

**Comment by ikhoon** [comment]
Sure, I will.

**Comment by ikhoon** [comment]
Fixed the new sonar code smells except false positive ones.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by sunix — APPROVED** [review]

**Pull request merged**
