### PR TITLE
Managed Kubernetes/Openshift Client does not respect environment varables #471

### PR DESCRIPTION
**Pull request by lburgazzoli**
This should solve both #470 and #471 

@iocanel @jimmidyson can you have a look ?

### CODE REVIEW

**Comment by jimmidyson** [comment]
add to whitelist

**Comment by jimmidyson** [comment]
@lburgazzoli Would be good to get some tests in for this if you can do so easily enough.

LGTM - thanks!

**Comment by lburgazzoli** [comment]
@jimmidyson test added

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
Thanks @lburgazzoli!

**Pull request merged**
