### PR TITLE
Fix conflict in kube-validation-schema.json

### PR DESCRIPTION
**Pull request by kunal-kushwaha**
Fixed conflicts in kube-validation-schema.json due to TemplateInstance and ControllerRevision.

### CODE REVIEW

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: Can you please take a look at this?

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : Thanks for noticing, let's merge this as soon as it gets green

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
add to whitelist

**Comment by kunal-kushwaha** [comment]
@rohanKanojia : Can you please rebuild the tests?

**Comment by rohanKanojia** [comment]
ah, these flaky tests. I'll ignore these and merge this for now

**Pull request merged**
