### PR TITLE
Adding support for creating ingress through kubernetes client

### PR DESCRIPTION
**Pull request by gayanlggd**

### CODE REVIEW

**Comment by iocanel** [comment]
ok to test

**Comment by iocanel** [comment]
Looks good to me.

Can you please also add a test similar to: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java so that we can merge this?

**Comment by gayanlggd** [comment]
Ok will do.

**Comment by gayanlggd** [comment]
Tests are passed in ci/circleci. Build is failing in Jenkins. Out of space ?

[WARNING] Failed to write tracking file /home/slave/.m2/repository/io/fabric8/kubernetes-model/1.0.38/kubernetes-model-1.0.38.lastUpdated
java.io.FileNotFoundException: /home/slave/.m2/repository/io/fabric8/kubernetes-model/1.0.38/kubernetes-model-1.0.38.lastUpdated (No space left on device)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
	at org.eclipse.aether.internal.impl.TrackingFileManager.update(TrackingFileManager.java:96)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.write(DefaultUpdateCheckManager.java:617)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.touchArtifact(DefaultUpdateCheckManager.java:553)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.evaluateDownloads(DefaultArtifactResolver.java:645)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:535)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:212)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.access$000(DefaultArtifactResolver.java:74)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver$ResolveTask.run(DefaultArtifactResolver.java:602)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jimmidyson** [comment]
Sorry about that. Let me try to find someone to sort that out.

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
LGTM

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
Thanks!

**Comment by iocanel** [comment]
[merge]

**Pull request merged**
