### PR TITLE
chore(crd-generator): Add approval tests for crd-generator

### LINKED ISSUE #5850: CRDGenerator: Replace assertions with ApprovalTests
### Is your task related to a problem? Please describe

At the moment we have implemented some tests with self-developed assertions.

### Describe the solution you'd like

Those tests can be replaced by [ApprovalTests](https://github.com/approvals/ApprovalTests.Java).

This test approach is also used for the Java-Generator and requires less self developed code.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by baloo42**
## Description

Add approval tests for crd-generator

Fixes #5850

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report

### CODE REVIEW

**Comment by baloo42** [comment]
@manusa @shawkins @andreaTP: I need some initial feedback here:

1. Keep or remove the old tests (atm marked as deprecated)?
2. Structure ok?
   - Keep the examples package (which are also used by other unit tests)
   - Approval files next to test source files? (instead of somewhere in resources)
 3. Other thoughts?

I would suggest to create such a test for each of the existing examples.

If you know some missing edge cases, please let me know ;)

**Comment by manusa** [comment]
> @manusa @shawkins @andreaTP: I need some initial feedback here:
> 
>     1. Keep or remove the old tests (atm marked as deprecated)?

If the approval tests make those redundant and no production code is being touched, then remove them.


>     2. Structure ok?
>        
>        * Keep and reuse the examples package (which are also used by other unit tests)

Please, create specific test samples so we can keep a narrowed scope and purpose for the files.

>        * Approval files next to test source files? (instead of somewhere in resources)

Whatever, we're doing at the moment in other modules (keep consistent).

> If you know some missing edge cases, please let me know ;)

Yes, it would be good to have a thorough set of tests to ensure nothing breaks during upcoming refactors. I'm not a user of the crd-generator, but I encourage anyone else using it to ensure their use cases are being covered.

**Comment by baloo42** [comment]
## Usage for new tests

1. Create new package below package `approvaltests` named after the test intention
2. Add CustomResource DTO(s) to sub package `api`. Don't use examples from somewhere else to fully isolate the test.
3. Create Test class e.g. `MultipleVersionsApprovalTest` which extends  `AbstractCRDGeneratorApprovalTest`
4. Implement the two abstract methods which define the api classes under test and the expected CRD name:
```java
class MultipleVersionsApprovalTest extends AbstractCRDGeneratorApprovalTest {

  protected Class<? extends CustomResource<?, ?>>[] crClasses() {
    return new Class[] {
        io.fabric8.crd.generator.approvaltests.multipleversions.api.v1.Multiple.class,
        io.fabric8.crd.generator.approvaltests.multipleversions.api.v2.Multiple.class
    };
  }

  protected String[] expectedCRDs() {
    return new String[] {
        "multiples.sample.fabric8.io"
    };
  }
}
```
5. Run the test class. It will fail. But it will create e.g. `MultipleVersionsApprovalTest.multiples.sample.fabric8.io.v1.received.yml`
6. Review this file and rename it to e.g. `MultipleVersionsApprovalTest.multiples.sample.fabric8.io.v1.approved.yml`
7. Run the test class again. It will fail again. This time it will create e.g. `MultipleVersionsApprovalTest.multiples.sample.fabric8.io.v1beta1.received.yml`
8. Review this file and rename it to e.g. `MultipleVersionsApprovalTest.multiples.sample.fabric8.io.v1beta1.approved.yml`
9. Run test class again, now it should succeed.
10. Add the approval files to git.

### What you get

The abstract class inherits two test cases: With parallel generation enabled and disabled. In both cases the same results are expected and as such in both cases the same "golden" files are used.
By default v1 and v1beta1 are generated and verified.
The abstract class and the approval naming are aware of the CRD name. This makes it possible to generate and compare multiple CRD kinds within the same test class.

## Usage on a broken test

If a test breaks e.g. in CI, run it locally again. If it fails here too, you will get again a `[...].received.yml` file.
You can now compare the expected result (from the `[...].approval.yml` file) with the receveived one and either fix the generator or accept the changes by replacing the approval file.

(The automatic diff tool detection and opening comparisons in such a case is disabled - it has killed a few times my IDE)

**Comment by manusa** [comment]
Is this PR affected by the changes introduced in https://github.com/fabric8io/kubernetes-client/pull/5954?

**Comment by manusa** [comment]
OK, I'll probably add some changes on top and send you a PR

**Comment by manusa** [comment]
@baloo42 I've added some changes on top of your branch, please take a look and merge if you think it's OK:
https://github.com/baloo42/kubernetes-client/pull/6

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
