### PR TITLE
feat: add support for kustomize api v1beta1 (#4929)

### PR DESCRIPTION
**Pull request by hypnoce**
## Description
Generate kustomize api v1beta1 (sigs.k8s.io/kustomize/api)

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by andreaTP** [comment]
Thanks for the PR @hypnoce !
I haven't thought at it earlier, but, if you can find the source CRD (yaml or json) for: `kustomize.config.k8s.io/v1beta1/Kustomization`

we can use the `java-generator` instead of adding a new `model` sub-module.
Have you already attempted to go down this path?

**Comment by hypnoce** [comment]
> Have you already attempted to go down this path? Or am I missing something?

@andreaTP you didn't miss anything :-) I will have a look.

**Comment by andreaTP** [comment]
> you didn't miss anything :-) I will have a look.

@hypnoce keep me posted!

**Comment by hypnoce** [comment]
@andreaTP from my research, seems to be a non implemented request : https://github.com/kubernetes-sigs/kustomize/issues/205 
there is one in schema store but is not maintain by kustomize maintainers : https://github.com/kubernetes-sigs/kustomize/issues/3190#issuecomment-723215657

You prefer to generate the json or use the schema store json ?

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by manusa** [comment]
could you please fix the conflicting files :pray:

**Comment by manusa** [comment]
> @andreaTP from my research, seems to be a non implemented request : [kubernetes-sigs/kustomize#205](https://github.com/kubernetes-sigs/kustomize/issues/205) there is one in schema store but is not maintain by kustomize maintainers : [kubernetes-sigs/kustomize#3190 (comment)](https://github.com/kubernetes-sigs/kustomize/issues/3190#issuecomment-723215657)
> 
> You prefer to keep json generation or use the schema store json ?

From the context of the issue, I understood that this wasn't a CRD but part of the official types. If this is the case, then we should proceed this way for consistency and also because schemastore is updated manually.

**Pull request merged**
