### PR TITLE
[java-gen] Apply sundrio annotations to the CustomResource class

### PR DESCRIPTION
**Pull request by andreaTP**
## Description
Follow up from:
https://github.com/fabric8io/kubernetes-client/pull/3918#discussion_r818009082

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by andreaTP** [comment]
rebased and ready for review @manusa

**Review by manusa — APPROVED** [review]

**Comment by andreaTP** [comment]
Just found out that this is not enough 😞 , will follow up.

**Comment by andreaTP** [comment]
Maybe @manusa or @iocanel can help me here, I'm not sure how to tell `sundrio` to generate the builders and the fluent API for the fields of the parent `abstract class CustomResource`, any hint?

**Comment by iocanel** [comment]
@andreaTP: Usually sundrio will only generate builders and fluent apis for classes that have been explictly annotated with `@Buidlable`. When we are dealing with 3rd party classes and annotating them is not an option we have can create a dummy class and add the `@ExternalBuildables` annotations with reference to the classes we need to generate builder for. In fact this is how we originally generated the `kubernetes-model` a long time ago. 

Last but not least it should be possible to use the sundrio api to generate builders etc programmatically.

If this is not enough, let's schedule a meeting so that I can better undestand the context.

**Pull request merged**
