### PR TITLE
#1200: Support client authenticator commands like aws-iam-authenticator

### PR DESCRIPTION
**Pull request by jglick**
Rudimentary implementation of #1200. Enough to get my authentication working at least; does not implement some parts of the documented spec.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by jglick** [comment]
This probably deserves an entry in `ConfigTest`. Would the tests always be run on Linux?

**Comment by rohanKanojia** [comment]
@jglick : As per current setup, tests are running on ubuntu based environments.

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rhuss** [comment]
Any idea why the test on ci.centos.org fails with 

```
+ /usr/bin/timeout 20m ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root 172.19.2.86 -t 'cd payload && /bin/bash cico_build.sh'
Warning: Permanently added '172.19.2.86' (ECDSA) to the list of known hosts.
/bin/bash: cico_build.sh: No such file or directory
```

**Comment by rohanKanojia** [comment]
@rhuss : I'm working on moving cd pipiline on centos ci, that branch hasn't been merged into master yet, so it's failing because it's not configured. I enabled webhook because I needed it for testing cd pipeline.

**Comment by rhuss** [comment]
@rohanKanojia thanks for the explanation, makes sense.

**Comment by rohanKanojia** [comment]
[merge]

**Comment by roldevg** [comment]
@jglick Thanks for the feature. I tried now with version 4.1.2 and it works as expected.

**Pull request merged**
