### PR TITLE
fix (kubernetes-examples) : Update Slf4j Simple dependency scope to runtime (#4904)

### LINKED ISSUE #4904: [Kubernetes Examples] Samples using SLF4j in kubernetes-examples/ module don't print anything
### Is your task related to a problem? Please describe

When I run demo samples in kubernetes-example/` folder they don't seem to print anything. Instead, I get a warning related to SLF4j:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
I think it's due to provided scope of `slf4j-simple` dependency in parent pom:
```
kubernetes-examples : $ mvn dependency:tree | grep slf4j-
[INFO] +- org.slf4j:slf4j-simple:jar:1.7.36:provided
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.36:compile
```

### Describe the solution you'd like

I think we should modify sl4fj-simple dependency scope to `compile` in [kubernetes-examples/pom.xml](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/pom.xml)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #4904 

In order for Slf4j to work, it needs to be in compile scope. Otherwise we're getting failure in resolving StaticLoggerBinder errors while running samples in kubernetes-examples

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [X] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by shawkins** [comment]
@rohanKanojia sorry for the nit, but what about runtime scope?

**Comment by rohanKanojia** [comment]
@shawkins : When I change it to runtime scope, I get a compilation error at this line:
https://github.com/fabric8io/kubernetes-client/blob/2075967c013bf5154c36206c59c8ca3a75355fdf/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LeaderElectionExamples.java#L26

**Comment by shawkins** [comment]
> @shawkins : When I change it to runtime scope, I get a compilation error at this line:

Seems like that should be removed.  Turning off all logging in that example was just trying to make some of the internal logging seem less chatty than it actually is.  I think some of that has been improved but there may still be some stuff that is being inappropriately logged at warning / error that should be adjusted instead.

**Comment by rohanKanojia** [comment]
@shawkins : I've removed the abovementioned code block.

**Review by manusa — APPROVED** [review]

**Pull request merged**
