### PR TITLE
Do not repeatly create Config in exec

### LINKED ISSUE #1082: Perf: exec in PodOperationsImpl repeatly creates Config instance
https://github.com/fabric8io/kubernetes-client/blob/c78c1a49508b735c1c0d9ca7e3b375753a63952f/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java#L266

This significantly reduces performance.

### PR DESCRIPTION
**Pull request by skyline75489**
This fixes #1082

### CODE REVIEW

**Comment by oscerd** [comment]
Can you please create an issue for this and add a line in CHANGELOG?

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
ok to test

**Comment by skyline75489** [comment]
Sure. I get the CHANGELOG part. But why is an issue needed?

**Comment by oscerd** [comment]
To track what you're doing. This project need to track any change/update we do, because in the past we broke things also for minor stuff like this.

**Comment by oscerd** [comment]
Thanks a lot :-)

**Comment by piyush1594** [comment]
Please update the PR with the changes in CHANGELOG.md because that is the file we track :smiley:

**Comment by skyline75489** [comment]
Done.

**Comment by skyline75489** [comment]
Man these tests are utterly time consuming...

**Comment by piyush1594** [comment]
Sorry to say, but you need to squash the commits into one also. We have complete guidelines here https://github.com/fabric8io/kubernetes-client/blob/master/CONTRIBUTING.md

**Comment by oscerd** [comment]
Looks good.

**Comment by oscerd** [comment]
[merge]

**Comment by skyline75489** [comment]
Thanks everyone. We would love to see this be shipped soon.

**Comment by skyline75489** [comment]
Thanks for the heads up 👍

**Pull request merged**
