### PR TITLE
Fix #2319: Create Config without using auto-configure functionality or setting env variables

### LINKED ISSUE #2319: Create Config without using auto-configure functionality or setting env variables
Hi,

I´m looking for a away to create a Config without using auto-configuration functionality while not relying on env variables or properties.

Currently when constructing a config like this, it still invokes the auto-configuration. I instead want to explicitly use the values provided (as they differ in terms of authorization from what is provided via auto-configuration)

```kotlin
val config: Config = ConfigBuilder()
                    .withCaCertData(...)
                    .withUsername(...)
                    .withNamespace(...)
                    .withOauthToken(...)
                    .withMasterUrl(...)
                    .build()

val client = DefaultKubernetesClient(config)
```

Is this already possible and I´m just not seeing it? :)

Thanks, Fabian

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #2319

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [X] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
This is based on @Fabian-K 's suggestion in the issue here: https://github.com/fabric8io/kubernetes-client/issues/2319#issuecomment-659354833

**Comment by rohanKanojia** [comment]
@Fabian-K : Could you please review this whenever you find some time?

**Comment by Fabian-K** [comment]
This looks perfect, thank you!

**Comment by manusa** [comment]
[merge]

**Pull request merged**
