### PR TITLE
Mock

### PR DESCRIPTION
**Pull request by iocanel**
Here is a first draft of a simple mock DSL on top of our kubernetes client.

The idea is pretty simple you create a mock client, you use the DSL to define the expectations and when ready, you obtain the actual mock instance to use. 

In other words this is sugar that combines our DSL with EasyMock DSL. 

A simple example:

  MockClient mock = new MockClient();
   mock.pods().inNamespace("ns1").withLabel("component", "f1").list().andReturn(new PodListBuilder()
        .addNewItem()
        .withNewMetadata().withName("pod1").endMetadata()
        .endItem()
        .addNewItem()
        .withNewMetadata().withName("pod2").endMetadata()
        .endItem()
        .build()
    ).once();

    KubernetesClient client = mock.replay();
    PodList result  = client.pods().inNamespace("ns1").withLabel("component", "f1").list();
    Assert.assertNotNull(result);
    Assert.assertEquals(2, result.getItems().size());

### CODE REVIEW

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
This was just an error in the licence check build that didn't limit it to just parent module. Think we need to add aggregate option to licence plugin config too to cover submodules but this can wait if you can't be bothered ;)

**Comment by jimmidyson** [comment]
Oh & I love this mock!

**Comment by iocanel** [comment]
too tired to fight with maven plugins right now. let's see tomorrow what we can do :-)

**Comment by jimmidyson** [comment]
If you're happy to merge, merge away. We can sort licence headers out any time.

**Comment by jimmidyson** [comment]
Out of interest, why easymock instead of mockito (or other)?

**Comment by iocanel** [comment]
No reason. I am open to use anything really. In fact it might worth investigating if some limitation we currently have can be overcome by switching to an other framework.

**Comment by iocanel** [comment]
[merge]

**Pull request merged**
