### PR TITLE
Vertx client

### PR DESCRIPTION
**Pull request by vietj**
## Description

Implements some missing features

## Type of change

- proxy authorization
- InputStream async body
- WebSocket handshake failure
- SSLContext handling
- upgrade to Vert.x 4.3.7

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I have implemented unit tests to cover my changes

### CODE REVIEW

**Comment by vietj** [comment]
you can keep this PR open and in review as I will add missing features, I think the PR could become in draft mode.

**Comment by vietj** [comment]
I actually set the PR in draft mode until it get other commits, I only want for now to show the contribution I'm working on and get early feedback.

**Comment by vietj** [comment]
The test `buildAsyncIncludesRequiredHeadersAndPropagatesConfigured` cannot pass for the moment because the mock web server should signal in the handshake that it does support the subprotocol amqp and it does not.

The vertx HTTP client expects the subprotocol to be sent back by the server, otherwise it considers the handshake to be failed.

**Comment by vietj** [comment]
I think now it can be merged in the vertx-client branch

**Comment by shawkins** [comment]
Thanks @vietj we'll get it merged.

**Pull request merged**
