### PR TITLE
using a strategic merge to prevent a 422

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Addressing the integration test timing issue seen in https://github.com/fabric8io/kubernetes-client/pull/3136#issuecomment-843243513 with a strategic merge patch.

@rohanKanojia it feels a little verbose to create a patch context of a given patch type - should there be utility methods for that?

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by rohanKanojia** [comment]
sure, I think we can add some utility methods for PatchContext (maybe in KubernetesResourceUtil). Do you have some idea in mind with which we can improve readability?

**Comment by shawkins** [comment]
how about - PatchContext.of(patchType)

**Comment by rohanKanojia** [comment]
Sounds good to me.

**Review by rohanKanojia — APPROVED** [review]

**Comment by shawkins** [comment]
@manusa https://github.com/fabric8io/kubernetes-client/pull/3148/files#diff-0ae0c25ccaf88d84f2fc51e6487f7033e312ca550ce5af75ace50bdc3a75168fR90 is now the clearest expression of what you were looking for in https://github.com/fabric8io/kubernetes-client/issues/3078#issuecomment-832659015

**Pull request merged**
