### PR TITLE
remove WebSocket close in ExecWebSocketListener close function

### PR DESCRIPTION
**Pull request by fanhaozzu**
the webSocket have bean closed when dkc.pods().withName("xxxxx").xxxxx.exec(""), so it need't close the socket again.

### CODE REVIEW

**Comment by jimmidyson** [comment]
ok to test

**Comment by iocanel** [comment]
@fanhaozzu: what happens in the case where the user decides to call close() on the handle but the exec isn't over yet? Should we leave the websocket open?

I think that we should keep the webscoket.close() but we need to check if its closed already. 

@jimmidyson: wdyt?

**Comment by jimmidyson** [comment]
> I think that we should keep the webscoket.close() but we need to check if its closed already.

Sounds good to me, don't want to leave any potential connection leaks.

**Comment by iocanel** [comment]
@fanhaozzu: do you fancy updating you pull request as discussed?

**Comment by fanhaozzu** [comment]
@iocanel  @jimmidyson  it's my pleasure, i will have a try.

**Comment by fanhaozzu** [comment]
@iocanel @jimmidyson i have improve the pull request, in the new pull request 

https://github.com/fabric8io/kubernetes-client/pull/622

**Comment by iocanel** [comment]
@fanhaozzu my understanding is that since you created #622 we can close this one, right?

Please, feel free to reopen, if I misunderstood.

**Pull request closed without merging**
