### PR TITLE
Execute command on pod example

### PR DESCRIPTION
**Pull request by antoanandonov**
## Description

Example of executing commands on a pod with cleaning all the resources after the execution.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
We are using Apache 2.0 license in this project. Could you please add license header using `mvn -N license:format`

**Review by oscerd — APPROVED** [review]

**Comment by antoanandonov** [comment]
> We are using Apache 2.0 license in this project. Could you please add license header using `mvn -N license:format`

Done

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM thx!
I don't really like the Sneaky bit, but I guess it can reduce some boiler-plate for the example.

**Comment by manusa** [comment]
[merge]

**Pull request merged**
