### PR TITLE
kubernetes-client osgi manifest #473

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
Failing on circle but hard to diagnose - might be easier on jenkins :)

**Comment by jimmidyson** [comment]
This needs a rebase - we upgraded to okhttp3 in master.

**Comment by lburgazzoli** [comment]
Yep, I'm waiting for the latest servicemix release to include ohkttp 3

**Comment by jimmidyson** [comment]
OK cool.

**Comment by oscerd** [comment]
The Smx bundles for this month are on vote :-)

**Comment by lburgazzoli** [comment]
@jimmidyson rebased and improved

**Comment by jimmidyson** [comment]
@lburgazzoli @oscerd Thanks for this! I see the required SMX bundles are available from Maven central.

LGTM [merge]

**Comment by jimmidyson** [comment]
@lburgazzoli Released & available from Maven central.

**Comment by lburgazzoli** [comment]
@jimmidyson wow, that's great

**Pull request merged**
