### PR TITLE
chore: fallback to current class cloader if can't find httpClient

### LINKED ISSUE #4563: facing classloader issue with gradle
```
io.fabric8.kubernetes.client.KubernetesClientException: No httpclient implementations found on the context classloader, please ensure your classpath includes an implementation jar
    at io.fabric8.kubernetes.client.utils.HttpClientUtils.getHttpClientFactory(HttpClientUtils.java:164)
    at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:76)
    at com.metalbear.mirrord.KubeDataProvider.<init>(KubeDataProvider.kt:8)
    at com.metalbear.mirrord.MirrordListener.processStartScheduled$lambda-3(MirrordListener.kt:43)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
    at ...

```

just added the dependency like so:

```
dependencies {
    implementation("com.github.zafarkhaja:java-semver:0.9.0")
    implementation("io.fabric8:kubernetes-client:6.2.0") {
        exclude(group = "org.slf4j", module = "slf4j-api")
    }
}
```

Would really appreciate any solutions, thanks

_Originally posted by @infiniteregrets in https://github.com/fabric8io/kubernetes-client/issues/4248#issuecomment-1304583337_

### PR DESCRIPTION
**Pull request by adietish**
## Description

fixes #4563 

I added a fallback where the http client is looked up via the classloader of the `HttpUtils` class if lookup via the thread context classloader fails.
The current impl looks up a http client impl using the thread context classloader. This fails in IDEA (and also in Eclipse/OSGI) because the thread context classloader has no access to the plugin/bundle-resources. 
A typical workaround is to set the thread context classloader to the classloader of the bundle/plugin before calling the code that's using the thread context classloader. This is something one wants to avoid though, because it breaks platform isolation. 

## Type of change
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [X] I tested my code in Kubernetes
 - [X] I tested my code in OpenShift

### CODE REVIEW

**Comment by adietish** [comment]
CC: @jeffmaury ^

**Comment by shawkins** [comment]
@adietish would you mind also changing the ServiceLoader call in ServiceOperationsImpl.getUrlHelper?  So that we can all locations using a fallback as a resolution to the issue.

**Comment by adietish** [comment]
@shawkins sure, makes perfect sense.

**Comment by adietish** [comment]
@shawkins: sonar complains about missing unit tests. There are afaics currently no tests for `ServiceOperationsImpl`, correct?

**Comment by adietish** [comment]
@shawkins ok, sounds good. I added the fallback in `ServiceOperationsImpl.getUrlHelper`. Hope I met your expectations. Please review.

**Review by shawkins — APPROVED** [review]
LGTM

Thanks @adietish

**Review by manusa — APPROVED** [review]

**Comment by adietish** [comment]
@shawkins very welcome, thanks for the opportunity to contribute.

**Pull request merged**
