### PR TITLE
Added timestamps support for deployment logs

### LINKED ISSUE #4470: Timestamps for deployment logs
### Is your enhancement related to a problem? Please describe

It should be possible to get timestamps for deployment logs the same way that you can get timestamps for pod logs.

```java
KubernetesClient kubernetesClient = new KubernetesClientBuilder().build();

//Can get timestamps with .usingTimestamps() for pods
LogWatch podLogWatcher = kubernetesClient.pods().inNamespace("Foo").withName("Bar").usingTimestamps().watchLog();

//But not for deployments
LogWatch deploymentLogWatcher = kubernetesClient.apps().deployments().inNamespace("Foo").withName("Bar").watchLog();
```

### Describe the solution you'd like

It should be possible to do:

```java
LogWatch deploymentLogWatcher = kubernetesClient.apps().deployments().inNamespace("Foo").withName("Bar").usingTimestamps().watchLog();
```

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DobromirM**
## Description

Fixes #4470 
Added timestamps support for deployment logs and other resources.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [X] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by DobromirM** [comment]
Fixes #4470

**Review by shawkins — APPROVED** [review]
LGTM

The initial pr comment mentions this is a breaking change.  Can you elaborate on what behavioral changes this causes?

**Comment by DobromirM** [comment]
@shawkins Some of the changes are on public classes / interfaces so if anyone is using them directly it will break. For example if you have a custom resource that extends `interface ScalableResource<T>` then you will need to add the new methods. As far as I am aware this change does not introduce any breaking changes to the k8s client interface itself.

**Comment by shawkins** [comment]
> For example if you have a custom resource that extends interface ScalableResource<T> then you will need to add the new methods.

Thanks for the explanation.  We generally won't worry about that case - especially for a minor release.

**Comment by manusa** [comment]
> For example if you have a custom resource that extends interface ScalableResource<T> then you will need to add the new methods. As far as I am aware this change does not introduce any breaking changes to the k8s client interface itself.

Is this something someone might be actually doing? if so we should probably consider moving those interfaces to an internal package.

**Review by manusa — APPROVED** [review]
LGTM, great job, thx!

**Pull request merged**
