### PR TITLE
fix: NodeMetrics and PodMetrics can have informers

### LINKED ISSUE #3639: Cannot create informers to capture the pod metrics
Tried to create informer with resource object `PodMetrics` and observed the below error:

**Code Snippet:**
```
 client.get.resources(classOf[PodMetrics]).inform()
```

**Error message:**
```
Failure executing: GET at: https://localhost:5125/apis/metrics.k8s.io/v1beta1/namespaces/default/podmetrics. 

Message: the server could not find the requested resource. 
```

Listed the api-resources with APIVERSION "metrics.k8s.io/v1beta1":
```
nodes                                          metrics.k8s.io/v1beta1                 false        NodeMetrics
pods                                           metrics.k8s.io/v1beta1                 true         PodMetrics
```

GET URL is supposed to be `https://localhost:5125/apis/metrics.k8s.io/v1beta1/namespaces/default/pods`

@rohanKanojia Please let me know how to capture the pod metrics using informers.

### LINKED ISSUE #3668: APIServiceIT breaks the cluster's API server
### Is your task related to a problem? Please describe

When running the [APIServiceIT](https://github.com/fabric8io/kubernetes-client/blob/5596fce44f55235bade1f4c7c5798972b191911d/kubernetes-itests/src/test/java/io/fabric8/kubernetes/APIServiceIT.java) we are performing write operations to the API server that, **although allowed by the REST API**, shouldn't be performed and break the cluster.

You can easily check this by running the test and then running:
```shell
kubectl api-resources
```
You will see an error message like:
```shell
error: unable to retrieve the complete list of server APIs: get.fabric8.io/v1beta1: the server could not find the requested resource, list.fabric8.io/v1beta1: the server could not find the requested resource, update.fabric8.io/v1beta1: the server could not find the requested resource
```

This is also affecting the new `PluralizeIT` implemented in #3664 (which basically mimics what `kubectl api-resources` does.

### Describe the solution you'd like

The solution is refactor the APIServiceIT test.

Test data can be initialized using CRDs and write operations should be annotated with `@Ignore`

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manusa**
## Description

fix #3639: NodeMetrics and PodMetrics can have informers
fix #3668: APIServiceIT doesn't manipulate the API server directly (no write operations)

- Related to: #3589
  Added E2E test to make sure that Pluralize works on all cluster resources (at least on the cluster where the test is performed)
- Added integration test for top()/inform() on PodMetrics and NodeMetrics resources

@shawkins please check the following snippet:
```java
      testCases = new ArrayList<>(new OperationSupport(client.getHttpClient(), client.getConfiguration())
        .restCall(APIResourceList.class, "api/v1").getResources());
```

I didn't find a better way to list these (core) resources.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
E2E tests are failing

**Comment by manusa** [comment]
> E2E tests are failing

Checking, it must be the client initialization, it wasn't failing locally.

**Review by rohanKanojia — APPROVED** [review]

**Comment by shawkins** [comment]
@manusa there is a KubernetesClient.getApiResources("api/v1") method available

**Comment by manusa** [comment]
> @manusa there is a KubernetesClient.getApiResources("api/v1") method available

Yes, but that one is intended to be used with an api group as an argument, the resulting call would be `apis/api/v1`, what we need here is a call to `api/v1`.

The one you mention is used later on to retrieve the Resources for each of the non-core groups.

**Comment by shawkins** [comment]
> Yes, but that one is intended to be used with an api group as an argument, the resulting call would be apis/api/v1, what we need here is a call to api/v1

Sorry I missed that, there's no existing method for the call you are looking for.

**Review by shawkins — APPROVED** [review]
LGTM

**Pull request merged**
