### PR TITLE
refactor to remove thrown KubernetesClientException

### LINKED ISSUE #2579: Remove instances of declaration of  thrown exception `KubernetesClientException` from codebase
`KubernetesClientException` extends [`RuntimeException`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/RuntimeException.html):

https://github.com/fabric8io/kubernetes-client/blob/ca0a124a7695b51324ab530779dbd86b735d4f94/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java#L21

We don't really need to have it in method declaration since `RuntimeException` is an unchecked exception and can be thrown anytime. Sonar detects this as a code smell[0]. So If we're having it in code like this:
```java
public AppsAPIGroupClient(OkHttpClient httpClient, final Config config) throws KubernetesClientException {
    super(httpClient, config);
}
```
It should rather be like this:
```java
public AppsAPIGroupClient(OkHttpClient httpClient, final Config config) {
    super(httpClient, config);
}
```

Here is a simple grep to find out places where it's declared:
```bash
kubernetes-client : $ git grep -c "throws KubernetesClientException"
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/AutoAdaptableKubernetesClient.java:4
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java:4
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BatchAPIGroupClient.java:2
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/ExtensionsAPIGroupClient.java:2
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/MetricAPIGroupClient.java:2
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/NetworkAPIGroupClient.java:2
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/RbacAPIGroupClient.java:2
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SchedulingAPIGroupClient.java:1
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/SettingsAPIGroupClient.java:1
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/StorageAPIGroupClient.java:2
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java:17
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java:16
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java:2
kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java:5
openshift-client/src/main/java/io/fabric8/openshift/client/DefaultOpenShiftClient.java:5
```

We just need to remove it from methods as described in this SonarRule[1]

[0] https://sonarcloud.io/project/issues?id=fabric8io_kubernetes-client&open=AXCBODe6SffsfmStSMSG&resolved=false&types=CODE_SMELL
[1] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS1130&rule_key=java%3AS1130

### PR DESCRIPTION
**Pull request by arghya88**
Fixes #2579

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by rohanKanojia** [comment]
Thanks for your PR :+1: There is one minor code smell related to an unused import[0]. Could you please address it whenever you revisit this? I think we can proceed with merge after this :)

[0] https://sonarcloud.io/project/issues?id=fabric8io_kubernetes-client&pullRequest=2582&resolved=false&types=CODE_SMELL&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by arghya88** [comment]
> Thanks for your PR 👍 There is one minor code smell related to an unused import[0]. Could you please address it whenever you revisit this? I think we can proceed with merge after this :)
> 
> [0] https://sonarcloud.io/project/issues?id=fabric8io_kubernetes-client&pullRequest=2582&resolved=false&types=CODE_SMELL&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

@rohanKanojia Done

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
[merge]

**Comment by arghya88** [comment]
@rohanKanojia Can you look into the build failure?

**Comment by manusa** [comment]
[merge]

**Pull request merged**
