### PR TITLE
Add resize terminal Support 

### LINKED ISSUE #1374: Add support for resizeChannel in ExecWebSocketListener
After walk through the `ExecWebSocketListener` I found that currently `resizeChannel` is not supported. 
Is there any plan to support it? Or any other work around here to resize tty while bash execution?

Thx.

### PR DESCRIPTION
**Pull request by candyleer**
I add a interface in `ExecWatch` .
I make it simple to support Resize ,please review whether it is proper,
 I will add `CHANGE LOG` and UnitTest after you review.

Fixes #1374

related kubenetes code: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/remotecommand/websocket.go

### CODE REVIEW

**Comment by candyleer** [comment]
I tested in my project and it works well

**Comment by rohanKanojia** [comment]
ok to test

**Comment by candyleer** [comment]
changelog has been added

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
