### PR TITLE
Allow to pick the CustomResourceDefinitionVersion with the highest priority (#2599)

### LINKED ISSUE #2599: Should be able to sort CustomResourceDefinitionVersion(s) according to their priority
When listing custom resources one has by default to display them in the version with the highest priority. One thus has to be able to sort available versions (CustomResourceDefinitionVersion) by their priority.

The kubernetes docs state the following at https://v1-17.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/:
> Version priority
>
>    Regardless of the order in which versions are defined in a CustomResourceDefinition, the version with the highest priority is used by kubectl as the default version to access objects. The priority is determined by parsing the name field to determine the version number, the stability (GA, Beta, or Alpha), and the sequence within that stability level.
>
>    The algorithm used for sorting the versions is designed to sort versions in the same way that the Kubernetes project sorts Kubernetes versions. Versions start with a v followed by a number, an optional beta or alpha designation, and optional additional numeric versioning information. Broadly, a version string might look like v2 or v2beta1. Versions are sorted using the following algorithm:
>
>* Entries that follow Kubernetes version patterns are sorted before those that do not.
>* For entries that follow Kubernetes version patterns, the numeric portions of the version string is sorted largest to smallest.
>* If the strings beta or alpha follow the first numeric portion, they sorted in that order, after the equivalent string without the beta or alpha suffix (which is presumed to be the GA version).
>* If another number follows the beta, or alpha, those numbers are also sorted from largest to smallest.
>* Strings that don’t fit the above format are sorted alphabetically and the numeric portions are not treated specially. Notice that in the example below, foo1 is sorted above foo10. This is different from the sorting of the numeric portion of entries that do follow the Kubernetes version patterns.

### PR DESCRIPTION
**Pull request by adietish**
fixes #2599 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by adietish** [comment]
I don't agree with sonar complaining about 2 assertions in my tests (the 2 code smells reported above): it wants me to use #contains instead of #equals which afaics don't have the same meaning.

**Comment by rohanKanojia** [comment]
You can simply ignore Sonar warnings if they don't make sense in your opinion :-)

**Comment by rohanKanojia** [comment]
In my opinion, it would be nice if we have some method like this:
```java
public static String highestPriorityVersion(CustomResourceDefinition crd);
public static String highestPriorityVersion(List<CustomResourceDefinitionVersion> versions);

```

**Comment by adietish** [comment]
> In my opinion, it would be nice if we have some method like this:
> 
> ```java
> public static String highestPriorityVersion(CustomResourceDefinition crd);
> public static String highestPriorityVersion(List<CustomResourceDefinitionVersion> versions);
> ```

I had typed parameters and return values using CustomResourceDefinitionVersion in my first take on this. I got off it bcs there are different classes for each version: `io.fabric8.kubernetes.api.model.apiextensions.v1` and `io.fabric8.kubernetes.api.model.apiextensions.v1beta1`. Using these classes would force me to provide overloads for each of them. Using simple Strings thus looks better to me.

**Comment by adietish** [comment]
I'll update my PR to also include a change in `CustomResourceDefinitionContext#fromCrd` which picks the version indicated in `CustomResourceDefinitionSpec#getVersion` where it should pick the version with the highest priority within `CustomResourceDefinitionSpec#getVersions`

**Comment by adietish** [comment]
I just discovered the changes to `CustomResourceDefinitionContext` made in 9662c38. I rather doubtful that the following would work correctly in `fromCustomResourceType(Class<? extends HasMetadata>)`:
```
String version = ApiVersionUtil.apiVersion(instance, "v1");
```
What happens if there's no "v1" but a "v1alpha1" and "v1beta1"?

**Comment by rohanKanojia** [comment]
Not sure if I understand...Where is this being used? Are you talking about this place?

https://github.com/fabric8io/kubernetes-client/blob/5bb774dc16c17d09b1fc1d446d6b254d729306d9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationContext.java#L88

Are you referring to `CustomResourceDefinitionContext` using `v1beta1` CustomResourceDefinition in `fromCrd` method?

**Comment by adietish** [comment]
> Not sure if I understand completely...Where is this being used? Are you talking about this place?
> 
> https://github.com/fabric8io/kubernetes-client/blob/5bb774dc16c17d09b1fc1d446d6b254d729306d9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationContext.java#L88
> 
> Are you referring to `CustomResourceDefinitionContext` using `v1beta1` CustomResourceDefinition in `fromCrd` method?

Sorry, my bad, was mislead by sub optimal UI in IntelliJ. The correct commit is 258ffb8. What I was referring to was :
https://github.com/fabric8io/kubernetes-client/commit/258ffb8#diff-0a2faee0e48ea089c119f1ce3b464f87493d36fddba3275eb21b96231988ea47R66
`CustomResourceDefinitionContext`
```
  public static CustomResourceDefinitionContext fromCustomResourceType(Class<? extends HasMetadata> customResource) {
    HasMetadata instance;
    try {
      instance = customResource.newInstance();

      String kind = Utils.isNullOrEmpty(instance.getKind()) ? customResource.getSimpleName() : instance.getKind();
      String name = kind.toLowerCase();
      String plural = Pluralize.toPlural(name);
      String group = ApiVersionUtil.apiGroup(instance, null);
      String version = ApiVersionUtil.apiVersion(instance, "v1");   <---------------------------------------------------
      String scope = instance instanceof Namespaced ? "Namespaced" : "Cluster";

      return new CustomResourceDefinitionContext.Builder()
        .withGroup(group)
        .withVersion(version)
        .withScope(scope)
        .withName(name)
        .withPlural(plural)
        .withKind(kind)
        .build();
    } catch (InstantiationException | IllegalAccessException e) {
      throw KubernetesClientException.launderThrowable(e);
    }
  }
``` 
I'm doubtful that assuming "v1" as version would be the right choice when judging from the spec. How would kube behave if there's no such version exist? Shouldn't we request the version in the custom resource instead?

**Comment by rohanKanojia** [comment]
oh, I think this is related to the new CustomResource DSL improvements we recently introduced. We now have a new method in DSL with which you can use any CustomResource with the client like this:
```java
MixedOperation<Foo, KubernetesResourceList<Foo>, Resource<Foo>> fooClient = k8sClient.customResource(Foo.class);
```
Here client just tries to build an opinionated `CustomResourceDefinitionContext` from the provided type. At this point, we don't have access to CustomResource; I'm not sure we can extract the version from CustomResource.

If the user wants to override this behavior, he can simply use DSL method with explicit `CustomResourceDefinitionContext`:
```java
CustomResourceDefinitionContext fooContext = new CustomResourceDefinitionContext.Builder()
      .withName("foo.example.com")
      .withGroup("example.com")
      .withVersion("v1alpha1")
      .withPlural("foos")
      .withScope("Namespaced")
      .build();
MixedOperation<Foo, KubernetesResourceList<Foo>, Resource<Foo>> fooClient = k8sClient.customResource(fooContext, Foo.class, FooList.class);
```

**Comment by adietish** [comment]
ok, my bad, misread the code, oversaw that the instance is created within the method from a type. "v1" is the default that it falls back to. I still believe that it's nothing more than a possible value, there's no guarantee or heightened plausibility for it. Nevertheless, I can't suggest any better solution for now.

**Comment by manusa** [comment]
Hi @adietish, tests are not being run in the CI env. Would you mind switching to JUnit5?
(`org.junit.jupiter.api.Test` instead of `org.junit.Test`)

We'll probably release a 5.0.0-alpha-3 version soon and it would be nice to have this in.

**Comment by adietish** [comment]
@manusa changed the import, rebased and pushed again.

**Comment by adietish** [comment]
@manusa weird, looks as if test now dont run. K8S and OpenShift checks stay yellow, wont turn green as they did before. Any idea?

**Comment by rohanKanojia** [comment]
I've restarted the workflow for now. I hope it'll pass

**Comment by rohanKanojia** [comment]
Could you please try pushing again? Strange, even after restarting it seems stuck

**Review by manusa — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
[merge]

**Comment by manusa** [comment]
[merge]

**Comment by manusa** [comment]
[merge]

**Pull request merged**
