### PR TITLE
Remove lexicographic resource version check

### PR DESCRIPTION
**Pull request by xguerin**
Also makes the handling of resourceVersion in WatchHTTPManager identical to that of WatchConnectionManager.

### CODE REVIEW

**Comment by xguerin** [comment]
Sure.

**Comment by xguerin** [comment]
@oscerd It does not look like the two failures are related to my change. Could you maybe restart the runs?

**Comment by rohanKanojia** [comment]
ok to test

**Comment by oscerd** [comment]
[merge]

**Pull request merged**
