### PR TITLE
refactor: remove Bean Validation integration

### PR DESCRIPTION
**Pull request by gastaldi**
This PR removes the Bean Validation integration (it doesn't seem to be used and it's causing trouble in Quarkus mainly)

@geoand @iocanel  can you test Quarkus with this PR and let me know how it behaves?

### CODE REVIEW

**Comment by geoand** [comment]
I tested this and it solved the Quarkus issues.

**Comment by rohanKanojia** [comment]
retest this please

**Comment by gastaldi** [comment]
Retest this please

**Comment by iocanel** [comment]
@gastaldi @geoand: Do we still have issues with quarkus after removing the @Valid annotation?

**Comment by iocanel** [comment]
@gastaldi: I am hitting issues with tests and I am not sure if I have the time to fix them.
If we are in a rush lets merge it as-is and we fix it later.

@rohanKanojia ^

**Comment by gastaldi** [comment]
[merge]

**Pull request merged**
