### PR TITLE
fix #4910 / #4923 addressing inconsistent behavior with exec streams

### LINKED ISSUE #4910: Issues with upload / failures with PodIT
With kubernetes 1.26 we are still seeing errors with pod upload:

```
Error:  Failures: 
Error:    PodIT.uploadBinaryFile:318 array lengths differ, expected: <16385> but was: <8192>
Error:    PodIT.uploadFile:298 expected: <I'm uploaded> but was: <>
```

https://github.com/fabric8io/kubernetes-client/actions/runs/4252695615/jobs/7396899761#step:6:579

With additional trace logging failed test runs showed the same data being sent to the server either way - as measured down at the level at which okhttp writes to the ssl socket.

There doesn't seem to be a good explanation for this other than we are more prone to seeing it on the containerd minikube runtime.  

The issue does seem to match one reported upstream https://github.com/kubernetes/kubernetes/issues/112834

We may want to add a formal warning about this behavior so that users are aware of potential data loss.

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Only 1 real issue was fully tracked down with #4910 / #4923 - vertx closeHandler is immediate.  That needs changed to the endHandler, which is notified in order.  Reviewing the vertx logic does also highlight that we'll have a problem if the server ever does send a ping - but that should not currently be the case.  The only "ping" sent currently is the 0 byte message.

For the common failures some additional debugging has been added to the failure message to narrow in on where the problem lies.

I had thought there was a concurrency issue with PodOperationsImpl.readTo, but that shouldn't be the case - the stream was still being closed in the calling method's try.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by shawkins** [comment]
https://github.com/fabric8io/kubernetes-client/actions/runs/4376515845/jobs/7659072908#step:6:450 confirms a fresh instance where some of the stdIn upload is dropped.  Options here include:
- adding a time delay between when the last data is sent and close
- attempt to check inline with the operation or afterwards.  File upload and directory upload have divergent logic that makes this difficult.  We may want to consolidate to just tar and a two step process - send the tar.gz, then in a separate exec check the length or checksum, then extract.

https://github.com/fabric8io/kubernetes-client/actions/runs/4268450566/jobs/7430955144#step:5:448 since there is no upload could be an issue with stdOut download - but I could never quite confirm that locally.  Initially it seemed like an issue with the stream close, but that turned out to not be the case.  I'd like to get another reproduction of that locally or via the github runs before drawing more conclusions about how to proceed.

**Comment by shawkins** [comment]
@manusa the first commit addresses the vertx close problem and some misc. cleanups.  The second commit is a speculative change help address the upload problem - basically throwing a few more messages at the server and a little wait to help ensure that what was already sent is processed.  This was done because I couldn't think of a good way an inline, or a post check that wouldn't require even more code.

**Comment by manusa** [comment]
So from the final code changes I see we're addressing 3 things here:
- Vert.x ping-pong handling: request more frames in case a pong is received (added a handler instead of disabling client-sent pings)
- Vert.x replacing `closeHandler` with `endHandler` which waits for the previous frames to be processed as opposed to closing the stream immediately
- Pod (Download) Operations: moved the exitCode blocking retrieval to the try-with-resources block. OutputStream is clearly closed after the server process has completed.

There still remains a few issues to solve:
- Delaying the close operation server-side for tar extract operation (might complete before the buffers are flushed) -Upload-
- Upload/Download checksums

_please feel free to edit this comment to make it more accurate_

**Comment by manusa** [comment]
I also think that we might want to add a little complexity to the upload operation (maybe also consolidate into a single implementation regardless of file or directory -like you proposed-). Perform 2 commands, one for the upload, one for the checksum. The upload command is only completed (local close processing is delayed) after the second command is successful. The checksum command is executed after the upload completes (websocket remains open) and is retried `n` times until success. I understand that this should cover the issue, but maybe I'm misinterpreting something.

**Review by manusa — APPROVED** [review]

**Pull request merged**
