### PR TITLE
Doc: Added a document for common operations using Fabric8 Kubernetes Client

### PR DESCRIPTION
**Pull request by rohanKanojia**
There are still a lot of things to add. But I think we can start with this much.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@oscerd : I discussed with @manusa about posting a blog on Red Hat developer about it. WDYT?

**Comment by manusa** [comment]
In order to be able to link specific parts of the document (point to answers in question issues) maybe it's better to use headings for each described operation instead of bullet points. WDYT?

BTW, this is awesome, great job!

**Comment by oscerd** [comment]
> @oscerd : I discussed with @manusa about posting a blog on Red Hat developer about it. WDYT?

Nice idea.

**Comment by manusa** [comment]
[merge]

**Comment by rohanKanojia** [comment]
Blog linking this CHEAT SHEET on Red Hat Developers: https://developers.redhat.com/blog/2020/05/20/getting-started-with-the-fabric8-kubernetes-java-client/

**Pull request merged**
