### PR TITLE
Improve selectors support in `OperationContext`

### PR DESCRIPTION
**Pull request by metacosm**
## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
Hi @shawkins, since you had some comments on previous iterations, could you please provide a LGTM if the current change-set is OK?

**Review by shawkins — APPROVED** [review]
> Hi @shawkins, since you had some comments on previous iterations, could you please provide a LGTM if the current change-set is OK?
LGTM  One thing that might be worth considering eventually is removing the direct references to labels, etc. off of the context, and instead hold a reference to FilterNestedImpl and encapsulate the getLabelQueryParam method there.  The only direct usage of the context is in the SharedInformerFactory - which can be removed in 6.

**Comment by manusa** [comment]
> LGTM One thing that might be worth considering eventually is removing the direct references to labels, etc. off of the context, and instead hold a reference to FilterNestedImpl and encapsulate the getLabelQueryParam method there. The only direct usage of the context is in the SharedInformerFactory - which can be removed in 6.

I merged to quickly.

Should we open a new issue for this?

**Comment by shawkins** [comment]
> Should we open a new issue for this?

Yes, there should probably be an umbrella issue for all removals of deprecated functionality, and in this case a change that is made easier following that.

**Pull request merged**
