### PR TITLE
fix #3179: creating a common base for the default kube and os clients

### LINKED ISSUE #3179: Functional differences between DefaultOpenShift and DefaultKubernetes clients
What are the expected functional differences between these clients?

We're seeing that at least custom resource handling differs because the defaultkubernetes client specifies a default delete propagation of background, while the openshift client does not so it default to orphan.

cc @rohanKanojia @manusa

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Creating a common base for the default kube and os clients.  This seems to require a generic form of the DefaultKubernetesClient, which I've named here BaseKubernetesClient.  Any of the problematic methods dealing with NamespacedXClient are left for the Default classes to implement.  Otherwise everything else can be shared from the base.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by manusa** [comment]
What bug are we fixing with this?

**Comment by rohanKanojia** [comment]
I think it's https://github.com/fabric8io/kubernetes-client/issues/3179 maybe

**Comment by manusa** [comment]
> I think it's #3179 maybe

Let me elaborate

That's not a bug, the issue is marked as a bug-fix on top of a chore/refactor.
image

I want to know if this PR is actually fixing something that wasn't working OK besides the refactor of the default clients.

**Comment by shawkins** [comment]
> That's not a bug, the issue is marked as a bug-fix on top of a chore/refactor.

From our projects perspective #3179 is a bug - prior to using operator sdk 1.8.2 custom resource deletes were cascading.  After the upgrade they weren't because of the difference in the implementation in the openshift client, which we were forced to use instead.

If it was intentional, or at least now expected, to have the openshift client default to orphaned deletes, then this should be noted as a breaking change as well.

**Review by metacosm — APPROVED** [review]

**Pull request merged**
