### PR TITLE
Add Github Action Workflow for Java 11 build

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by manusa** [comment]
Relates to https://github.com/fabric8io/kubernetes-client/issues/1714

**Comment by manusa** [comment]
Since we already a have a [build](https://github.com/fabric8io/kubernetes-client/blob/e695f8a6f56d3d00341c53af65d8edb0086e7c2b/.github/workflows/java8build.yml) workflow, maybe change it so that it declares a Java version [matrix](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix):
- java8build.yml > `java-build.yml`
- Change title
- Change setup Java step name

```yaml
      matrix:
        java-version: [8,11] # Supported LTS versions
```

**Review by jorsol — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by rohanKanojia** [comment]
[merge]

**Comment by manusa** [comment]
image
We need to change project settings after merge

**Pull request merged**
