### PR TITLE
Fix parsing openshift template throwing error

### PR DESCRIPTION
**Pull request by piyush1594**
#1070

### CODE REVIEW

**Comment by piyush1594** [comment]
ok to test

**Comment by oscerd** [comment]
ok to test

**Comment by piyush1594** [comment]
Just wondering, is not 3.1.11 will break for everyone who is using JSON file?

**Comment by rohanKanojia** [comment]
Yeah, we should release as soon as we can.

**Comment by oscerd** [comment]
[merge]

**Comment by oscerd** [comment]
We can start a new release once this has been merged.

**Comment by piyush1594** [comment]
Yeah, just please check if this is the case, it looks to me that it will break, not sure.

**Pull request merged**
