### PR TITLE
fixes(#1089): Appends query params at the end of the URL.

### PR DESCRIPTION
**Pull request by lordofthejars**
This PR appends query params at the end of the URL so in case of master URL has parameters they are appended correctly at the end.

### CODE REVIEW

**Comment by piyush1594** [comment]
ok to test

**Comment by piyush1594** [comment]
@lordofthejars You need to squash the commits. Also, you need to make an an entry to changelog.md

**Comment by lordofthejars** [comment]
They can be squashed when PR merging.

@bartoszmajsak could we add an ike plugin for checking changelog?

**Comment by lordofthejars** [comment]
@piyush1594 Before sending changelog, build was green in OS3.7 and red in OS3.6, now it is green in 3.6 and red in 3.7, (flaky build?)

**Comment by bartoszmajsak** [comment]
> @bartoszmajsak could we add an ike plugin for checking changelog?

this would mean new plugin, but sure we can hack it together

>  Although the ideal scenario would be that changelog was created automatically.

yeah. using properly prefixed commits landing to master that should be achievable

**Comment by hrishin** [comment]
@lordofthejars 

Do we have to address following one case for handling URL?

```java
  // could name if better. 
  public void shouldHandleMultiParamsURI() {

    // Given
    String masterUrl = "https://oso-master-url:8888/kubernetes?param1=value";

    // When

    final String fullUrl = URLUtils.join(masterUrl, "port?port=port");

    // Then
    assertThat(fullUrl, is("https://oso-master-url:8888/kubernetes/port?param1=value&port=port"));
  }
```

Unfortunately, there are few [places](https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/BuildOperationsImpl.java#L166) where URL passed in different way.

**Comment by lordofthejars** [comment]
@hrishin humm true, not easy at all all the possible use cases, but  now PR is merged :( So new PR then.

**Pull request merged**
