### PR TITLE
Add Kubernetes-model to kubernetes-client

### PR DESCRIPTION
**Pull request by rohanKanojia**
Merge kubernetes-model module into kubernetes-client, rather than having as
a separate repo.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@oscerd : Do you have any idea why test job is failing? It was passing on my local machine but here i'm getting:` [ERROR] GC overhead limit exceeded -> [Help 1]`

**Comment by oscerd** [comment]
Maybe you can try to give a look at https://github.com/fabric8io/kubernetes-model/blob/master/Jenkinsfile#L20

**Comment by rhuss** [comment]
@rohanKanojia what is the motivation to merge it into the client ? Actually, I have a use case with https://github.com/fabric8io/fabric8-kit to use the model without the client. But I guess I can still do this as this becomes a dedicated maven submodule in this repo, right ?

**Comment by iocanel** [comment]
@rhuss: The idea is to be able to release faster. Currently, we have to release model->client->fmp and so on.

**Comment by rhuss** [comment]
@iocanel sounds legit. as always :)

**Comment by iocanel** [comment]
[merge]

**Comment by iocanel** [comment]
Its an issue with Jenkins. Build containers need better jvm arguments. Can we ping woever is responsible for configuring it?

**Comment by rohanKanojia** [comment]
@oscerd @nicolaferraro @rhuss : Do you have any idea who has ownership of ci.fabric8.io(someone in Syndesis)? I mean who we can ping to somehow get this error fixed in merge job?

**Comment by oscerd** [comment]
It seems to be a problem of space on the CI server, maybe @zregvart may have a look at it.

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
OK, seems that I just needed to whitelist myself to re-trigger the build.

I've increased the heap size to 2GB in the [job configuration](https://ci.fabric8.io/job/kubernetes-client-pullreq/configure) as it seems that `jsonschema2pojo-maven-plugin:generate` uses quite a bit of memory. I think it should be OK now. I've made the same change on the merge and the release builds (now it's `-Xmx2g`).

**Comment by oscerd** [comment]
[merge]

**Comment by matzew** [comment]
@rohanKanojia @rhuss  I see that a `v4.0.5` client has been released, but not yet this model - on maven central the last one is from August (3.0.x) - am I missing something here ?

**Pull request merged**
