### PR TITLE
Added CRUD Test and Regression Test for SecurityContextConstraints

### PR DESCRIPTION
**Pull request by piyush1594**
Added CRUD Test and Regression Test for SecurityContextConstraints
After adding tests, they were failing so fixed the SCC.
It was not working for get, update and list operations.
#996

### CODE REVIEW

**Comment by piyush1594** [comment]
ok to test

**Comment by oscerd** [comment]
Ok to test

**Comment by oscerd** [comment]
[emerge]

**Comment by oscerd** [comment]
[merge]

**Pull request merged**
