### PR TITLE
Add stale bot.

### LINKED ISSUE #1290: Add a stale bot.
Adding a stale bot would close the issues which were created long ago and might not be relevant now. We can always triage the issues which the bot closes up and re-open them if they are still valid. This might be a good way for some cleansing.

https://github.com/probot/stale

### PR DESCRIPTION
**Pull request by dev-gaur**
Fixes #1290

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by oscerd** [comment]
We just need to rebase the Changelog here

**Comment by oscerd** [comment]
You should be used to already with f-m-p :-)

**Comment by rohanKanojia** [comment]
merging this one

**Comment by rohanKanojia** [comment]
:crossed_fingers:

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
