### PR TITLE
Make the Java generator Maven Plugin able to directly download resources

### LINKED ISSUE #4622: [java-generator] make the Maven plugin(and CLI?) able to fetch CRDs from URLs
### Is your enhancement related to a problem? Please describe

Currently, when we need to download a CRD and generate the corresponding Java code we need to leverage some external Maven plugin, such as:
https://github.com/bf2fc6cc711aee1a0c2a/e2e-test-suite/pull/417/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R284-R338

This is tedious, verbose and error-prone; instead, the logic to actually fetch the resources might be simple enough for the most common use cases.

### Describe the solution you'd like

The Maven plugin and the CLI should be able to fetch CRDs from URLs (possibly with a built-in caching as well).

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by andreaTP**
## Description
Fix #4622

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by andreaTP** [comment]
This is the resulting simplification from this change:
https://github.com/bf2fc6cc711aee1a0c2a/e2e-test-suite/pull/434/files

**Comment by rohanKanojia** [comment]
@andreaTP : Do you think the sonar report for closing ReadableByteChannel should be addressed?

**Review by rohanKanojia — APPROVED** [review]

**Comment by andreaTP** [comment]
@rohanKanojia sure! Done!

**Review by sunix — APPROVED** [review]

**Comment by manusa** [comment]
I'll create a follow-up PR to generalize the remote URL source so that it can be reused from the CLI tool, the Maven plugin, direct API usage, or whatever we build next.

**Review by manusa — APPROVED** [review]

**Pull request merged**
