### PR TITLE
WatchConnectionManager.onFailure: Handle null response

### PR DESCRIPTION
**Pull request by rohansingh**
`onFailure` is sometimes called with a null `response`. When this happens,
we would throw a `NullPointException` that would mask the underlying error,
prevent `onClose` from being called, and therefore prevent reconnection.

### CODE REVIEW

**Comment by rohansingh** [comment]
@rouzwawi FYI, should fix what we're seeing.

**Comment by jimmidyson** [comment]
LGTM

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
Thanks @rohansingh!

**Comment by rohansingh** [comment]
Sure thing, thank you!

**Comment by rouzwawi** [comment]
@jimmidyson would it be possible to get a new release of kubernetes-client soon?

**Comment by jimmidyson** [comment]
@jrawlings @iocanel Could you kick off a release please? I'm on holiday!

**Comment by rawlingsj** [comment]
@jimmidyson @rouzwawi sure thing.  I'll comment when its finished.

**Comment by rawlingsj** [comment]
Somethings not right with the kubernetes-client release.  I've just had a notification saying that 1.3.67 was released but I can see in maven central that was already released in January.  I think there's something wrong with the process now that we automatically add a [merge] comment.  

It also looks like some license checks failed yet the PR was still merged https://github.com/fabric8io/kubernetes-client/pull/300

Checking and I've found that the previous PR for 1.3.67 pom version update and next development versions was closed and not merged https://github.com/fabric8io/kubernetes-client/pull/293

I'll kick off another release now which should be ok but we need to look at it next week.

**Comment by rawlingsj** [comment]
1.3.68 release available http://repo1.maven.org/maven2/io/fabric8/kubernetes-client/1.3.68/

**Comment by rouzwawi** [comment]
Thanks!

**Pull request merged**
