### PR TITLE
cherry pick to sync

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by davsclaus** [comment]
ok to test

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
This is due to my force push & jenkins workspaces being a bit messed up.

retest this please

**Comment by jimmidyson** [comment]
retest this please

**Comment by davsclaus** [comment]
I will merge the lic fix to master if this works

**Comment by jimmidyson** [comment]
Previous commit worked too - that last commit is redundant.

**Comment by davsclaus** [comment]
so there is no auto merge to git? so you need to click the "Merge pull request" ?

**Comment by jimmidyson** [comment]
Yes we like to review what we do here :)

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
