### PR TITLE
ci: jdk 16

### PR DESCRIPTION
**Pull request by sullis**
## Description

add JDK 16 to build matrix

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
I would go with jdk 16, 15 doesn't really make sense now

**Review by oscerd — APPROVED** [review]

**Comment by rohanKanojia** [comment]
Hi, I think the build is not passing with this new version of JDK16:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Fabric8 :: Kubernetes :: Project 5.0-SNAPSHOT:
[INFO] 
[INFO] Fabric8 :: Kubernetes :: Project ................... SUCCESS [ 18.147 s]
[INFO] Fabric8 :: Kubernetes Model Parent ................. SUCCESS [  3.539 s]
[INFO] Fabric8 :: Kubernetes Model :: Common .............. FAILURE [  3.255 s]
[INFO] Fabric8 :: Kubernetes :: Model Annotator ........... SKIPPED
[INFO] Fabric8 :: Kubernetes Model Schema2Pojo Customizer . SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Core ................ SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: RBAC ................ SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Admission Registration, Authentication and Authorization SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Apps ................ SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Autoscaling ......... SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: API Extensions ...... SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Batch ............... SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Certificates ........ SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Coordination ........ SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Discovery ........... SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Events .............. SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Extensions .......... SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Networking .......... SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Metrics ............. SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Policy .............. SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Scheduling .......... SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Settings ............ SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Storage Class ....... SKIPPED
[INFO] Fabric8 :: OpenShift Model ......................... SKIPPED
[INFO] Fabric8 :: Kubernetes Model ........................ SKIPPED
[INFO] Fabric8 :: Kubernetes Model :: Node ................ SKIPPED
[INFO] Fabric8 :: OpenShift Operator Model ................ SKIPPED
[INFO] Fabric8 :: OpenShift OperatorHub Model ............. SKIPPED
[INFO] Fabric8 :: OpenShift Monitoring Model .............. SKIPPED
[INFO] Fabric8 :: OpenShift Console Model ................. SKIPPED
[INFO] Fabric8 :: Kubernetes :: Java Client ............... SKIPPED
[INFO] Fabric8 :: Kubernetes :: Server Mock ............... SKIPPED
[INFO] Fabric8 :: Openshift :: Java Client ................ SKIPPED
[INFO] Fabric8 :: Kubernetes :: Extensions ................ SKIPPED
[INFO] Fabric8 :: Knative :: Extension .................... SKIPPED
[INFO] Fabric8 :: Knative :: Model ........................ SKIPPED
[INFO] Fabric8 :: Knative :: Client ....................... SKIPPED
[INFO] Fabric8 :: Knative :: Server Mock .................. SKIPPED
[INFO] Fabric8 :: Knative :: Examples ..................... SKIPPED
[INFO] Fabric8 :: Knative :: Tests ........................ SKIPPED
[INFO] Fabric8 :: Tekton :: Extension ..................... SKIPPED
[INFO] Fabric8 :: Tekton :: Model v1alpha1 ................ SKIPPED
[INFO] Fabric8 :: Tekton :: Model v1beta1 ................. SKIPPED
[INFO] Fabric8 :: Tekton :: Model triggers ................ SKIPPED
[INFO] Fabric8 :: Tekton :: Client ........................ SKIPPED
[INFO] Fabric8 :: Tekton :: Server Mock ................... SKIPPED
[INFO] Fabric8 :: Tekton :: Examples ...................... SKIPPED
[INFO] Fabric8 :: Tekton :: Tests ......................... SKIPPED
[INFO] Fabric8 :: Service Catalog :: Extension ............ SKIPPED
[INFO] Fabric8 :: Service Catalog :: Model ................ SKIPPED
[INFO] Fabric8 :: Service Catalog :: Client ............... SKIPPED
[INFO] Fabric8 :: Service Catalog :: Server Mock .......... SKIPPED
[INFO] Fabric8 :: Service Catalog :: Examples ............. SKIPPED
[INFO] Fabric8 :: Service Catalog :: Tests ................ SKIPPED
[INFO] Fabric8 :: Volume Snapshot :: Extension ............ SKIPPED
[INFO] Fabric8 :: Volume Snapshot :: Model ................ SKIPPED
[INFO] Fabric8 :: Volume Snapshot :: Client ............... SKIPPED
[INFO] Fabric8 :: Volume Snapshot :: Server Mock .......... SKIPPED
[INFO] Fabric8 :: Volume Snapshot :: Examples ............. SKIPPED
[INFO] Fabric8 :: Volume Snapshot :: Tests ................ SKIPPED
[INFO] Fabric8 :: Chaos Mesh :: Extension ................. SKIPPED
[INFO] Fabric8 :: Chaos Mesh :: Model ..................... SKIPPED
[INFO] Fabric8 :: Chaos Mesh :: Client .................... SKIPPED
[INFO] Fabric8 :: Chaos Mesh :: Server Mock ............... SKIPPED
[INFO] Fabric8 :: Chaos Mesh :: Examples .................. SKIPPED
[INFO] Fabric8 :: Chaos Mesh :: Tests ..................... SKIPPED
[INFO] Fabric8 :: Openshift :: Server Mock ................ SKIPPED
[INFO] Fabric8 :: Kubernetes :: Client Examples ........... SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms ................. SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf ........ SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf :: Features SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf :: Tests SKIPPED
[INFO] Fabric8 :: Kubernetes :: Tests ..................... SKIPPED
[INFO] Fabric8 :: Kubernetes and Openshift :: UberJar ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  44.339 s
[INFO] Finished at: 2021-01-04T06:12:07Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kubernetes-model-common: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x2222cd2c) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x2222cd2c -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :kubernetes-model-common
Error: Process completed with exit code 1.
```

**Comment by manusa** [comment]
It would make a lot of sense to upgrade this into JDK 17 (LTS) now that it's finally available.

**Comment by manusa** [comment]
> It would make a lot of sense to upgrade this into JDK 17 (LTS) now that it's finally available.

I'm closing this one, let's open a new PR to bump into JDK 17.

**Pull request closed without merging**
