### PR TITLE
Fix #1816: Support for Binding in dsl

### LINKED ISSUE #1816: V1Binding API equivalent?
Using the kubernetes-java client (https://github.com/kubernetes-client/java/), I can implement my own scheduling logic to assign pods to nodes by doing something like this:

```java
    private void bindOne(final String namespace, final String podName, final String nodeName, final CoreV1Api v1Api) throws ApiException {
        final V1Binding body = new V1Binding();
        final V1ObjectReference target = new V1ObjectReference();
        final V1ObjectMeta meta = new V1ObjectMeta();
        target.setKind("Node");
        target.setApiVersion("v1");
        target.setName(nodeName);
        meta.setName(podName);
        body.setTarget(target);
        body.setMetadata(meta);
        v1Api.createNamespacedBinding(namespace, body, null, null, null);
    }
```
How can I do the same thing using the fabric8io client? I'd love to avoid using another client in my system only to support the above code snippet.

Thanks!

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #1816

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@lalithsuresh: I'm not very familiar with `Binding` usage.  When I was trying to add binding for a pod I kept getting this error:
```
Failure executing: POST at: https://192.168.99.100:8443/api/v1/namespaces/default/bindings. Message: Operation cannot be fulfilled on pods/binding "testpod": pod testpod is already assigned to node "minikube". Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=pods/binding, name=testpod, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on pods/binding "testpod": pod testpod is already assigned to node "minikube", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510)
```

Could you please pull this and try SNAPSHOT build on your machine?
1. Clone the repo
2. pull my branch: `git fetch origin pull/1819/head:pullRequest1819 && git checkout pullRequest1819`
3. build SNAPSHOT version `mvn clean install -DskipTests`
4. Try `4.7-SNAPSHOT` in your project and see if it helps.

**Comment by lalithsuresh** [comment]
The build fails with the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kubernetes-model: Compilation failure: Compilation failure:
[ERROR] /Users/lsuresh/code/kube-pr/kubernetes-model/kubernetes-model/target/generated-sources/annotations/io/fabric8/kubernetes/api/builder/VisitableMap.java:[37,27] name clash: forEach(java.util.function.Consumer<?>) in io.fabric8.kubernetes.api.builder.VisitableMap and forEach(java.util.function.Consumer<? super io.fabric8.kubernetes.api.builder.Visitable>) in java.lang.Iterable have the same erasure, yet neither overrides the other
[ERROR] /Users/lsuresh/code/kube-pr/kubernetes-model/kubernetes-model/target/generated-sources/annotations/io/fabric8/kubernetes/api/builder/VisitableMap.java:[37,5] method does not override or implement a method from a supertype
[ERROR] /Users/lsuresh/code/kube-pr/kubernetes-model/kubernetes-model/target/generated-sources/annotations/io/fabric8/kubernetes/api/builder/VisitableMap.java:[38,33] incompatible types: java.util.function.Consumer<capture#1 of ?> cannot be converted to java.util.function.Consumer<? super io.fabric8.kubernetes.api.builder.Visitable>
[ERROR] -> [Help 1]
```

I'm on OpenJDK 12. Do I need to switch to something else for this to build?

Either way, the error you got looks benign, it's because the default scheduler has already assigned the pod to a node. You can work around this by adding something like this to the podspec:
```
spec:
      schedulerName: fake-scheduler
```
If you then create the pod, it should stay in the "Pending" state until you try to perform the binding to a valid node.

**Comment by rohanKanojia** [comment]
nice, Thanks a lot for taking time to test this!

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
