### PR TITLE
Provide more options to for loading and using resources.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Can you summarise what these extra options are?

**Comment by iocanel** [comment]
For load() we now have additional methods for loading File, URL and String pointing to the path of the file.
For resource() we now have the ability to pass the string representation of the object.

No biggies, in practice we just hide serialization and exception handling which in some cases its really useful. (e.g. inside a pipeline).

**Comment by iocanel** [comment]
@jimmidyson: can u have a look and merge please?

**Comment by jimmidyson** [comment]
LGTM [merge]

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
