### PR TITLE
Update Tekton Triggers model to v0.12.0

### PR DESCRIPTION
**Pull request by Fabian-K**
## Description
This PR updates the tekton triggers model to 0.12.0 (https://github.com/tektoncd/triggers/releases/tag/v0.12.0).
The breaking aspect is the removal of the `name` field for templates.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by Fabian-K** [comment]
Sorry, need to put this on hold. I noticed some strange behavior related to the builder & serialization which I need to look into first

**Comment by rohanKanojia** [comment]
@Fabian-K : Hello, Is this blocked via https://github.com/fabric8io/kubernetes-client/issues/2916 ? Do you need some help in order to resolve this?

**Comment by Fabian-K** [comment]
Yes, you are right. I did not find time to investigate more. It would be great to get some help with #2916

**Comment by manusa** [comment]
Superseded by #3099

**Pull request closed without merging**
