### PR TITLE
Migrate to okhttp client

### PR DESCRIPTION
**Pull request by jimmidyson**
@iocanel Have a quick look for any problems if you can please.

### CODE REVIEW

**Comment by iocanel** [comment]
@jimmidyson: I also forgot to mention that you shouldn't be bitching about people naming their branches "misc" Mr. "devel".

Cheers!

**Comment by jimmidyson** [comment]
@iocanel Don't do as I do, do as I say :stuck_out_tongue_winking_eye:

**Comment by jimmidyson** [comment]
In my defence I never bitched about branch names, I bitched about PR names & commit comments. So I win.

**Comment by iocanel** [comment]
git log | grep -i misc

**Comment by jimmidyson** [comment]
Do we have a test for the karaf feature? Or an example? Just want to check I haven't broken it.

**Comment by iocanel** [comment]
No, we don't! Do you want me to hack one?

**Comment by jimmidyson** [comment]
Yeah!

**Comment by jimmidyson** [comment]
@iocanel One more dependency dropped.

**Comment by iocanel** [comment]
@jimmidyson: Woot woot! https://www.youtube.com/watch?v=sCNrK-n68CM

**Comment by jimmidyson** [comment]
@iocanel Any news on that karaf test? Shall I merge this & we can fix up after?

**Comment by iocanel** [comment]
Behind the test failure, lies a LinkageError.

The LinkageError is caused by the fact that we have okhttp embedded in both bundles. Classes from openshift-client extend classes from kubernetes-client and both use their private instance of okhttp. Should I say more?

**Comment by jimmidyson** [comment]
Yes you should - you should detail the solution ;) Wrap or create our own bundle of okhttp?

**Comment by iocanel** [comment]
I have a pull request almost ready, which goes to extraordinary lengths in order to solve the issue.

**Comment by iocanel** [comment]
The PR that solves issue is merged. I am closing this.

**Pull request closed without merging**
