### PR TITLE
Fix #1872: Support for kubernetes 1.17

### LINKED ISSUE #1872: Support for kubernetes 1.17
Is there any plan to support kuberentes 1.16?How to join in your development and get the latest version of kubernetes model?

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #1872 

+ Updated Kubernetes Model to Kubernetes 1.16
+ Added these new resources to Kubernetes Model
   - CreateOptions
   - GetOptions
   - UpdateOptions
   - PatchOptions
   - EndpointSlice
   - VolumeAttachment
   - CSIDriver
   - CSINode
   - Lease

### CODE REVIEW

**Comment by rohanKanojia** [comment]
retest this please

**Comment by sedooe** [comment]
I think there should be `UpdateOptions` also, see: https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#UpdateOptions

Noticed this because validation webhook failed to parse json on some update request.

**Comment by rohanKanojia** [comment]
@sedooe : I've added it in this update. Do you know any resource that I could have missed here?

**Comment by sedooe** [comment]
I'm not aware of any more resources but I know that this `options` objects came with 1.15, not with 1.16: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#other-notable-changes-8

**Comment by rohanKanojia** [comment]
[merge]

**Comment by infoankitp** [comment]
@rohanKanojia Wanted to confirm if the client library supporting Kubernetes 1.17 also supports the Kubernetes 1.16 ?

**Pull request merged**
