### PR TITLE
Handle NullPointerException in loadRelated

### LINKED ISSUE #4791: Unhandled NullPointerException in loadRelated
#### Background
Hi, I am working on the [Calico GlobalNetworkPolicy CRD](https://github.com/projectcalico/calico/blob/f1a1611acb98d9187f48bbbe2227301aa69f0499/manifests/canal.yaml#L1522-L2377) with Fabric8 `6.0.0`. After generating the Java classes from the CRD YAML with the [java-generator-maven-plugin](https://github.com/fabric8io/kubernetes-client/blob/master/doc/java-generation-from-CRD.md) and manually fixed the [namespaced issue](https://github.com/fabric8io/kubernetes-client/commit/d9376eb01f7fc8c2f813a6b42738aee03177e750), I always got `NullPointerException` when I try with
```java
public enum MyKubeTypeHandler {
    // these work
    POD(Pod.class, KubernetesClient::pods),
    DEPLOYMENT(Deployment.class, client -> client.apps().deployments()),
    ......
    // this DOES NOT work due to unhandled `NullPointerException`
    CALICO_GLOBAL_NETWORK_POLICY(GlobalNetworkPolicy.class, client -> client.resources(GlobalNetworkPolicy.class));
    ......
    public NonNamespaceOperation<
              HasMetadata,
              KubernetesResourceList<? extends HasMetadata>,
              ? extends Resource<HasMetadata>>
          withAllNamespaces(KubernetesClient client) {
        // This is where it failed
        return this.ops.apply(apiClient);
    }
}
```
The stack trace is as follow
```
java.lang.NullPointerException: null
	at io.fabric8.kubernetes.client.utils.KubernetesResourceUtil.loadRelated(KubernetesResourceUtil.java:415)
	at io.fabric8.kubernetes.client.utils.KubernetesResourceUtil.inferListType(KubernetesResourceUtil.java:406)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperationsImpl.<init>(HasMetadataOperationsImpl.java:50)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperationsImpl.<init>(HasMetadataOperationsImpl.java:38)
	at io.fabric8.kubernetes.client.BaseClient.newHasMetadataOperation(BaseClient.java:288)
	at io.fabric8.kubernetes.client.BaseClient.resources(BaseClient.java:279)
	at io.fabric8.kubernetes.client.Client.resources(Client.java:162)
	at io.fabric8.kubernetes.client.KubernetesClient.resources(KubernetesClient.java:140)
	at com.foo.bar.kube.MyKubeTypeHandler.lambda$static$6(MyKubeTypeHandler.java:61)
```

#### Java version
```bash
$ java -version
Picked up JAVA_TOOL_OPTIONS:  -Djavax.net.ssl.trustStore=/etc/pki/ca-trust/extracted/java/cacerts
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
```

#### Fabric8 source code
When digging into the source code of fabric8 this is where I found that threw the `NullPointerException`s
```java
    public static <T extends HasMetadata> Class<? extends KubernetesResourceList> inferListType(Class<T> type) {
        return loadRelated(type, "List", DefaultKubernetesResourceList.class);
    }
    ......
    private static Class<?> loadRelated(Class<?> type, String suffix, Class<?> defaultClass) {
        try {
            // Here the `getContextClassLoader()` may throw `null`
            return Thread.currentThread().getContextClassLoader().loadClass(type.getName() + suffix);
        } catch (ClassCastException | ClassNotFoundException var6) {
            try {
                return type.getClassLoader().loadClass(type.getName() + suffix);
            } catch (ClassCastException | ClassNotFoundException var5) {
                return defaultClass;
            }
        }
    }
```

#### Proposal
After checking the [java 11 docs](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html#getContextClassLoader()) for `getContextClassLoader` method, it could return `null`, which makes the subsequent method invocation, `loadClass()` from a null object.

I checked the latest code ([1a3b2b6](https://github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java#L415)) that this unhandled `NullPointerException` issue may still exists.

My suggestion is simply expect and handle the `NullPointerException` in the `catch` clause, as in #4792 

### Fabric8 Kubernetes Client version

6.0.0

### Steps to reproduce

1. Use `openjdk 11.0.17`
2. Follow the [docs](https://github.com/fabric8io/kubernetes-client/blob/master/doc/java-generation-from-CRD.md) to generate the collection of classes for `GlobalNetworkPolicy` from the [Calico GlobalNetworkPolicy CRD](https://github.com/projectcalico/calico/blob/f1a1611acb98d9187f48bbbe2227301aa69f0499/manifests/canal.yaml#L1522-L2377).
3. Run the code snippet above and check the logs

### Expected behavior

The `NullPointerException` should be expected and handled.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.24

### Environment

Linux

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sfc-gh-valiu**
## Description

Fix  #4791 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by andreaTP — APPROVED** [review]
Hi @sfc-gh-valiu , thanks a lot for the report and the proposed fix.

Your analysis seems consistent LGTM.

**Comment by rohanKanojia** [comment]
Is it possible to write a test case for this?

**Comment by shawkins** [comment]
The issue must be with due having no context when classloading an enum type, otherwise it would be rare or require the caller to explicitly set the context classloader to null.

We aren't handling the possibility of a null context classloader in KubernetesClientBuilder as well.  The other locations either check for null or use ServiceLoader, which will use ClassLoader.getSystemClassLoader if a null is passed in.  

Can you change KubernetesClientBuilder as well just for completeness?

**Comment by sfc-gh-valiu** [comment]
@shawkins Sure. Just want to confirm is [this part](https://cs.github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientBuilder.java?q=KubernetesClientBuilder#L55-L62) what you referred to?
@rohanKanojia Sure, but I realized this no existing unit test classes for `KubernetesResourceUtil` and there is only 1 vanilla test for [KubernetesClientBuilderTest](https://github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/kubernetes-client-api/src/test/java/io/fabric8/kubernetes/client/KubernetesClientBuilderTest.java#L26-L34). What I might do is to add one more test only for the `NullPointerException` handling, right?
BTW I might switch from my work account to my personal account (@jazzplato)to continue this PR after work.

**Comment by shawkins** [comment]
@sfc-gh-valiu yes that's the other place that does not handle a null context class loader.

**Comment by sfc-gh-valiu** [comment]
Close this PR and created #4847 to continue the work and discussion.

**Pull request closed without merging**
