### PR TITLE
fix: 4846 allowing for read / copy operations to detect missing files

### LINKED ISSUE #4846: pod read unable to distinguish between empty result and missing file
### Is your task related to a problem? Please describe

using pod read or copy will treat a missing file as an empty result.

### Describe the solution you'd like

An exception when missing.

It would be nice if we could just turn on terminateOnError on the underlying exec, but this does not work because the tar command will complain about stripping the leading / to stdErr.  The tar command either needs sanitized (which my quick attempt didn't seem to do) or both the readTar and the read commands need to include an explicit existence check that returns an error exit code:

test -e file && ... regular command ... || exit 1

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
## Description

Fix #4846 

Split the prospective changes into several prs, this on covering #4846

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by shawkins** [comment]
Here's a good run:

```
2023-02-07T23:53:06.8163682Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-07T23:53:06.8173226Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - send 21 bytes
2023-02-07T23:53:06.8174263Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - sendClose
2023-02-07T23:53:06.9167666Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-07T23:53:06.9168905Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onClosing queueSize 0
2023-02-07T23:53:06.9170098Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: completed with a null exit code - no status was received prior to onClose
2023-02-07T23:53:06.9171371Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: On Close with code:[1000], due to: []
2023-02-07T23:53:07.0180950Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-07T23:53:07.0182623Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-07T23:53:07.0183795Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 22 bytes
```
The trailing onMessage 22 bytes is reading the file contents back.

Here's a failing run:

```
2023-02-07T23:53:07.1188333Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-07T23:53:07.1189818Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-07T23:53:07.1191080Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - send 21 bytes
2023-02-07T23:53:07.1192109Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - sendClose
2023-02-07T23:53:07.2177796Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 35 bytes
2023-02-07T23:53:07.2179281Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - exec message received on channel errorChannel: {"metadata":{},"status":"Success"}
2023-02-07T23:53:07.2180791Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onClosing queueSize 0
2023-02-07T23:53:07.2182008Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: On Close with code:[1000], due to: []
2023-02-07T23:53:07.2183179Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-07T23:53:07.3012849Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-07T23:53:07.3014769Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 35 bytes
```

That trailing 35 bytes is the errorChannel Success / exitCode 0 message.   Our logic currently assumes that no more messages will be seen after that point, so it will initiate a close after that.  The only thing I can think here is that the channel 1 and channel 3 messages are potentially out of order.  I'll do another run that won't proactively call close from the client side when we get the errorChannel status and see if that fixes it.

**Comment by manusa** [comment]
This is from the failed execution after disabling the proactive close:
```
2023-02-08T02:30:28.6188611Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-08T02:30:28.6189779Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-08T02:30:28.6190688Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 22 bytes
2023-02-08T02:30:28.6191762Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - exec message received 21 bytes on channel stdOut
2023-02-08T02:30:28.6192600Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 35 bytes
2023-02-08T02:30:28.6193644Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - exec message received on channel errorChannel: {"metadata":{},"status":"Success"}
2023-02-08T02:30:28.6194541Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onClosing queueSize 0
2023-02-08T02:30:28.6195387Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - sendClose
2023-02-08T02:30:28.6196246Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: On Close with code:[1000], due to: []
2023-02-08T02:30:28.7363476Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl - Shutting down dispatcher okhttp3.Dispatcher@179a0d61
```

Messages and close events seem to be _logged_ in the correct order this time. However, it looks like the last message is never processed, probably because the close event is received before the message processing starts. Seems like a similar situation to what we force on #4796 where no more processing happens once the reflector is closed, but in this case with the websocket. Still haven't checked the related code though.

**Comment by shawkins** [comment]
> Messages and close events seem to be logged in the correct order this time.

@manusa unfortunately they are still not.  The failing sequence is:

```
2023-02-08T02:30:26.6094092Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-08T02:30:26.6095274Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-08T02:30:26.6096123Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - send 21 bytes
2023-02-08T02:30:26.6096910Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - sendClose
2023-02-08T02:30:26.6097794Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onClosing queueSize 0
2023-02-08T02:30:26.6098853Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: completed with a null exit code - no status was received prior to onClose
2023-02-08T02:30:26.6099967Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: On Close with code:[1000], due to: []
2023-02-08T02:30:26.7094042Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-08T02:30:26.7095216Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-08T02:30:26.7541684Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 35 bytes
2023-02-08T02:30:26.7542976Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - exec message received on channel errorChannel: {"metadata":{},"status":"Success"}
2023-02-08T02:30:26.7544016Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onClosing queueSize 0
2023-02-08T02:30:26.7544901Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - sendClose
2023-02-08T02:30:26.7545870Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: On Close with code:[1000], due to: []
```

That shows the expected upload 2023-02-08T02:30:26.6096123Z, but the expected 22 bytes on stdOut is never received.  The websocket is opened 2023-02-08T02:30:26.7095216Z, then 2023-02-08T02:30:26.7541684Z the errorChannel success is seen, then close 2023-02-08T02:30:26.7544016Z - which indicates that no more messages will be seen.  The data is simply not seen by our usage of okhttp.

On the upload - the semantics of sendClose is supposed to be that it clears the send queue prior to being sent.  We won't complete the exitCode for the upload until we see an errorChannel message (not expected) or until we're notified of remote close 2023-02-08T02:30:26.6096910Z.

I can only see 2 possibilities:
1. Something is wrong with the okhttp logic - the frame with the data to be sent or to be read is being dropped.  We can crank up the okhttp logging and/or do a couple of runs with another client.  In looking at the httpclient e2e tests it seems there are issues with the jdk and vertx runs of late, so I try jetty.  I'll make sure that at least jdk runs cleanly after getting this addressed.
2. It's a problem with the api server - a timing issue or something related for filesystem caching?

> probably because the close event is received before the message processing starts. 

The message delivery is effectively single threaded and the processing logic is inline - that is as soon as a buffer is delivered via onMessage it will be added to the ExecWebSocketListener buffers.  Similarly close is noted at the ExecWebSocketListener, but is not considered until the buffers are empty.

**Comment by shawkins** [comment]
> We can crank up the okhttp logging

That doesn't really do anything for websockets - the additional trace logging is only for regular http requests.

**Comment by manusa** [comment]
> It's a problem with the api server - a timing issue or something related for filesystem caching?

I really don't see why would this be happening now. Also the file contents is piped along with the creation command. It would be more likely to see a problem related to not finding the file, but who knows.
An additional diagnostic would be to perform a `cat` command of the affected file to discard it's sth related to the API server or the underlying FS.

**Comment by shawkins** [comment]
The next diagnostic confirms the issue is with the upload, not the download.  The ls after the upload shows 0 bytes and none of the retries work:

```
2023-02-08T14:01:55.5157207Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-08T14:01:55.5158073Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-08T14:01:55.5158979Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - send 21 bytes
2023-02-08T14:01:55.5159594Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - sendClose
2023-02-08T14:01:55.6153721Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onClosing queueSize 0
2023-02-08T14:01:55.6154751Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: completed with a null exit code - no status was received prior to onClose
2023-02-08T14:01:55.6155708Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: On Close with code:[1000], due to: []
2023-02-08T14:01:55.6156560Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-08T14:01:55.6157324Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-08T14:01:55.7161317Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 76 bytes
2023-02-08T14:01:55.7161959Z -rw-r--r--    1 root     root             0 Feb  8 14:01 /tmp/toBeUploaded
2023-02-08T14:01:55.7164056Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - exec message received 75 bytes on channel stdOut
2023-02-08T14:01:55.7164999Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 35 bytes
2023-02-08T14:01:55.7166036Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - exec message received on channel errorChannel: {"metadata":{},"status":"Success"}
2023-02-08T14:01:55.7167383Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - sendClose
2023-02-08T14:01:55.7168346Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onClosing queueSize 0
2023-02-08T14:01:55.7169486Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: On Close with code:[1000], due to: []
2023-02-08T14:01:55.7172322Z [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl - using first container busybox in pod pod-standard
2023-02-08T14:01:55.8159727Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-08T14:01:55.8160231Z Trying to read upload again
```

**Comment by manusa** [comment]
Would an OkHttp timeout be reflected in the logs?

**Comment by shawkins** [comment]
The check of the queueSize when closing confirms that the data has been sent.  Either okhttp is dropping it, or the api server is.  

The buffer that is passed in is created locally in ExecWebSocketListener.send - so it's not possible that the data / buffer is somehow changing, and it's copied again with the creation of the OkHttp ByteString.  The changes that are part of this pr related to copying the buffer are for the other send paths - which is really just port forwarding where the buffer is reused.   That could cause an issue with the jdk and jetty clients.

**Comment by shawkins** [comment]
Yes any timeout we see, especially at a debug level, would be logged.

**Comment by shawkins** [comment]
@manusa with okio logging, here's a failed upload:

```
2023-02-08T15:24:03.9278095Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - send 21 bytes
2023-02-08T15:24:03.9279073Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - sendClose
2023-02-08T15:24:03.9280373Z [OkHttp WebSocket https://192.168.49.2:8443/...] DEBUG okio.Okio - sink(sun.security.ssl.SSLSocketImpl$AppOutputStream@128f9c52) writing bytes 27
2023-02-08T15:24:03.9281422Z [OkHttp WebSocket https://192.168.49.2:8443/...] DEBUG okio.Okio - sink(sun.security.ssl.SSLSocketImpl$AppOutputStream@128f9c52) writing bytes 18
2023-02-08T15:24:03.9282686Z [OkHttp WebSocket https://192.168.49.2:8443/...] DEBUG okio.Okio - sink(sun.security.ssl.SSLSocketImpl$AppOutputStream@128f9c52) flushing
2023-02-08T15:24:04.0276562Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onClosing queueSize 0
2023-02-08T15:24:04.0278090Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: completed with a null exit code - no status was received prior to onClose
2023-02-08T15:24:04.0279718Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: On Close with code:[1000], due to: []
...
2023-02-08T15:24:04.1293646Z -rw-r--r--    1 root     root             0 Feb  8 15:24 /tmp/001_special_!@#\$^&(.mp4
```

The 27 byte message is the data + overhead.  The 18 byte message should be the close + overhead.  The websocket the closes as expected and confirms that the queue has been flushed.  However when looking at the file length, it's empty.

Here's a successful upload:

```
2023-02-08T15:24:05.3355352Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - send 21 bytes
2023-02-08T15:24:05.3356604Z [main] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - sendClose
2023-02-08T15:24:05.3357607Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 1 bytes
2023-02-08T15:24:05.3358661Z [OkHttp WebSocket https://192.168.49.2:8443/...] DEBUG okio.Okio - sink(sun.security.ssl.SSLSocketImpl$AppOutputStream@74fde204) writing bytes 27
2023-02-08T15:24:05.3365582Z [OkHttp WebSocket https://192.168.49.2:8443/...] DEBUG okio.Okio - sink(sun.security.ssl.SSLSocketImpl$AppOutputStream@74fde204) writing bytes 18
2023-02-08T15:24:05.3371945Z [OkHttp WebSocket https://192.168.49.2:8443/...] DEBUG okio.Okio - sink(sun.security.ssl.SSLSocketImpl$AppOutputStream@74fde204) flushing
2023-02-08T15:24:05.4331336Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onMessage 35 bytes
2023-02-08T15:24:05.4333038Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - exec message received on channel errorChannel: {"metadata":{},"status":"Success"}
2023-02-08T15:24:05.4334496Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl - onClosing queueSize 0
2023-02-08T15:24:05.4336040Z [OkHttp https://192.168.49.2:8443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener - Exec Web Socket: On Close with code:[1000], due to: []
...
2023-02-08T15:24:05.5333314Z -rw-r--r--    1 root     root            13 Feb  8 15:24 /tmp/002'special
```

From all the way down at the io / socket level what is being sent appears the same.

One difference in this run, which seems to have inconsistent behavior on the api server side (in particular by version), is whether we see an errorChannel success message before we see onClose on a process that remains open until a close is sent.

If there is are timing issue here, it looks like it rests on the api server side.

**Review by sunix — APPROVED** [review]

**Comment by manusa** [comment]
As discussed internally, Exec streams (the ones used to upload/download files) are always piped through WebSockets, there is no fallback to regular HTTP transport (as there is for Watchers).
This means that not using the additional base64 encoding shouldn't be a problem in this case, so it's safe to remove the base64 conversion.
As a follow-up task we might want to remove the [Base64](https://github.com/fabric8io/kubernetes-client/blob/94a38a58810e0237edf2401720e03f70b35b2759/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/internal/Base64.java) class we use internally to decode and encode base64-encoded `InputStreams` and `OutputStreams`.

**Review by manusa — APPROVED** [review]

**Pull request merged**
