### PR TITLE
Update model so that Step does not contain a Container but has the sa…

### LINKED ISSUE #1900: Cannot create a Task using the Tekton extension
I am trying to create a Task from this payload:

```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world1
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"

```

I always go rejected by the server and noticed that various attributes for the step are stored as additionalProperties and are lost when editing the resource.
I looked at the code and noticed that the Step model class is defined as containing a Container where it is an extension of Container (from the Go code).

### LINKED ISSUE #1984: There is unknown field "container" in Tekton
#### Issue description
I was trying to make Tekton `Task` with java fabric8.tekton apis, however I got some issues.

However I got an error message in runtime. 

image

#### Steps to reproduce the issue

I just compile with javac, and run the jar file. 

It is just sample test code, and there are already information about environments in link below. 

[issue in stackoverflow](https://stackoverflow.com/questions/60049533/there-is-unknown-field-container-in-tekton?noredirect=1#comment106205962_60049533)

#### What's the expected result?

- Make `Task` in tekton

#### What's the actual result?

- Got Error message as a screenshot provided.

### PR DESCRIPTION
**Pull request by jeffmaury**
…me attributes

Fixes #1900
Fixes #1984 

- Optimal solution would be to have Step inherits from Container but I'm not a generator expert

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by manusa** [comment]
License is missing for task.json file, please run `mvn -N license:format`

**Comment by rohanKanojia** [comment]
retest this please

**Comment by rohanKanojia** [comment]
@Fabian-K: Hi, Could you please take a look at this PR? It's related to #1984

**Comment by Fabian-K** [comment]
I don´t know much about the generator logic. The resulting tekton-schema.json looks good!

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
