### PR TITLE
fix #3587: adding inform support for limit/batch fetching

### LINKED ISSUE #3587: Add a construct in between a Watch and an Informer
The fabric8 built-in watch support is similar to a retrywatcher in the go client - until http gone it will maintain the watch automatically.  Because the watch is restarted at an exact resourceVersion, there are no duplicate add events.

The next option is to use an informer, but in some circumstances there may be a concern about the size of an informer cache.  Either we need to offer additional cache customization features - similar to #3472 - or introduce a further enhanced watch construct that goes beyond the retry to handle http gone.  Under the covers this would look like an informer that caches only the resource key and version, but the user would still use the Watcher interface.

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Related to #3587 #3616 - adds limit / batch fetching support to informers.  This can cut down on the size of the responses from the server and eventually the memory footprint of an informer.  To support the latter this will not fall back to fetching the entire list like the go client - this may need some refinement as currently it will just keep retrying.

If the limit is not specified, the default is to fetch everything in a single list.

A behavioral difference introduced here is that the affect of a relist is no longer atomic on the cache - rather each item in the relist will perform a cache update and create an event as it is seen.  Since the cache is still eventually consistent either way, I think this change is not a concern.

The javadocs call out a performance warning - it seems that pagination hits etc.d directly and so there's a concern about performance and scaling.

These changes to conflict of course with the api module creation, but that will be easy to resolve.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by shawkins** [comment]
@metacosm @attilapiros Some additional thoughts - it seems to be a pretty advanced case to consider using the limit option with an informer.  There are quite a few comments around the behavior in the go client.  

I don't see much in the literature about it being a built-in case, but it seems like you'd also look towards a sharding pattern - an overall/coordinating operator would create something like a statefulset of controllers, where each has responsibility for a subset of the resources - driven by an annotation (something that is filterable by informers/kubernetes) added by the overall operator.

**Comment by manusa** [comment]
https://github.com/kubernetes/kubernetes/blob/6f896dec4f45ffb82491bc9ce2393e7452886562/staging/src/k8s.io/client-go/tools/cache/reflector.go#L92

**Comment by manusa** [comment]
> I don't see much in the literature about it being a built-in case, but it seems like you'd also look towards a sharding pattern - an overall/coordinating operator would create something like a statefulset of controllers, where each has responsibility for a subset of the resources - driven by an annotation (something that is filterable by informers/kubernetes) added by the overall operator.

I can't find now the source, but I recall that operators should be singletons (or work with some sort of leader-election mechanism). (Which is something that disappointment given the nature of K8s and its overall purpose) 

Is this new _sharding_ approach something documented?

I understand that this has nothing to do with the scope of the current PR, or does it?

**Review by manusa — APPROVED** [review]

**Comment by shawkins** [comment]
> Is this new sharding approach something documented?

No, just a musing on how you would approach it assuming a "singleton" coordinating operator.

> I understand that this has nothing to do with the scope of the current PR, or does it?

So far the only request for this limit/batching logic is to work towards scaling operators.  If there are other applicable approaches we should determine what is best to ultimately peruse.  The next step from here is to control the memory footprint of the cache - from #3636 that either looks like a mapping/pruning function or a store that's not fully in memory.  I don't think the latter seems like the right direction. 

As for this change it does seem like it can stand alone based upon the go client.  There are situations where it is beneficial to form smaller paginated results.

**Comment by shawkins** [comment]
> No, just a musing on how you would approach it assuming a "singleton" coordinating operator.

To elaborate further - you'd have the coordinating operator set a hash on the resource as a label in the range of the number of statefulset replicas.  The statefulset pods would be setup to provide the pod name via an env property, which means they could parse out the pod index to determine which bucket they were responsible for.  The individual informers would then be setup to only look for resources with that index label.  Any dependent resources would need to have that label transitively set as well for the sharding pattern to work all the way down.

**Comment by manusa** [comment]
> To elaborate further [...]

Yes, I figured some mechanism like this. However, I might still see some flaws depending on the use-case (from my undetailed, first-glance perspective). For some other uses, it might not be necessary to have an orchestrating process/controller (i.e. considering a StatefulSet, the Pod's ordinal name might be enough to devise a constant strategy to self-assign the bucket).

**Comment by shawkins** [comment]
> the Pod's ordinal name might be enough to devise a constant strategy to self-assign the bucket

To self-assign the hash/index label would already need to be present on the resources.

> Anyway, I guess this is really off topic for the PR.

Yes, it was just to add some more to the discussion about operator scaling.  I'll add a reference to this to the other on-going issue.

**Comment by manusa** [comment]
> the hash/index label would already need to be present on the resources

Well, in my imaginary example the hash (or input for the resource assignment) could be computed from the resource UID or something similar.

**Comment by shawkins** [comment]
> Well, in my imaginary example the hash (or input for the resource assignment) could be computed from the resource UID or something similar.

Something (which I'm referring to as the overall operator) has to compute a hash to the index and apply it as a label to the resource - it needs to be filterable by an informer.  I tried to summarize all the extra work this would entail at https://github.com/fabric8io/kubernetes-client/issues/3587#issuecomment-1014652601

**Comment by manusa** [comment]
> > Well, in my imaginary example the hash (or input for the resource assignment) could be computed from the resource UID or something similar.
> 
> Something (which I'm referring to as the overall operator) has to compute a hash to the index and apply it as a label to the resource - it needs to be filterable by an informer. I tried to summarize all the extra work this would entail at [#3587 (comment)](https://github.com/fabric8io/kubernetes-client/issues/3587#issuecomment-1014652601)

:sweat_smile: I forgot about the filtering part :) 

From your detailed explanations I get the following:
- The Orchestrating Pod (Overall Operator) is responsible to assign a filterable property (in this case a label) to the resource to be processed. _bottleneck_
- 1-N worker Pods with shared informers that filter the assigned resources and perform the actual work. I guess that scaling might impose a challenge in order to rehash the existing resources(I think you expand on this on your comment).

Support for some sort of server-side dynamic labels or wildcard filtering would be of help to completely remove the orchestrating part (https://github.com/kubernetes/kubernetes/issues/30755)

**Review by rohanKanojia — APPROVED** [review]

**Comment by amydentremont** [comment]
Just wanted to say thanks for adding this feature! My team just ran into needing the ListerWatcher to paginate in the Informer's Reflector and we realized the ability was something we just got from upgrading versions 🙌

**Comment by shawkins** [comment]
> Just wanted to say thanks for adding this feature!

No problem, hope it works out well.

**Pull request merged**
