### PR TITLE
Bulk formatting and removing unused imports

### LINKED ISSUE #3984: Bulk format the entire codebase
### Is your task related to a problem? Please describe

To cut down on the amount of noise in PRs it would be good to bulk format everything now that we haven't seen additional issues with spotless.

### Describe the solution you'd like

Bulk format everything.  At worst the existing prs would need to be rebased, but generally the changes should be mergable.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Fix #3984 and enables removing unused imports.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by andreaTP** [comment]
Style check is failing, apart from that, now that we are at the `6.2` phase I think this does make a lot of sense 🙂 
LGTM 👍

**Comment by shawkins** [comment]
> Style check is failing

A few old files have their header comments in the wrong spot, I'll have that addressed shortly.

**Comment by andreaTP** [comment]
We should remove this line as well:
https://github.com/fabric8io/kubernetes-client/blob/9394b5abca4e3fc10228e8f442003aebbbd849e5/pom.xml#L1059

**Comment by shawkins** [comment]
> We should remove this line as well:

@andreaTP this pr was generated with that removed

**Comment by shawkins** [comment]
@andreaTP or do you mean that we shouldn't need to have that property anymore and just let it format everything on each run?

**Comment by andreaTP** [comment]
Yup, correct @shawkins

**Comment by shawkins** [comment]
@andreaTP updated the pom to always format - it doesn't make much difference in the build time on my ssd system.

**Review by manusa — APPROVED** [review]
image

**Pull request merged**
