### PR TITLE
Added basic support for replace and patch operations in kubernetes-mock

### LINKED ISSUE #458: add support for patch and create operations in kubernetes-mock
One should be able to do:
```java
mock.configMaps()
    .inNamespace(TEST_NAMESPACE)
    .withName(TEST_CONFIG_MAP_NAME)
    .patch(cm)
    .andThrow(new RuntimeException("Failed patching of a resource"))
.once();
```
instead of : 
```java
MockResource<ConfigMap, MockDoneableConfigMap, Boolean> resource = 
    mock.configMaps().inNamespace(TEST_NAMESPACE).withName(TEST_CONFIG_MAP_NAME);
Field delegate = BaseMockOperation.class.getDeclaredField("delegate");
delegate.setAccessible(true);
ClientMixedOperation delegateResource = (ClientMixedOperation)delegate.get(resource);
IExpectationSetters<Object> expect = EasyMock.expect(delegateResource.patch(cm));
expect.andThrow(new RuntimeException("Failed patching of a resource")).once();
```

### PR DESCRIPTION
**Pull request by valdar**
Fix #458

### CODE REVIEW

**Comment by iocanel** [comment]
ok to test

**Comment by iocanel** [comment]
@valdar: since u are the first  person contributing to the mock, could u please comment on https://github.com/fabric8io/kubernetes-client/issues/415

**Comment by valdar** [comment]
@iocanel I'll try to use mockwebserver DSL to do what I have done with kubernetes-mock for camel-master component test and then I'll give feedbacks on this.

**Comment by iocanel** [comment]
@valdar: any news on this?

**Comment by iocanel** [comment]
[merge]

**Comment by iocanel** [comment]
This discussion seems to have stalled, but I since we still haven't deprecated xxx-mock, I think this should be merged.

Thanks @valdar !

**Pull request merged**
