### PR TITLE
Refactor kubernetes-model transitive dependencies

### PR DESCRIPTION
**Pull request by jorsol**
* Rename the `kubernetes-model` to `kubernetes-model-generator` to follow the same name of the artifactId.
* Check and mark lombok as provided dependency everywhere.
* Check and mark sundrio as provided dependency everywhere.
* jsonschema2pojo-core should be used mostly on the maven plugin generator, so it's removed as a direct dependency
* Move duplicate dependency declaration to the parent pom.
* *-model-annotator its used only to generate source, so it's safe to mark lombok/sundrio as compile.

NOTE: This supersedes #2253, if this is merged the other should be closed and vice versa...

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by manusa** [comment]
Could you please rebase the branch to fix the conflicts :pray: ?

**Comment by jorsol** [comment]
> Could you please rebase the branch to fix the conflicts?

Sure, give me a few hours.

**Comment by manusa** [comment]
retest this please

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
