### PR TITLE
feat: add storage and served fields

### LINKED ISSUE #2757: Version annotation should support served and storage attributes
This could then be used by tools that generate CRDs from those annotations.

### LINKED ISSUE #2759: Add ShortNames annotation to specify short names for a CRD

### PR DESCRIPTION
**Pull request by metacosm**
## Description

Fixes #2757
Fixes #2759 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by manusa** [comment]
Shouldn't we add along with the PR the logic that will make use of these annotations? I understand that you are using this for the code-generation project, but it might make sure to improve also the CustomResourceDefinitionContext [methods](https://github.com/fabric8io/kubernetes-client/blob/6648179c0bd7aa0e2e229430eebe71b9d5f4ea77/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java#L100).

Are you sure you want to make served and storage fields default to false? I'm not sure how likely is that one application has more than one version per custom resource, so for those cases it make sense to be opt-out instead of opt-in.

**Comment by metacosm** [comment]
> Shouldn't we add along with the PR the logic that will make use of these annotations? I understand that you are using this for the code-generation project, but it might make sense to also improve the CustomResourceDefinitionContext [methods](https://github.com/fabric8io/kubernetes-client/blob/6648179c0bd7aa0e2e229430eebe71b9d5f4ea77/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java#L100).

Good point.

> 
> Are you sure you want to make served and storage fields default to false? I'm not sure how likely is that one application has more than one version per custom resource, so for those cases it make sense to be opt-out instead of opt-in.

`served` is `true` by default. For `storage`, if we consider that most people will only have one version of their CRD, it might indeed make sense to have the default set to `true`.

**Comment by metacosm** [comment]
Converting back to draft to keep this open as work for this will be completed in #2776

**Comment by manusa** [comment]
> Converting back to draft to keep this open as work for this will be completed in #2776

#2776 was already merged. Is there something in this PR pending to be merged to master? can we close it?

**Comment by metacosm** [comment]
Yes it can be closed now. Sorry!

**Pull request closed without merging**
