### PR TITLE
System.currentTimeMillis() replaced with System.nanoTime()

### LINKED ISSUE #1449: Don't use System.currentTimeMillis for measuring durations
Using wall clock for measuring time is a very bad idea as NTP can update it anytime, so it might just forward or backward.

You should be using `System.nanotime` instead as it's monotonic.

`System.currentTimeMillis` is being used in `HasMetadataOperation`, `ServiceOperationsImpl` and `BaseOperation` for timeouts.

I suspect weird `HasMetadataOperation#periodicWatchUntilReady` documented as `The need for that is that in some cases a pure watcher approach consistently fails.` is because of this.

We encountered super weird timeouts on a slow machine and it was fixed when we reimplemented `waitUntilReady` based on `System.nanotime` and dropped `periodicWatchUntilReady`.

### PR DESCRIPTION
**Pull request by kunal-kushwaha**
Fixes #1449
System.currentTimeMillis replaced with System.nanotime in HasMetadataOperation, ServiceOperationsImpl and BaseOperation for timeouts.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : Could you please check why a test is failing?

**Comment by kunal-kushwaha** [comment]
> @kunal-kushwaha : Could you please check why a test is failing?

**Comment by kunal-kushwaha** [comment]
> @kunal-kushwaha : Could you please check why a test is failing?

Sorry I closed it by mistake while making a comment, it was giving nullpointer exception. I'm working on it.

**Comment by kunal-kushwaha** [comment]
Getting NullPointer in function testWaitUntilReady of class ResourceTest at line 173 while creating a new Pod. 

https://github.com/fabric8io/kubernetes-client/blob/f3c0c1de20d12d7db606c75f27211b26b37a970b/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java#L148

**Comment by kunal-kushwaha** [comment]
Does anybody have any idea for what might be causing this NullPointer at line 173?

**Comment by rohanKanojia** [comment]
@dev-gaur : Could you please take a look into it?

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : Could you please explain why you closed issue and re-opened it?

**Comment by kunal-kushwaha** [comment]
> @kunal-kushwaha : Could you please explain why you closed issue and re-opened it?

@rohanKanojia  I forced pushed to the commit before I made my changes and hence it showed 0 commits in this issue and closed it automatically. I just pushed another new commit and reopened it.

**Comment by kunal-kushwaha** [comment]
@rohanKanojia Why were the tests canceled?

**Comment by rohanKanojia** [comment]
oops, I did it via mistake. let me restart then again

**Pull request merged**
