### PR TITLE
Add ReplicaSet support

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
[merge]

**Comment by rhuss** [comment]
@jimmidyson cool, thanks. If i understand ReplicaSet right, it the same as ReplicationController except that you are more flexible wrt the selector. Is it already available in OpenShift origin 1.1.x ? 

wonder whether I should use it directly for the plugin or whether still to wait a bit.

**Comment by jimmidyson** [comment]
It's still beta API so I'd wait by default, but in time...

**Comment by jimmidyson** [comment]
& yes it is available in OpenShift, but doubt it's properly integrated with auth etc so probably best to avoid for now.

**Pull request merged**
