### PR TITLE
feat: add CSI Volume Snapshot extension

### PR DESCRIPTION
**Pull request by Vlatombe**
## Description

Add DSL for [Volume Snapshots](https://kubernetes.io/docs/concepts/storage/volume-snapshots/)

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@Vlatombe: Is this pull request ready for review? If yes, could you please remove your PR being marked as draft?

**Comment by ajaykmis** [comment]
@Vlatombe : any idea when this PR will be ready?

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
[merge]

**Comment by ajaykmis** [comment]
Thanks for merging this. @rohanKanojia - Any idea when can this be cut into a release? I have been testing the client using the SNAPSHOT version, but will be good to start using the official client.

**Comment by rohanKanojia** [comment]
If everything goes well, I think we should be able to release by the end of next week

**Comment by ajaykmis** [comment]
@rohanKanojia : I see that 4.11 is release now, how do I used the volumesnapshot-client from 4.11? I added this  dependency 'io.fabric8:kubernetes-client:4.11.0' but I don't see volumesnapshot in there. I also added 'io.fabric8:volumesnapshot-client:4.11.0' but it looks like the volumesnapshot-client might not be release.

**Comment by rohanKanojia** [comment]
It's not a part of kubernetes-client, it's added as an extension. You can use it after adding this dependency:
```
<dependency>
  <groupId>io.fabric8</groupId>
  <artifactId>volumesnapshot-client</artifactId>
  <version>4.11.0</version>
</dependency>
```
https://search.maven.org/artifact/io.fabric8/volumesnapshot-client/4.11.0/bundle

**Comment by ajaykmis** [comment]
Thanks, that worked!

**Pull request merged**
