### PR TITLE
Adds configurable serializers and deserializers to json schema codegen

### PR DESCRIPTION
**Pull request by bbeaudreault**
So, I hit a similar issue to https://github.com/fabric8io/kubernetes-client/issues/2131 over the weekend, but unfortunately I did not see https://github.com/fabric8io/kubernetes-client/pull/2281 when I wrote this implementation. I know you already merged 2281, but I wanted to offer up my implementation as an alternative.

Rohan's approach is totally reasonable, and I considered taking it. The reason I didn't is I felt we could get a cleaner implementation by plugging into jsonschema2pojo. We have had to maintain a "hack" (see removed hack in diff) of rewriting the kube-schema to replace JSON with JsonNode. This new approach solves that hack more cleanly, as well as issue 2131.

The benefit of relying on codegen rather than replacing the generated code with manual code  is we will see build failures if anything changes in the kubernetes implementation that is not compatible with the serializers/deserializers.

Anyway, I'm happy to throw this code away if you prefer, but I figured I'd submit it since I wrote it around the same time Rohan wrote his.

cc @rohanKanojia

### CODE REVIEW

**Comment by bbeaudreault** [comment]
Unfortunately the `JSON` handling needs to use `writeRawValue`, which is not compatible with the YAMLGenerator. I can't think of a way around that so I guess I'll punt on this for now. I do think we could similarly remove the hack I mentioned by doing what Rohan did, but for JSON as well. We'd need to modify the class to keep track of a JsonNode, which isn't pretty. But probably better than a regex to update the schema.

**Comment by manusa** [comment]
I like the generator approach because this is really a problem that should be tackled at generation time (Same for classes such as [IntOrString](https://javadoc.io/doc/io.fabric8/kubernetes-model-core/latest/io/fabric8/kubernetes/api/model/IntOrString.html), etc.). IMHO The main problem with apiextensions is that these types (`JSON*Or*`) are somewhat bizarre and don't even work in some K8s version (at least I couldn't).

Regarding `JSON`, type is already being mapped to `JsonNode` in the [generator](https://github.com/fabric8io/kubernetes-client/blob/2d1a9d47d42e6aa37ba3cb0e70ede9429c93e392/kubernetes-model-generator/kubernetes-model-apiextensions/cmd/generate/generate.go#L115). Generator should really have some Map/function (if it doesn't already) to globally take care of these mappings (I agree with the strings replace being a bad idea), before the schema is even generated.

**Comment by rohanKanojia** [comment]
I think adding a hashmap to take care of these mappings should not be that hard. let me try it out.

**Comment by bbeaudreault** [comment]
Ok I'll reopen this PR and let rohan handle JSON in his PR. I'll just handle the 3 `JSON*Or*` classes I've tackled for now, but we can do a followup PR to handle things like IntOrString. Does that sound ok?

**Comment by bbeaudreault** [comment]
@rohanKanojia if you merge yours, since it's already approved, i'll rebase mine on top and remove the JSON handling

**Comment by rohanKanojia** [comment]
retest this please

**Comment by bbeaudreault** [comment]
This PR is ready -- the only remaining failure is the usual flaky test DefaultSharedIndexInformerTest

**Comment by rohanKanojia** [comment]
retest this please

**Comment by rohanKanojia** [comment]
ah, I would fix this flaky test. This started failing randomly when I removed Thread.sleep in tests. Need to revisit this and fix :-(

**Comment by rohanKanojia** [comment]
Could you please squash your commits into one?

**Comment by bbeaudreault** [comment]
@rohanKanojia all set

**Comment by rohanKanojia** [comment]
add to whitelist

**Comment by rohanKanojia** [comment]
I would appreciate if you could address Sonar code smells, most of them can be easily addressed.

**Comment by bbeaudreault** [comment]
@rohanKanojia this one is also all set. The test failure seems like a flaky test, since 3.11 succeeds. Can you re-run and merge if looks good?

**Comment by bbeaudreault** [comment]
@rohanKanojia any chance we can get this merged?

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
