### PR TITLE
fix: Singular is missing from CustomResourceDefinitionContext

### PR DESCRIPTION
**Pull request by jorsol**
## Description

Fixes: #2843 
## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by metacosm — APPROVED** [review]

**Review by manusa — APPROVED** [review]
Changes seem fine to me, thx!

However, where is this field going to be used?

**Comment by jorsol** [comment]
Mostly for external use, I need to have access to the singular name, but now that I'm thinking this more thoroughly, I could simply use CustomResource.getSingular().

**Review by rohanKanojia — APPROVED** [review]

**Comment by metacosm** [comment]
> Mostly for external use, I need to have access to the singular name, but now that I'm thinking this more thoroughly, I could simply use CustomResource.getSingular().

Probably, yes. That said we might change this in future releases (or at least, not make it specific to `CustomResource`). If you have any opinion on the subject, we'd love to hear it! 😄

**Comment by jorsol** [comment]
I think this is no longer relevant, so consider closing it.

**Comment by manusa** [comment]
> I think this is no longer relevant, so consider closing it.

Following YAGNI, I'm going to close the PR since, internally, I really don't see the need to have singular in the CR context (class meant to be used only internally).

Anyway, we really appreciate your contributions and keeping up with the project :heart:.

**Pull request closed without merging**
