### PR TITLE
Fix README builder creation example

### PR DESCRIPTION
**Pull request by PlasmaPower**
As is, it gives a null pointer exception (which left me very confused - maybe that should change too?).

### CODE REVIEW

**Comment by PlasmaPower** [comment]
I should clarify that I tried this with pods, not services. I'm not sure if that makes a difference.

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
[merge]

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
[merge]

**Comment by oscerd** [comment]
Can you please close this PR and open a new one? Thanks

**Comment by PlasmaPower** [comment]
Done with #953.

**Pull request closed without merging**
