### PR TITLE
Make adapt() and isAdaptable() methods more generic (no longer limite…

### PR DESCRIPTION
**Pull request by iocanel**
…d to Client instances). Allow the client to be adapted to OkHttpClient as an indirect way to gain access to the client.

### CODE REVIEW

**Comment by jimmidyson** [comment]
LGTM

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
@iocanel Needs a rebase

**Comment by jimmidyson** [comment]
[merge]

**Comment by iocanel** [comment]
[merge]

**Comment by jimmidyson** [comment]
beat ya!

**Pull request merged**
