### PR TITLE
Fixes #744

### LINKED ISSUE #744: Minor API issue: Watcher<T> should probably be Watcher<T extends HasMetadata>
Hello; thanks for your work on this project.

It seems to me that the `Watcher` class should not take an undifferentiated type parameter but should instead use `T extends HasMetadata`.  (Creating, say, a `Watcher<Integer>` is currently permitted but we all know such a thing would never be called.)

I base this off the [only location I could find in the source base where the `eventReceived` method is called](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L207-L217), and the payload is forced into being a subclass of `HasMetadata`.

### PR DESCRIPTION
**Pull request by kunal-kushwaha**
Fixes #744

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : build seems to be failing, Could you please address those build failures whenever you get time?

**Comment by kunal-kushwaha** [comment]
There have been uses of Watcher<String>, String is an an undifferentiated type parameter. How do I replace it when it doesn't implement HasMetadata?

**Comment by rohanKanojia** [comment]
Apologies for the late reply, I think uses of Watcher with String parameters were added by me in order to handle raw CustomResource events where we don't have POJOs to deserialize. 

Maybe we can introduce another interface similar to the current `Watcher` called `RawWatcher` which would handle those raw String-based events??

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: Ah been a long time indeed. Will work on it when I get some time free from current schedule, with college and internships 😅

**Comment by rohanKanojia** [comment]
No rush, take your time :-)

**Comment by kunal-kushwaha** [comment]
Didn't get time to look into this :(

**Pull request closed without merging**
