### PR TITLE
adds a method to customize KubernetesMockServer clients

### PR DESCRIPTION
**Pull request by shawkins**
## Description

@manusa @jonsie this seems like the quickest fix, the alternative would be more involved - updating the annoation(s) to have a KubernetesSerialization provider.  Does this fix seem sufficient? 

More completely addresses #5293

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jonsie** [comment]
Looks good.  Verifying we can call this on the mock server after it's started?

**Comment by shawkins** [comment]
> Looks good. Verifying we can call this on the mock server after it's started?

Yes that would look like:

Fully manual:
```
  KubernetesMockServer server;
  KubernetesClient client;

  @BeforeEach
  void setUp() {
    server = new KubernetesMockServer();
    server.start();
    client = server.createClient(builder -> builder.withKubernetesSerialization(ks));
  }
```

Or with a test annotation on the injected instance:

```
@EnableKubernetesMockClient
class MyTest {
  private KubernetesMockServer server;
  private KubernetesClient client;  
  
  @BeforeEach
  void setUp() {
    // replace the injected client
    client.close(); 
    client = server.createClient(builder -> builder.withKubernetesSerialization(ks));
  }
```

**Comment by jonsie** [comment]
Looks great, thanks for the quick turnaround!  Any idea when this would make it to a release?

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
I don't really like the approach since it makes it kind of cumbersome. Users will need to update most tests and implement the test preparation method.
I'll send an alternative approach later today, we can compare and see what works better

**Comment by shawkins** [comment]
> I don't really like the approach

I guessed as much :) but it seems pretty sprawling to address this more idomatically - and it's not exactly a common case yet.

**Comment by manusa** [comment]
> I guessed as much :) but it seems pretty sprawling to address this more idomatically - and it's not exactly a common case yet.

Proposed alternative #5349

**Pull request closed without merging**
