### PR TITLE
[chore] bump sundrio to 0.80.1

### PR DESCRIPTION
**Pull request by andreaTP**
## Description

Updates needed for #3665 
and eventually to merge the fix for #3716

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [X] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by andreaTP** [comment]
the CI failure looks unrelated with this change, @manusa do you think we can get this in 5.12 (due to the breaking API changes) ?

**Comment by manusa** [comment]
> the CI failure looks unrelated with this change,

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project kubernetes-itests: Compilation failure: Compilation failure: 
Error:  /home/runner/work/kubernetes-client/kubernetes-client/kubernetes-itests/src/test/java/io/fabric8/openshift/OpenShiftAuthorizationIT.java:[169,7] cannot find symbol
Error:    symbol:   method addNewGroup(java.lang.String)
Error:    location: interface io.fabric8.openshift.api.model.RoleBindingRestrictionSpecFluent.GrouprestrictionNested<io.fabric8.openshift.api.model.RoleBindingRestrictionFluent.SpecNested<io.fabric8.openshift.api.model.RoleBindingRestrictionBuilder>>
Error:  /home/runner/work/kubernetes-client/kubernetes-client/kubernetes-itests/src/test/java/io/fabric8/kubernetes/CustomResourceDefinitionIT.java:[113,37] cannot find symbol
Error:    symbol:   method addNewShortName(java.lang.String)
Error:    location: interface io.fabric8.kubernetes.api.model.apiextensions.v1.CustomResourceDefinitionSpecFluent.NamesNested<io.fabric8.kubernetes.api.model.apiextensions.v1.CustomResourceDefinitionFluent.SpecNested<io.fabric8.kubernetes.api.model.apiextensions.v1.CustomResourceDefinitionBuilder>>
Error:  -> [Help 1]
```

They do seem to be related. For some reason I thought that the `withNew***` methods had been removed a while back :flushed: 

>  @manusa do you think we can get this in 5.12 (due to the breaking API changes) ?

These kind of changes are never welcome. Given the fact that we should start working on 6.x, IMHO it might be better to delay these changes until then.

Is there any specific reason why you'd need these changes on 5.x?

**Comment by andreaTP** [comment]
@manusa I'm fixing the additional failures (sorry hadn't noticed the e2e 😊  )

I need to get this fix in https://github.com/sundrio/sundrio/pull/296 to make #3689 fully usable (for my use-case).
I completely understand the concerns regarding the breaking changes, in this case I would kindly ask @metacosm or @iocanel if we can, eventually, publish sundrio `0.50.3` including the fix (I'm assuming that the fix is legit 🙂  ).

**Comment by iocanel** [comment]
> They do seem to be related. For some reason I thought that the `withNew***` methods had been removed a while back flushed
> 
> >

The `withNew**` that accept String arguments haven't been removed, but deprecated a long time ago! Finally, removed in 0.80.0.

**Comment by iocanel** [comment]
> @manusa I'm fixing the additional failures (sorry hadn't noticed the e2e blush )
> 
> I need to get this fix in [sundrio/sundrio#296](https://github.com/sundrio/sundrio/pull/296) to make #3689 fully usable (for my use-case). I completely understand the concerns regarding the breaking changes, in this case I would kindly ask @metacosm or @iocanel if we can, eventually, publish sundrio `0.50.3` including the fix (I'm assuming that the fix is legit slightly_smiling_face ).

We did release 0.50.3, so you are clear!

**Comment by andreaTP** [comment]
@manusa plase ping me when the development of the `6.X` series starts so that I can rebase this branch.

**Comment by manusa** [comment]
> @manusa please ping me when the development of the `6.X` series starts so that I can rebase this branch.

no pb. As soon as 5.12 is out, sorry for the delay on this. I want to be sure that most of the bugs or back-portable issues get fixes so that we can minimize the patching effort in the coming months.

You'll also be aware with the overall pom versioning in master branch being changed to 6.0-SNAPSHOT

**Comment by andreaTP** [comment]
@iocanel I'm updating this PR but we need `0.80.1` containing the fix to have the tests passing, please let me know when is available. 🙏

**Comment by andreaTP** [comment]
Ping, periodic reminder that we need a release of `sundrio` containing the most recent fixes 😛  🙏  @iocanel

**Comment by manusa** [comment]
https://github.com/sundrio/sundrio/releases/tag/0.80.1 was released a few days ago

**Comment by andreaTP** [comment]
thanks for the heads up @manusa !

**Comment by andreaTP** [comment]
Ready now 🎉  cc. @manusa @oscerd

**Review by metacosm — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
It might be interesting to add a note here https://github.com/fabric8io/kubernetes-client/blob/master/doc/MIGRATION-v6.md
for the breaking change

**Pull request merged**
