### PR TITLE
Fix 1109: something drops '-' from Singular/Plural forms of CustomRes…

### LINKED ISSUE #1109: something drops '-' from Singular/Plural forms of CustomResources.
I define a CustomResource like this:
```java
public static final CustomResourceDefinition DEFINITION =
    new CustomResourceDefinitionBuilder()
        .withNewMetadata()
        .withName("foo-bar.baz.example.com")
        .endMetadata()
        .withNewSpec()
        .withGroup("baz.example.com")
        .withVersion("v1alpha1")
        .withScope("Namespaced")
        .withNewNames()
        .withKind("FooBar")
        .withPlural("foo-bars")
        .withSingular("foo-bar")
        .endNames()
        .endSpec()
        .build();
```
Now a simple test fails:
```java
FooBar fb1 = new FooBar();
fb1.getMetadata().setName("example");
FooBar.client(client).inNamespace("default").create(fb1);

FooBar fb2 = FooBar.client(client).inNamespace("default").withName("example").get();
```
and this fails with a 404. I added some more printf
https://github.com/ensonic/kubernetes-client/commit/29d8096a25b961cd88cfeb9b7aafa0476560107d
and what I see is this:
```
Query string: '/apis/baz.example.com/v1alpha1/namespaces/default/foo-bars/example'
Query attributes: '{attributes: {namespace={key:namespace, value:default}, name={key:name, value:example}, kind={key:kind, value:foo-bar}}}'
Comparing attributes: '{attributes: {namespace={key:namespace, value:default}, name={key:name, value:example}, kind={key:kind, value:foobar}}}'
```

So, something elmininated the '-' in the kind, when the object was created. When I do this with kubernetes itself it works though. Also 
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
suggests that dashes are allowed. I am a bit lost at finding the code that is responsible for it.

### PR DESCRIPTION
**Pull request by dev-gaur**
…ources

fixes #1109

### CODE REVIEW

**Comment by dev-gaur** [comment]
[test]

**Comment by manusa** [comment]
retest this please

**Comment by manusa** [comment]
retest this please

**Comment by manusa** [comment]
retest this please

**Comment by rohanKanojia** [comment]
retest this please

**Comment by manusa** [comment]
[merge]

**Pull request merged**
