### PR TITLE
Fix #5608 Support authentication with certificate in exec-credentials

### LINKED ISSUE #5608: Support authentication with certificate in exec-credentials
### Is your task related to a problem? Please describe

In class io.fabric8.kubernetes.client.Config, it is only support authenticate with token, authenticate with certificate is unsupported and marked as TODO.

Due to there is no token generated by ExecConfig and certificate is not supported yet, so all requests treat as anonymous request

`WARN    No token returned`

`Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://[server]:6443/api/v1/namespaces/sandbox/secrets. Message: secrets is forbidden: User "system:anonymous" cannot list resource "secrets" in API group "" in the namespace "sandbox". Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=secrets, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=secrets is forbidden: User "system:anonymous" cannot list resource "secrets" in API group "" in the namespace "sandbox", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).`

### Describe the solution you'd like

Implement TODO item, add support to authenticate with certificate

### Describe alternatives you've considered

_No response_

### Additional context

Fabric8 Kubernetes Client version: 6.8.1

### PR DESCRIPTION
**Pull request by qingboooo**
## Description

Fix #5608

ExecCredentialStatus also contains clientKeyData and clientCertificateData fields

https://kubernetes.io/docs/reference/config-api/client-authentication.v1beta1/#client-authentication-k8s-io-v1beta1-ExecCredentialStatus

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@qingboooo : Thanks, is it possible to add some test to validate this?

**Comment by qingboooo** [comment]
Thanks for the quick response.

For sure, I am now trying to validate it with UT and Regression Test locally

Rohan Kumar ***@***.***> 于2023年11月27日周一 14:20写道：

**Comment by qingboooo** [comment]
@rohanKanojia some checks failed, seems some of them are not related to the code change, see my quick analysis below:

- **Build / Java 8 Maven**: Failed in UT io.fabric8.crd.generator.zookeeper.ZookeeperCustomResourceTest, but succeeded locally, is it possible an infra/env problem?
- **Windows Build / Java 11 Maven**: Same as above failure
- **Build / Java 11 Maven**: Cancelled, I didn't see any failure
- **E2E Tests / OpenShift (v3.11.0)**: Failed to startup OpenShift cluster
- **SonarCloud Code Analysis**: Test coverage not enough, will update the test to increase the coverage rate

Do you have some suggestions? thanks in advance.

**Comment by rohanKanojia** [comment]
Openshift CI failure is a known issue https://github.com/fabric8io/kubernetes-client/issues/5545 . Other failures might be due to flaky tests

Let's see if we see then on re-runs.

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
It would require review from other team members as well. Maybe in a week or two it might get merged.

**Review by shawkins — APPROVED** [review]
@qingboooo thank you for the pr - the tests look great.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
