### PR TITLE
fix #1515 HasMetadataOperation.periodicWatchUntilReady is broken

### LINKED ISSUE #1515: HasMetadataOperation.periodicWatchUntilReady is broken
Our call to `HasMetadataOperation.waitUntilReady` never returns. A stacktrace suggests that the thread is stuck awaiting the latch at https://github.com/fabric8io/kubernetes-client/blob/5f5d1697839b0b220bf400133a4dbe65a56f797d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L192

I believe the cause is https://github.com/fabric8io/kubernetes-client/pull/1451
which changes millisecond values into nanoseconds, but the `interval` value used in the above line is still treated as a milliseconds value, resulting in a huge wait time.

### PR DESCRIPTION
**Pull request by oscerd**
Fixes #1515

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
@rohanKanojia can you run again the build for 3.10.0?

**Comment by oscerd** [comment]
[merge]

**Comment by rohanKanojia** [comment]
strange, there is a failing test in merge logs:
```
INFO: MockWebServer[59077] done accepting connections: Socket closed
[WARNING] Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 5.007 s - in io.fabric8.kubernetes.client.mock.ReplicaSetTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ResourceTest.testWaitUntilReady:173 » NullPointer
[INFO] 
[ERROR] Tests run: 231, Failures: 0, Errors: 1, Skipped: 4
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Fabric8 :: Kubernetes :: Project ................... SUCCESS [  3.849 s]
[INFO] Fabric8 :: Kubernetes Model Parent ................. SUCCESS [  0.480 s]
[INFO] Fabric8 :: Kubernetes Model :: Common .............. SUCCESS [  1.309 s]
[INFO] Fabric8 :: Kubernetes Model Annotator .............. SUCCESS [  1.445 s]
[INFO] Fabric8 :: Kubernetes Model ........................ SUCCESS [05:44 min]
[INFO] Fabric8 :: Kubernetes :: Java Client ............... SUCCESS [ 31.535 s]
[INFO] Fabric8 :: Kubernetes :: Server Mock ............... SUCCESS [ 14.208 s]
[INFO] Fabric8 :: Openshift :: Java Client ................ SUCCESS [ 10.810 s]
[INFO] Fabric8 :: Openshift :: Server Mock ................ SUCCESS [  0.400 s]
[INFO] Fabric8 :: Kubernetes :: Client Examples ........... SUCCESS [  0.653 s]
[INFO] Fabric8 :: Kubernetes :: Platforms ................. SUCCESS [  0.012 s]
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf ........ SUCCESS [  0.011 s]
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf :: Features SUCCESS [  0.055 s]
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf :: Tests SUCCESS [ 35.759 s]
[INFO] Fabric8 :: Kubernetes :: Tests ..................... FAILURE [07:28 min]
[INFO] Fabric8 :: Kubernetes and Openshift :: UberJar ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:55 min
[INFO] Finished at: 2019-05-16T05:12:36-04:00
[INFO] Final Memory: 96M/983M
[INFO] ------------------------------------------------------------------------
```

**Comment by rohanKanojia** [comment]
[merge]

**Comment by oscerd** [comment]
I don't know.

**Comment by oscerd** [comment]
[merge]

**Comment by oscerd** [comment]
[merge]

**Comment by oscerd** [comment]
@rohanKanojia can you take a look ? I don't think it's a problem with PR

**Comment by rohanKanojia** [comment]
Hmm, strange.... let me pull it and check asap

**Comment by rohanKanojia** [comment]
retest this please

**Comment by rohanKanojia** [comment]
build passed on my machine, not sure why it's failing here

**Comment by rohanKanojia** [comment]
Nah, I accidentally built on the wrong branch. it's failing

**Comment by oscerd** [comment]
[merge]

**Comment by paxbit** [comment]
@rohanKanojia @oscerd 
Still appears broken to me. See: https://github.com/fabric8io/kubernetes-client/issues/1515#issuecomment-510090313

**Pull request merged**
