### PR TITLE
Changes to support tektoncd/pipeline v0.24.1

### LINKED ISSUE #3140: Tekton Client updated for 0.24
In 0.24 of Tekton this PR was fixed to add Host Aliases to the Pod Template. https://github.com/tektoncd/pipeline/pull/3889

What needs to be done to incorporate this?

### PR DESCRIPTION
**Pull request by tlawrie**
## Description
Fixes #3140 and supports the latest release of Tekton to v0.24.1

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by tlawrie** [comment]
Hi @rohanKanojia this is the PR for the issue you have been guiding me on. Let me know if there is more to be done / tested / verified.

**Comment by rohanKanojia** [comment]
@tlawrie : Sorry for late reply, Thanks for creating a PR. 

Do you know if new Tekton models were added in this version. If yes, they need to be added here https://github.com/fabric8io/kubernetes-client/blob/master/extensions/tekton/generator-v1beta1/cmd/generate/generate.go#L32

It would be nice to have some serialization/deserialization tests for tekton resources.

**Comment by rohanKanojia** [comment]
@tlawrie : [0.24.2](https://github.com/tektoncd/pipeline/releases/tag/v0.24.2) got released yesterday. Shall we bump the version?

**Comment by tlawrie** [comment]
Hi @rohanKanojia we probably should. Ill update the PR. 

W.r.t the serialization tests and additional models. I'd need help / pointers in how to do this...

**Comment by rohanKanojia** [comment]
@tlawrie : No worries, I think this PR is good as it to merge too. We can create a separate issue for tests and track it there.

**Comment by rohanKanojia** [comment]
Did you run `make` after bumping version? I don't see any schema files getting affected, or maybe there wasn't any change in schema in this new patch release?

**Comment by tlawrie** [comment]
As for models, I looked here: https://github.com/tektoncd/pipeline/blob/1f5980f8c8a05b106687cfa3e5b3193c213cb66e/pkg/apis/pipeline/v1beta1/register.go and the 5 list types seem to correspond to what was in the `generate.go`

**Comment by tlawrie** [comment]
Running make in the background now. Was just checking on the models in case I needed to do something further.

**Comment by tlawrie** [comment]
Agree on new issue for tests, id love to help, just need a bit of guidance to set up my local and how to structure them. New to Go. But happy to do it.

**Comment by tlawrie** [comment]
Id also like to raise an issue to document this process based on the guidance you have given so far. That way anyone can contribute / update every time there is a new release.

**Comment by rohanKanojia** [comment]
Sure, no problem. Please feel free to create a PR/issue about it.

**Comment by tlawrie** [comment]
Hi @rohanKanojia when running the make, hit an issue. 

```
[ERROR] Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:1.1.0:generate (generate) on project tekton-model-v1beta1: Execution generate of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:1.1.0:generate failed: trying to create the same field twice: input 
```

Looking at that WhenExpression struct from last time its like 0.24.2 has reverted to 0.24.0 when it had problems doing the generation

0.24.1: https://github.com/tektoncd/pipeline/blob/v0.24.1/pkg/apis/pipeline/v1beta1/when_types.go#L26
0.24.2: https://github.com/tektoncd/pipeline/blob/v0.24.2/pkg/apis/pipeline/v1beta1/when_types.go

**Comment by rohanKanojia** [comment]
ah, I'm not sure why they reintroduced that field in that struct again(that too, in a patch release) :-( . We're hitting into https://github.com/joelittlejohn/jsonschema2pojo/issues/637 again like we were in 0.24.0

**Comment by tlawrie** [comment]
Ive raised an issue on TektonCD https://github.com/tektoncd/pipeline/issues/4017

**Comment by tlawrie** [comment]
Should we revert my commit, and go with 0.24.1 but track 0.24.2 and the issue to see if we can close it out at a later time?

**Comment by rohanKanojia** [comment]
We can either stick to 0.24.1 or modify our schema generator to rename field to something else.

**Comment by rohanKanojia** [comment]
> Should we revert my commit, and go with 0.24.1 but track 0.24.2 and the issue to see if we can close it out at a later time?

@tlawrie : Sounds good to me :+1:

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by tlawrie** [comment]
Hey @rohanKanojia do you know when this will make it out in a client build? Looking to test whether this then also fixes the real issue which was HostAliases missing from the implementation (because Tekton only fixed that on a later version)

**Comment by rohanKanojia** [comment]
Do you mean when the next version is going to be released? Releasing 5.5.0 is part of our sprint plan[0]. I think we should be able to release 2-3 weeks

[0] https://github.com/eclipse/jkube/projects/22

**Comment by tlawrie** [comment]
Thanks @rohanKanojia. In the meantime i tried to generate a tekton client jar locally but having a large number of issues.

1. Had to skip the `karaf.itest` as it kept failing
2. I ran the generateModel.sh and then `mvn clean install` but I get a JAR that doesn't contain the required models

Are you able to guide me so I can build a local JAR of tekton and import it to my project?

```
jar tf tekton-client-5.5-20210625.002823-1.jar
META-INF/
META-INF/MANIFEST.MF
META-INF/maven/
META-INF/maven/io.fabric8/
META-INF/maven/io.fabric8/tekton-client/
META-INF/maven/io.fabric8/tekton-client/pom.properties
META-INF/maven/io.fabric8/tekton-client/pom.xml
META-INF/services/
META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter
META-INF/services/io.fabric8.kubernetes.client.ResourceHandler
io/
io/fabric8/
io/fabric8/tekton/
io/fabric8/tekton/client/
io/fabric8/tekton/client/CodeGen.class
io/fabric8/tekton/client/DefaultTektonClient.class
io/fabric8/tekton/client/GenericTektonClient.class
io/fabric8/tekton/client/NamespacedTektonClient.class
io/fabric8/tekton/client/TektonClient.class
io/fabric8/tekton/client/TektonExtensionAdapter.class
io/fabric8/tekton/client/V1alpha1APIGroupClient.class
io/fabric8/tekton/client/V1alpha1APIGroupExtensionAdapter.class
io/fabric8/tekton/client/V1beta1APIGroupClient.class
io/fabric8/tekton/client/V1beta1APIGroupExtensionAdapter.class
io/fabric8/tekton/client/dsl/
io/fabric8/tekton/client/dsl/V1alpha1APIGroupDSL.class
io/fabric8/tekton/client/dsl/V1beta1APIGroupDSL.class
io/fabric8/tekton/client/handlers/
io/fabric8/tekton/client/handlers/v1alpha1/
io/fabric8/tekton/client/handlers/v1alpha1/ClusterTaskHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/ClusterTriggerBindingHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/ConditionHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/EventListenerHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/PipelineHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/PipelineResourceHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/PipelineRunHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/TaskHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/TaskRunHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/TriggerBindingHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/TriggerHandler.class
io/fabric8/tekton/client/handlers/v1alpha1/TriggerTemplateHandler.class
io/fabric8/tekton/client/handlers/v1beta1/
io/fabric8/tekton/client/handlers/v1beta1/ClusterTaskHandler.class
io/fabric8/tekton/client/handlers/v1beta1/PipelineHandler.class
io/fabric8/tekton/client/handlers/v1beta1/PipelineRunHandler.class
io/fabric8/tekton/client/handlers/v1beta1/TaskHandler.class
io/fabric8/tekton/client/handlers/v1beta1/TaskRunHandler.class
io/fabric8/tekton/client/internal/
io/fabric8/tekton/client/internal/v1alpha1/
io/fabric8/tekton/client/internal/v1alpha1/ClusterTaskOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/ClusterTriggerBindingOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/ConditionOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/EventListenerOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/PipelineOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/PipelineResourceOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/PipelineRunOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/TaskOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/TaskRunOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/TriggerBindingOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/TriggerOperationsImpl.class
io/fabric8/tekton/client/internal/v1alpha1/TriggerTemplateOperationsImpl.class
io/fabric8/tekton/client/internal/v1beta1/
io/fabric8/tekton/client/internal/v1beta1/ClusterTaskOperationsImpl.class
io/fabric8/tekton/client/internal/v1beta1/PipelineOperationsImpl.class
io/fabric8/tekton/client/internal/v1beta1/PipelineRunOperationsImpl.class
io/fabric8/tekton/client/internal/v1beta1/TaskOperationsImpl.class
io/fabric8/tekton/client/internal/v1beta1/TaskRunOperationsImpl.class
io/fabric8/tekton/client/util/
io/fabric8/tekton/client/util/ApiVersionUtil.class
```

**Comment by rohanKanojia** [comment]
Your change modified tekton schema so you won't really need to generate model again. It's strange that you're not able to see updated model on `mvn clean install`. I think if you just want to generate a jar locally you can easily do it with `mvn clean install -DskipTests`

[v5.5.0](https://github.com/fabric8io/kubernetes-client/milestone/27) is going to be released next Wednesday

**Comment by tlawrie** [comment]
Ok. So i was able to see the updated JAR but I needed to manually import the JARs separately tekton-client, tekton-model-v1beta1, tekton-triggers, knative-model

And now that I am testing to see if it picked up the new HostAlias on the pod template. And it doesn't seem to be able to. Either I am doing something wrong with these JARs (very possible) or the update made didn't pull in this change from Tekton.

**Comment by tlawrie** [comment]
Even though the change is clearly in the commit -> extensions/tekton/model-v1beta1/src/main/resources/schema/tekton-schema-v1beta1.json

**Comment by rohanKanojia** [comment]
@tlawrie : Bdw, have you tried out https://jitpack.io/ for testing master snapshot build? I think this might help you in testing snapshot versions without having to build it locally

**Comment by tlawrie** [comment]
Very interesting. Ill definitely look into that.

Do you think that will get a different result to not being able to find the host alias against a pod template?

**Comment by rohanKanojia** [comment]
> Do you think that will get a different result to not being able to find the host alias against a pod template?

Could you please elaborate? Which generated class are you looking into? Maybe we missed something while upgrading the model? I haven't seen any case in past when released artifacts have a different version than locally generated artifacts.

**Comment by tlawrie** [comment]
Hi @rohanKanojia thanks for the help. Got it all working locally. I think next time I will definitely try jitpack!

**Pull request merged**
