### PR TITLE
GitHub issue 923

### PR DESCRIPTION
**Pull request by rohanKanojia**
Add more CRUD tests #923

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by rohanKanojia** [comment]
Hey, i have a doubt. Could anyone please give me any example of simple update case. In almost all the test cases i've been unable to do an edit operation. For example, take a look at SecretCrudTest.java . If i uncomment that edit section i get an error like this : 
```
Dec 18, 2017 12:20:38 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[42605] done accepting connections: Socket closed
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.199 sec <<< FAILURE! - in io.fabric8.kubernetes.client.mock.SecretCrudTest
testCrud(io.fabric8.kubernetes.client.mock.SecretCrudTest)  Time elapsed: 3.08 sec  <<< ERROR!
java.lang.NullPointerException
	at io.fabric8.kubernetes.client.mock.SecretCrudTest.testCrud(SecretCrudTest.java:78)


Results :

Tests in error: 
  SecretCrudTest.testCrud:78 » NullPointer

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```
I'm not sure if i'm doing it the right way or maybe there is some bug in Kubernetes mock server in CRUD mode. All the other tests also show same error in case of edit. Plus there were some failures in Deployment related resources as well.

**Comment by oscerd** [comment]
Open an issue for that and we can take a look.

**Comment by oscerd** [comment]
@iocanel would you mind take a look here? Can we merge and take a look at the edit operation later?

**Comment by iocanel** [comment]
Rebased and addressed the edit issue.

Note: I am not sure if its even possible to a edit a resources name. It definitely causes issues in our crud tests. I replaced it with adding a label instead.

**Comment by iocanel** [comment]
[merge]

**Pull request merged**
