### PR TITLE
Changes the resource kind in the ProjectRequestHandler from "Project" to "ProjectRequest"

### LINKED ISSUE #2442: ProjectRequestHandler is registered as handler for Project
After updating from the client version 4.10.2 to 4.11.0 I'm experiencing the following bug:

I'm using the client to create all resources of a KubernetesList in the following way:
`client.resourceList(resources).createOrReplace()`

The list also contains one resource of the kind "Project" and apiGroup "project.openshift.io/v1". When it's the project's turn to be created, I get the following error with new version of the client while it worked with the old one: `class io.fabric8.openshift.api.model.Project cannot be cast to class io.fabric8.openshift.api.model.ProjectRequest`.

I think the culprit lies somewhere in the resuscitation of the ProjectRequestHandler and I'd like to verify that. In [this line ](https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/handlers/ProjectRequestHandler.java#L42) I guess `return Project.class.getSimpleName();` might need to be replaced with `return ProjectRequest.class.getSimpleName();`.

With the way the ProjectRequestHandler is written now, a call to `Handlers.get("Project", "project.openshift.io/v1")` will return the ProjectRequestHandler instead of the ProjectHandler and after that the erroneous cast happens. That's exactly what happens in the "acceptVisitors" method of NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl after the wrong handler is returned.

### PR DESCRIPTION
**Pull request by Obirah**
Fix #2442 

## Description
Changes the resource kind in the ProjectRequestHandler from "Project" to "ProjectRequest" so that the client does not wrongfully try to cast a Project to ProjectRequest.

## Type of change
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Thanks for your PR. Could you please add a test of loading a ProjectRequest and verifying that it's successful?

**Comment by Obirah** [comment]
> Thanks for your PR. Could you please add a test of loading a ProjectRequest and verifying that it's successful?

I'll try, but unfortunately my IntelliJ has some problems to properly import and index the project. If I'm able to fix that, of course I'll code the test.

**Comment by Obirah** [comment]
@rohanKanojia, I added it to the `HandlersTest` in the same fashion the other resources are tested. Is that sufficient or do we need a separate test that does even more?

**Comment by rohanKanojia** [comment]
Umm, I think this should work. Are you able to resolve your issue while loading a generic resoucelist with this change?
```
client.resourceList(resources).createOrReplace();
```

**Comment by Obirah** [comment]
> Umm, I think this should work. Are you able to resolve your issue while loading a generic resoucelist with this change?
> 
> ```
> client.resourceList(resources).createOrReplace();
> ```

Yes, I just created a small, temporary test on my machine that creates a KubernetesList containing a Project directly on one of my OpenShift clusters and it worked.

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
