### PR TITLE
Fixes problems with swallowed InterruptedExceptions #1201

### LINKED ISSUE #1199: Improperly handled InterruptedException in NonBlockingInputStreamPumper?
I am not sure, but this:

https://github.com/fabric8io/kubernetes-client/blob/f7843cff15b239e4466167f63c599fc9ca4e4146/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/NonBlockingInputStreamPumper.java#L68-L70

...effectively does nothing.  The presence of an `InterruptedException` means the interrupted status has been cleared, so `Thread#interrupted()` will redundantly clear the interrupted status as well as return false, and its return value is ignored here.

Is it possible that the author actually meant something quite different here, namely `Thread#interrupt()`?

### PR DESCRIPTION
**Pull request by ljnelson**
Signed-off-by: Laird Nelson <ljnelson@gmail.com>

This PR should fix issue #1201.  It deliberately does not fix #1199 as it is not immediately clear to me what the intent of that particular catch block was.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by ljnelson** [comment]
Done.

**Comment by rohanKanojia** [comment]
@oscerd :Shall we cherry-pick this to 3.x and 3.1.x also?

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
