### PR TITLE
fix: Cannot change the type of the Service from ClusterIP to External…

### PR DESCRIPTION
**Pull request by jorsol**
Fixes: #2853 

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

(There are some style changes, sorry for that)

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx for your contribution(s) and involvement!

**Comment by manusa** [comment]
I cannot push to your branch, could you please fix the conflicts (rebase + force push)?

**Comment by jorsol** [comment]
Off-topic... not sure if this works, but to avoid conflicts on CHANGELOG.md probably adding a `.gitattributes` with

```
CHANGELOG.md text merge=union
```
should do the trick.

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
> Off-topic... not sure if this works, but to avoid conflicts on CHANGELOG.md probably adding a `.gitattributes` with
> 
> ```
> CHANGELOG.md merge=union
> ```
> 
> should do the trick.

Not sure if GitHub will automatically resolve merge conflicts using the `.gitattributes` config, but we can give it a spin

**Pull request merged**
