### PR TITLE
chore: make RawCustomResourceOperationsImpl watch methods to return Watch

### PR DESCRIPTION
**Pull request by lburgazzoli**
## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by nicolaferraro — APPROVED** [review]

**Comment by rohanKanojia** [comment]
Could you please add a unit test for this?

**Comment by lburgazzoli** [comment]
@rohanKanojia can you point me to an  test example for watch ?

**Comment by rohanKanojia** [comment]
You can find mock tests for this here: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java#L302

**Comment by lburgazzoli** [comment]
@rohanKanojia can you ahve a look if the latest commit is enough for you ? I have not added a test for every signature

**Comment by rohanKanojia** [comment]
I think it's okay.  Thanks for contributing :+1:

**Comment by lburgazzoli** [comment]
@rohanKanojia can this be merged ?

**Comment by oscerd** [comment]
Let's wait for two reviewers and then we can merge

**Comment by rohanKanojia** [comment]
Yes, I think it can be merged. Let me ping Marc to review

**Comment by rohanKanojia** [comment]
Sorry, I remember now we're blocked on releasing v5.3.1

**Comment by rohanKanojia** [comment]
Once we release v5.3.1. We will merge this

**Comment by manusa** [comment]
> Sorry, I remember now we're blocked on releasing v5.3.1

OK, at first sight this PR doesn't collide with the [outstanding PR](https://github.com/fabric8io/kubernetes-client/pull/3022) waiting to be merged and cherry-picked into the 5.3.x branch, so it won't create additional conflicts.

If it's necessary we can merge it.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by ohbus — APPROVED** [review]

**Pull request merged**
