### PR TITLE
Users and Groups are non-namespaced resources.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by davsclaus** [comment]
I dont think this got merged to the master branch. 

The PR is not auto merged you have to click the button

**Comment by jimmidyson** [comment]
No you have to comment [merge]

**Comment by jimmidyson** [comment]
@davsclaus Automerging stuff for libraries isn't great so we review client & model & use ghprb to merge for us by adding the merge comment.

**Comment by iocanel** [comment]
[merge]

**Pull request merged**
