### PR TITLE
Adding extension for JUnit5 support

### PR DESCRIPTION
**Pull request by piomin**

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@piomin: Could you please add some Javadocs in the added classes about how they fit in the existing mock framework for the benefit of future developers? Also, I would appreciate if you could add some docs about usage too.

**Comment by piomin** [comment]
@rohanKanojia I added javadocs, entry in changelog and information in the readme.md file. I also don't think that error 'ci/circleci: OPENSHIFT_3.11.0 — Your tests failed on CircleCI' has anything with to do with my changes.

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
