### PR TITLE
add missing OpenShiftReadiness.isReadinessApplicable

### LINKED ISSUE #2557: OpenShiftReadiness is missing isReadinessApplicable
When using `Readiness`, there are 2 main methods I use vast majority of time: `isReadinessApplicable` and `isReady`.

Now that OpenShift-related readiness stuff is moved into `OpenShiftReadiness`, I'd like to use it as a drop-in replacement but can't. It only has `isReady`; `isReadinessApplicable` is missing.

### PR DESCRIPTION
**Pull request by Ladicek**
This is to make `OpenShiftReadiness` a drop-in replacement
for `Readiness` for OpenShift users.

Fixes #2557.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by manusa — APPROVED** [review]
thx!

**Review by rohanKanojia — APPROVED** [review]

**Comment by manusa** [comment]
[merge]

**Comment by pjgg** [comment]
Do you know, in which version this method is going to be available?

**Comment by rohanKanojia** [comment]
From commit info it looks like this change is included since 4.13.0 to latest releases

**Comment by pjgg** [comment]
@rohanKanojia

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L85

Seems that was reverted in some merge.

**Comment by manusa** [comment]
> @rohanKanojia
> Do you know, in which version this method is going to be available? , I mean `public` ...
> 
> ```
> protected boolean isReadinessApplicable(HasMetadata item) -> public boolean isReadinessApplicable(HasMetadata item)
> ```

Hi @pjgg 
What's your use-case, why do you need that method to be public?

**Comment by Ladicek** [comment]
We should probably file a separate issue, something like "make the Readiness API public". I've personally used that API on multiple occasions, for example in a test framework that deploys applications and then waits for their readiness. Or in tests that rolls out new applications versions and, again, waits for their readiness.

**Comment by rohanKanojia** [comment]
@Ladicek : I think there is an issue already for this: https://github.com/fabric8io/kubernetes-client/issues/2838

**Comment by Ladicek** [comment]
Nice, didn't know that, thanks!

**Pull request merged**
