### PR TITLE
new api version for PodSecurityPolicies #1968

### LINKED ISSUE #1968: Working with Podsecuritypolicies is broken using k8s1.17 due to api version change
In k8s1.17 PodSecurityPolicies were dropped from the api version "extensions/v1beta1". 
They are now part of the api version "policy/v1beta1" as mentioned here https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

The kubernetes-client in Version 4.7.0 still uses the api version "extensions/v1beta1" for PodSecurityPolicies.

Please support the new api version. 

Thx.

### PR DESCRIPTION
**Pull request by tobexyz**
@rohanKanojia Hi, this is the PR for ticket #1968 please integrate. thx.
Fix #1968

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@tobexyz : Thanks, I think you would also need to generate model again after this change. Issuing a `make` in `kubernetes-model` would do that.

Also, Could you please add a line to CHANGELOG.md regarding this change?

**Comment by manusa** [comment]
> @tobexyz : Thanks, I think you would also need to generate model again after this change. Issuing a `make` in `kubernetes-model` would do that.
> 
> Also, Could you please add a line to CHANGELOG.md regarding this change?

Yes, go build need to be run in order to update the generate binary and the JSON schema(s) that will be consumed by Maven

**Comment by tobexyz** [comment]
> > @tobexyz : Thanks, I think you would also need to generate model again after this change. Issuing a `make` in `kubernetes-model` would do that.
> > Also, Could you please add a line to CHANGELOG.md regarding this change?
> 
> Yes, go build need to be run in order to update the generate binary and the JSON schema(s) that will be consumed by Maven
@manusa : when starting the build with make the go build succeeds bud the maven build returns following error on my machine:
`
[ERROR] Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.23:generate (default) on project kubernetes-model: Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.23:generate failed: Path not present: kubernetes_apimachinery_pkg_runtime_ImageRawExtension -> [Help 1]
`
what do I wrong?

**Comment by manusa** [comment]
Let me check

**Comment by manusa** [comment]
Removing the v1beta1 class dependencies also removes some "transitive" dependency classes that are used by other parts of the model, they have to be added. Let me check which of them are needed.

**Comment by manusa** [comment]
@tobexyz , sorry but I had to open a different pull request, the extent of the required changes is too much.

**Comment by tobexyz** [comment]
> @tobexyz , sorry but I had to open a different pull request, the extent of the required changes is too much.

ok, no problem. Thank you. Is this PR needed any more, or is the fix fully covered by PR  #1986?

**Comment by manusa** [comment]
> > @tobexyz , sorry but I had to open a different pull request, the extent of the required changes is too much.
> 
> ok, no problem. Thank you. Is this PR needed any more, or is the fix fully covered by PR #1986?

Not needed any more, you may close it.

**Comment by tobexyz** [comment]
this PR is covered by PR #1986.

**Pull request closed without merging**
