### PR TITLE
StatefulSet handler and readiness check

### PR DESCRIPTION
**Pull request by pavolloffay**
This is improved version of https://github.com/fabric8io/kubernetes-client/pull/769 with readiness check for StatefulSet.

I need this in arquillian-cube to test our k8s deployments.

@jimmidyson @jstrachan could you please review?

### CODE REVIEW

**Comment by pavolloffay** [comment]
cc @iocanel

**Comment by iocanel** [comment]
add to whitelist

**Comment by pavolloffay** [comment]
@iocanel when do you plan to cut a new release? 

I need this change in arq-cube. Can I create a PR to arq-cube with updated version of this dependency? It will bump from 2_3 to 2_5.

**Comment by pavolloffay** [comment]
And thanks for merging :+1:

**Comment by iocanel** [comment]
I think that @jstrachan is already trying to get a release out, but I we hit some issues with the release.

**Pull request merged**
