### PR TITLE
Update Tekton Pipeline model to 0.17.0

### LINKED ISSUE #2534: Tekton extension does not support When expressions
When expressions are not supported. Updating to the latest Tekton Pipeline will update model

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2534

Adds
- WhenExpressions
- Optional workspaces

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@Fabian-K : Could you please review this whenever you get some time?

**Review by rohanKanojia — APPROVED** [review]

**Review by Fabian-K — APPROVED** [review]
LGTM, thanks @jeffmaury!

**Comment by rohanKanojia** [comment]
@Fabian-K @jeffmaury : Thanks to your awesome contributions, this extension is getting better and better! I think we now have pretty good/complete support with respect to Tekton REST API. 

I think it would be awesome if we had some cool blog posts on how this extension is becoming useful for Java devs who want to access Tekton API. Does anyone have any plans to write a blog post about it?

**Comment by jeffmaury** [comment]
Not sure I have time to do it but I can write a blog post about the latest changes in our IntelliJ Tekton plugin that uses the Tekton F8 client.

**Review by manusa — APPROVED** [review]
LGTM, thx!!

**Comment by manusa** [comment]
[merge]

**Comment by Fabian-K** [comment]
> I think it would be awesome if we had some cool blog posts on how this extension is becoming useful for Java devs who want to access Tekton API. Does anyone have any plans to write a blog post about it?

Agree, this would be really cool. So far I never wrote a blog post and tbh I don´t think this will change in the near future. If you plan to do something and need feedback let me know :)

**Comment by rohanKanojia** [comment]
I had written a blog post a week ago about it: https://itnext.io/access-tekton-pipelines-in-java-using-fabric8-tekton-client-bd727bd5806a . Maybe you can provide feedback on this :-) .

But to be honest, I'm not really a tekton guy; I'm not using tekton for anything. I'm not sure this blog post covers use cases regular tekton users might be looking for.

**Pull request merged**
