### PR TITLE
Fix #2823: Reduced number of duplicate literals and continue statements

### LINKED ISSUE #2823: Reduce the number of duplicate literals and number of break and continue statements
- [ ] Make this member "protected" 
https://github.com/fabric8io/kubernetes-client/blob/5df8dae7fa31b009fe8971bacb50dccd63a47b6d/crd-generator/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java#L77
- [ ]  Defining a constant instead of duplicating literals  
https://github.com/fabric8io/kubernetes-client/blob/5df8dae7fa31b009fe8971bacb50dccd63a47b6d/crd-generator/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java#L80-L94
- [ ] Reduce the total number of break and continue statements  
https://github.com/fabric8io/kubernetes-client/blob/5df8dae7fa31b009fe8971bacb50dccd63a47b6d/crd-generator/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java#L111-L131
[Sonarcloud.io issue page link](https://sonarcloud.io/project/issues?assigned=false&fileUuids=AXeKpnxFmR8wXoZXwwEb&id=fabric8io_kubernetes-client&resolved=false)

@iocanel 
I couldn't find this issue on github, so opened one here

### PR DESCRIPTION
**Pull request by gandalf0151**
## Description  
- Define a constant instead of duplicating literals "string" and "number"
- Changed member access modifier to "protected"
- Reduce the total number of break and continue statements in loop to use at most one
Fixes #2823 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by gandalf0151** [comment]
Hi @oscerd 
Thanks for taking time to review the patch
I'm a beginner in Open Source
I built the project on my local machine using Java 8. It was successful.
I don't understand why it's failing here

**Comment by gandalf0151** [comment]
@oscerd PTAL
Thanks

**Comment by oscerd** [comment]
I restarted the job for javadoc and sonar.

**Review by oscerd — APPROVED** [review]

**Review by metacosm — APPROVED** [review]
LGTM

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by gandalf0151** [comment]
@oscerd @metacosm @manusa @rohanKanojia
Thanks a lot for taking time to review and merge this PR

**Pull request merged**
