### PR TITLE
Added OSGi metadata to BatchAPIGroupExtensionAdapter

### LINKED ISSUE #2000: Unable to create jobs in OSGi environments
I am using the kubernetes-client library in an OSGi container. I am unable to submit a job due to the following error:

```
[PromiseFactory,pool-4-thread-2] WARN  c.a.s.n.m.ServiceBusCreationListener - Namespace ns-team-rmuntean1 was not succesfully provisioned on cluster ethos11-stage-nld2
java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.BatchAPIGroupClient
	at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:130)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.batch(DefaultKubernetesClient.java:313)
	at io.fabric8.kubernetes.client.osgi.ManagedKubernetesClient.batch(ManagedKubernetesClient.java:379)
	at com.example.Foo.lambda$apply$29(Foo.java:94)
	at org.osgi.util.promise.DeferredPromiseImpl$Submit.run(DeferredPromiseImpl.java:658)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I have tracked this down to missing OSGi annotations in `BatchAPIGroupExtensionAdapter`

### PR DESCRIPTION
**Pull request by rombert**
Fix #2000

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@rombert : Thanks a lot for your contribution :+1: . Could you also please add a line to CHANGELOG.md regarding this change?

**Comment by rohanKanojia** [comment]
let's merge this since we have to release today. We'll update changelog ourselves :-)

**Comment by rohanKanojia** [comment]
[merge]

**Comment by rombert** [comment]
Thanks a lot for the quick review and merge @oscerd , @rohanKanojia and @manusa !

I submitted a PR recording the fix in the changelog - #2005

**Pull request merged**
