### PR TITLE
Fix #1371: Add example code for Job Controller

### LINKED ISSUE #1371: Add an example for Job Controller
The repo currently has an example for Cronjob Controller. It would be nice to have an example code for [Job Controller](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) as well.

### PR DESCRIPTION
**Pull request by kolorful**
The repo currently has an example for Cronjob Controller. It would be nice to have an example code for [Job Controller](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) as well.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by kolorful** [comment]
Fixed license and updated CHANGELOG, not sure if format is correct.

**Comment by kolorful** [comment]
Done!

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
