### PR TITLE
ci: fix sonar issue

### PR DESCRIPTION
**Pull request by manusa**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
Umm, why didn't we get any sonar report comment like we used to?

**Comment by manusa** [comment]
> Umm, why didn't we get any sonar report comment like we used to?

That's really odd

image

https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client&pullRequest=3109

**Comment by manusa** [comment]
For some reason (probably actions taken to mitigate the CodeCov security issue) the organization was no longer bound, maybe that's why we started to get failures.

**Comment by manusa** [comment]
Anyway, I'm merging this, since it fixes the analysis publication

**Comment by manusa** [comment]
Seems to be back

https://github.com/fabric8io/kubernetes-client/pull/3099#issuecomment-839830437

**Pull request merged**
