### PR TITLE
use v1 instead of v2alpha1 for Job api

### PR DESCRIPTION
**Pull request by popyy0101**
Related #763

### CODE REVIEW

**Comment by joan38** [comment]
We need to merge https://github.com/fabric8io/kubernetes-model/pull/215 before or it will break

**Comment by joan38** [comment]
Can anyone review this? It's been open since 13 Jun.

I understand the maintainers are busy and do it as volunteer, that's why we fix stuff ourself here.
If the number of maintainers is not enough then we should probably look in for new volunteer maintainer?

Kubernetes is a project moving fast, I don't think it's reasonable to have a client laying multiple versions beind.

Cheers

**Comment by joan38** [comment]
This can be closed now as it's been superseded by https://github.com/fabric8io/kubernetes-client/pull/827

**Comment by oscerd** [comment]
Closed.

**Comment by oscerd** [comment]
Thanks @popyy0101

**Pull request closed without merging**
