### PR TITLE
Add in extensions API group, just jobs for now

### LINKED ISSUE #204: add support for the new Jobs resources in kubernetes

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #204

### CODE REVIEW

**Comment by jimmidyson** [comment]
@iocanel It's a bit hard to review with all the changes but if you want to take a look through the interesting ones & see what you think that would be appreciated. This is the basis for api groups going forward so want to get it semi-right.

**Comment by jimmidyson** [comment]
@iocanel OK this is it now. We can add in `withVersion` later, for now this seems good to go. Review when you get a chance please.

**Comment by jimmidyson** [comment]
@iocanel Can you take a last look at this & merge if you think it's OK before anything else? This is pretty intrusive & I don't want to have to rebase many more times :(

**Comment by iocanel** [comment]
Rebasing is a bitch isn't it?

I am on it!

**Comment by jimmidyson** [comment]
Yep... here we go again...

**Comment by jimmidyson** [comment]
Rebased

**Comment by iocanel** [comment]
[merge]

**Comment by jimmidyson** [comment]
Thanks @iocanel!

**Pull request merged**
