### PR TITLE
ci: Pipeline to run E2E tests for each httpclient implementation

### PR DESCRIPTION
**Pull request by manusa**
## Description

ci: Pipeline to run E2E tests for each httpclient implementation

Runs the tests based on the latest available SNAPSHOT builds.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Review by shawkins — APPROVED** [review]
LGTM

Are you good with the dependency approach, or would you rather property drive the client selection?

**Comment by manusa** [comment]
> or would you rather property drive the client selection?

I'm not following on this, could you elaborate?

With the current approach, for each new client we'll need to create a new profile and add the entry in the CI pipeline matrix. However, the rest of the workflows are completely unaffected by these changes (for example, the JDK dependency is only added when needed).

**Comment by manusa** [comment]
I think this moves away from what we discussed other times. I thought that the agreement was:
- httpclient-okhttp is provided as a default with the kubernetes|openshift-client modules
- If the classpath contains an additional entry for a single httpclient (e.g. httpclient-jdk), this one is selected and a warning is logged
- If the classpath contains 2 or more additional entries for alternate httpclient, an error is thrown

If the previous spec is fulfilled, the exclusion in the test is not really necessary. However, for the sake of "unitness" and peace of mind, I like to keep the redundant exclusion. Other tests can take care of validating the httpclient module selection spec.

**Comment by manusa** [comment]
> such as in a given kubernetes-test being able to declare that it's a HttpClient regression test

If the purpose is solely for internal testing, I don't think that this should be implemented in our code. Maven profile configuration should be enough for this use-case and would prevent coupling production code with testing environment preparation.

Anyway, let's move forward with the current pipeline and reevaluate later on.

**Pull request merged**
