### PR TITLE
Fix the ability to load Deployment that uses extensions/v1beta1

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by oscerd** [comment]
Ok to test

**Comment by iocanel** [comment]
... also it might make sense to evaluate the possible breakage on downstream projects if we actually go for a proper fix.

**Comment by geoand** [comment]
@iocanel I am all for a proper fix, but I can't really comment on the effects downstream.
That said, should we decide to pursue such a fix, I am willing to work on it

**Comment by geoand** [comment]
@iocanel could you point me to the "problematic" code you mentioned in your comment?

**Comment by iocanel** [comment]
@geoand: https://github.com/fabric8io/kubernetes-client/blob/df459cb490cb918500a7e92542ea57c03ff3d0c5/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L889

**Comment by geoand** [comment]
@iocanel Thanks, I'll have a look!

**Comment by geoand** [comment]
I updated the test to be more accurate in testing the fix

**Comment by geoand** [comment]
@iocanel FWIW, After debugging the code I found that it's not https://github.com/fabric8io/kubernetes-client/blob/df459cb490cb918500a7e92542ea57c03ff3d0c5/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L889, that changes apiGroup (the method is executed  does not make any changes the check at: https://github.com/fabric8io/kubernetes-client/blob/df459cb490cb918500a7e92542ea57c03ff3d0c5/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L923 does  not pass - since `apiGroupVersion` is null).

What happens is that the apiGroup is hardcoded at: https://github.com/fabric8io/kubernetes-client/blob/e8e171d82d7b974a8c3356c1061da5277717444b/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java#L54

**Comment by iocanel** [comment]
Damn you @geoand! It was too convinient for me to blame someone else for it, why did u have to dig around ?

**Comment by geoand** [comment]
Regardless, I will keep digging  into this and see if we can improve the situation :)

**Comment by iocanel** [comment]
Well, even if its not the root cause of the issue, IMHO the fact that it proactively mutates resources complicates things. 

However, its a fight that we shall give another day. 

So, I'll approve this.

**Comment by geoand** [comment]
Thanks @iocanel  for your assistance with this!

**Pull request merged**
