### PR TITLE
Add support for ControllerRevision

### PR DESCRIPTION
**Pull request by kunal-kushwaha**
#1380

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : is this still a WIP?

**Comment by kunal-kushwaha** [comment]
> @kunal-kushwaha : is this still a WIP?

@rohanKanojia: Yes

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: Thank You, I really appreciate it.

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : no problem, Sorry I couldn't look into this earlier. I'm a lazy reviewer :-)

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: It's all good 👍, would look into this after my exams next week.

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : no problem, good luck with your exams :+1:

**Comment by rohanKanojia** [comment]
[merge]

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: Got unresolved conflicts in kube-validation-schema.json. 
I've opened a new PR to resolve this.  
https://github.com/fabric8io/kubernetes-client/pull/1777

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : But I fixed those conflicts. I don't think a new PR is needed. Am I missing something?

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: Can you check again? I think few are left in kube-validation-schema.json
I just rebased with master and got the conflicts.

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : oh, yeah. I'm able to see them on master :disappointed:

**Pull request merged**
