### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joan38**
withMasterUrl instead of masterUrl

### CODE REVIEW

**Comment by joan38** [comment]
Any news on that?

**Comment by joan38** [comment]
Is this project abandonned?

**Comment by oscerd** [comment]
Looks good to me

**Comment by oscerd** [comment]
test this please

**Comment by oscerd** [comment]
retest this please

**Comment by oscerd** [comment]
ok to test

**Comment by joan38** [comment]
Cheers @oscerd
Are the tests ok? Do we really need the tests to pass for this readme change?

**Comment by oscerd** [comment]
It's the only way to merge. @iocanel @jimmidyson can you start the test ? Then we can merge.

**Comment by joan38** [comment]
@oscerd ok I see

**Comment by iocanel** [comment]
ok to test

**Comment by iocanel** [comment]
@oscerd: added you to the admin list, so hopefully you will be able to 'ok to test' now.

@joan38: Thanks a lot!

**Comment by joan38** [comment]
@iocanel and @oscerd great thanks.
I'll try to find some time to contribute the CronJob extension support.

**Pull request merged**
