### PR TITLE
feat(openshift): Support OpenShift 4.x API Groups. Fixes #1631

### LINKED ISSUE #1631: Support OpenShift 4.x
It seems that OpenShift 4 is not supported,  I get the following error when creating a new project:

Code snippet
==========
```
            client.projectrequests().createNew().
                    withNewMetadata().
                    withName(name).
                    endMetadata().
                    done();
```

Error
====

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.cluster-01.devcluster.openshift.com:6443/oapi/v1/projectrequests. Received status: Status(apiVersion=v1, code=404, details=null, kind=Status, message=null, metadata=null, reason=null, status=null, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:503)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:442)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:406)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:365)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:234)
	at io.fabric8.openshift.client.dsl.internal.ProjectRequestsOperationImpl.create(ProjectRequestsOperationImpl.java:74)
	at io.fabric8.openshift.client.dsl.internal.ProjectRequestsOperationImpl.lambda$createNew$0(ProjectRequestsOperationImpl.java:89)
	at io.fabric8.openshift.api.model.DoneableProjectRequest.done(DoneableProjectRequest.java:27)
```

### PR DESCRIPTION
**Pull request by gastaldi**
This PR aims to support OpenShift 4.x endpoints Fixes #1631

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@gastaldi : Is that it? Does this cover full support for Openshift 4.x or just your use case?

**Comment by gastaldi** [comment]
@rohanKanojia that partially covers my use case for now. I am still testing the full process and checking if nothing breaks in 3.11. I'll remove the WIP from the title when that's done

**Comment by gastaldi** [comment]
[test]

**Comment by gastaldi** [comment]
@rohanKanojia there you go, these were the changes I had to do in kubernetes-client to support creating a project and applying templates in OpenShift 4

**Comment by gastaldi** [comment]
Tests are still failing, need to check that: 

```
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.64 s <<< FAILURE! - in io.fabric8.openshift.TemplateIT
[ERROR] delete(io.fabric8.openshift.TemplateIT)  Time elapsed: 0.243 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://127.0.0.1:8443/apis/template.openshift.io/v1/namespaces/itest-da01e737/templates. Message: the API version in the data (v1) does not match the expected API version (template.openshift.io/v1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (v1) does not match the expected API version (template.openshift.io/v1), metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.openshift.TemplateIT.init(TemplateIT.java:78)

[ERROR] get(io.fabric8.openshift.TemplateIT)  Time elapsed: 0.114 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://127.0.0.1:8443/apis/template.openshift.io/v1/namespaces/itest-da01e737/templates. Message: the API version in the data (v1) does not match the expected API version (template.openshift.io/v1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (v1) does not match the expected API version (template.openshift.io/v1), metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.openshift.TemplateIT.init(TemplateIT.java:78)

[ERROR] list(io.fabric8.openshift.TemplateIT)  Time elapsed: 0.113 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://127.0.0.1:8443/apis/template.openshift.io/v1/namespaces/itest-da01e737/templates. Message: the API version in the data (v1) does not match the expected API version (template.openshift.io/v1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (v1) does not match the expected API version (template.openshift.io/v1), metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.openshift.TemplateIT.init(TemplateIT.java:78)

[ERROR] load(io.fabric8.openshift.TemplateIT)  Time elapsed: 0.073 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://127.0.0.1:8443/apis/template.openshift.io/v1/namespaces/itest-da01e737/templates. Message: the API version in the data (v1) does not match the expected API version (template.openshift.io/v1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (v1) does not match the expected API version (template.openshift.io/v1), metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.openshift.TemplateIT.init(TemplateIT.java:78)

```

**Comment by gastaldi** [comment]
Replaced by https://github.com/fabric8io/kubernetes-client/pull/1644

**Pull request closed without merging**
