### PR TITLE
Add integration test for the karaf platform integration.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by iocanel** [comment]
damn you intellij

**Comment by jimmidyson** [comment]
Loser.

**Comment by iocanel** [comment]
Jimmi

**Comment by iocanel** [comment]
[merge]

**Comment by jimmidyson** [comment]
It's actually test failures... https://fabric8-ci.fusesource.com/job/kubernetes-client-pullreq-merge/166/console

**Comment by iocanel** [comment]
[merge]

**Comment by iocanel** [comment]
Yeah, we can't create a repo, if we don't install the artifacts to the local repo. Updated the pr and mrg jobs to use "mvn clean install" and retrying now.

**Comment by jimmidyson** [comment]
[merge]

**Pull request merged**
