### PR TITLE
fix bug:  in.available() always return 0

### PR DESCRIPTION
**Pull request by zxbu**
issues：https://github.com/fabric8io/kubernetes-client/issues/883

### CODE REVIEW

**Comment by asacbp** [comment]
hi, what's missing on this pull request to land and be wrapped into a release? would be nice to get log watch working on 3.0 thanks.

**Comment by oscerd** [comment]
@iocanel and @jimmidyson WDYT?

**Comment by asacbp** [comment]
@iocanel how can we help on #872 ? Test whether it fixes the log streaming issue this PR was made for originally?

**Comment by iocanel** [comment]
@asacbp: yeah, some feedback on #872 is more than welcome.

**Comment by iocanel** [comment]
@asacbp: #872 is now merged to master, so I am closing this one. If you feel there are still issues, please reopen.

**Comment by asacbp** [comment]
this missed 3.0.2,right?

**Comment by asacbp** [comment]
quick heads up that 3.0.3 release works great for log watch. thanks a lot @iocanel !

**Comment by iocanel** [comment]
@asacbp: Great news! Cheers!

**Pull request closed without merging**
