### PR TITLE
Exclude unexported fields from JSON schema

### LINKED ISSUE #3190: CRD Schema Generator - Ignore Non-Exported Fields
In certain CRD structs in Go, a developer may choose to not to have a field be part of the schema by using "-" as the JSON field name. Currently, the generator does not handle this case and improperly generates a JSON Schema that has this as a field name, this subsequently fails during JSON Schema to POJO generation as a field should not be called "-".

A concrete example of this use can be found in the RolloutSpec for Argo Rollouts: https://github.com/argoproj/argo-rollouts/blob/master/pkg/apis/rollouts/v1alpha1/types.go#L36-L37

The generator should be made aware of this functionality and not export these fields to the JSON Schema.

### PR DESCRIPTION
**Pull request by ryantse**
## Description

Fixes #3190 by ignoring fields contained in structs with JSON name "-" from the generated JSON schema.

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by ryantse** [comment]
@oscerd / @rohanKanojia: Can we get this merged?

**Comment by rohanKanojia** [comment]
I think it'll get merged soon. Let's wait for Marc's approval.

**Comment by ryantse** [comment]
@manusa: Could you take a look at this patch? Thanks in advance.

**Comment by ryantse** [comment]
@manusa / @rohanKanojia: Sorry to keep pinging, but I am waiting for this merge to use internally for my use case. Any chance we can get this merged ASAP?

**Comment by manusa** [comment]
Hi, we are going to run the extensions generator to see if there's any direct impact on our currently generated classes.

**Comment by rohanKanojia** [comment]
I checked and this change doesn't affect our current schema. It's safe to merge. I've created https://github.com/fabric8io/kubernetes-client/pull/3203 to add extension generators to `generateModel.sh`

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
