### PR TITLE
fix #3364: removing boilerplate methods from the resourcehandler

### LINKED ISSUE #3364: resource and resourceList methods
resource method offers quite a bit more logic stemming from NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicable over the regular HasMetadataOperation - deletingExisting, acceptVisitors, createOrReplaceAnd, the VisitFromServerWritable/CascadingDeletable interface, etc.

With the refactorings related to #3327 it would be straight-forward to express resource(item) as resources(item.getClass()).withItem(item) - but that would provide a regular ResourceOperationImpl / HasMetadataOperation, not a NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicable.  The major functional difference is the expectation that inNamespace will update the item's namespace as well.

NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicable is of course conflicting with DryRunnable and Namespaceable - so ResourceOperationImpl can only partially implement it.

My question is - why is extra functionality (like createOrReplaceAnd) only available when using the resource method?  What of it (like deletingExisting, acceptVisitors) is actually still needed?  With a few minor changes I think it would eliminate the need for NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl and the related specialized handler logic.

### PR DESCRIPTION
**Pull request by shawkins**
## Description
This attempts to make all usage of resource operations regular.  It requires splitting the base operationcontext from the derived bits so that newInstance works with just the base operationcontext.  There are specific adjustments in places to the operationcontext passed in, such as removing the name when applicable: https://github.com/fabric8io/kubernetes-client/compare/master...shawkins:afteroptions?expand=1#diff-5f5b631eb85dc54234df36ce4b410bf1f1095e571a3f030d63e5a7863167d420R289

There were a couple of minor things addressed such as OpenShiftNamespaceVisitXXX needed newInstance methods in the base class to appropriately propagate the openshift specific handling, and another where the context values for the container id and the log wait timeout are not being passed https://github.com/fabric8io/kubernetes-client/compare/master...shawkins:afteroptions?expand=1#diff-8f439f4875edabad7096e999159b8c1cdabcbe150c9b9f46606505269de5b9e6L317

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by shawkins** [comment]
After this it will be straight-forward to remove the deprecated waitable properties.

**Review by manusa — APPROVED** [review]
There are some test failures, everything else LGTM

**Comment by shawkins** [comment]
> There are some test failures, everything else LGTM

Sorry, I hadn't noticed that after the late change to move Readiness onto the Config - it needed to be marked as JsonIgnore.  That seems to be the most natural place given the OpenShiftConfig override.

**Comment by manusa** [comment]
> That seems to be the most natural place given the OpenShiftConfig override.

Agreed

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
