### PR TITLE
Informer watch status

### PR DESCRIPTION
**Pull request by shawkins**
## Description
Adding a SharedInformer isRunning method, with some additional minor cleanups.  As best as I can determine if this returns true, the informer should still expect to receive events.  This does not address using the SharedInformerEventListener or some other mechanism to forward any possible abnormal termination exception to.

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by shawkins** [comment]
@oscerd @rohanKanojia A related question is what is the lifecycle expectation of a SharedInformer - can you call run after stop and expect it to come back to life?  As things are currently coded, I don't think that would work.  Should there be a check in run() for stopped?

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@shawkins : What do you mean by "Should there be a check in run() for stopped?" We already seem to have a check in run() to avoid running it again once it's run. 

https://github.com/fabric8io/kubernetes-client/blob/c06d9908aa4ac8a22ae47e7ecb66757f6bf56658/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java#L137-L142

Is your use case to restart informers?

**Comment by shawkins** [comment]
@rohanKanojia I'm asking if stop puts the informer into a terminal state.

If you do: 
informer.run();
informer.run(); // that is a noop

If you do: 
informer.run();
informer.stop();
informer.run(); // what is the expectation - noop, exception, restart?

**Comment by rohanKanojia** [comment]
I think we should not expect users to NOT `run()` again once informer is started. We should handle it in a separate issue/pr.

**Comment by shawkins** [comment]
Captured as #3050

**Comment by akram** [comment]
@shawkins  I don't see this PR as way to address the case where I want to stop the informer.
I would expect that stopping all the informers would stop also the watch.
On the other hand, I would expect that starting informers with the watch that has been stopped/closed already would just restart a new watch.

Otherwise, I don't see a way to have clean state on stop.

What do you think?

**Comment by shawkins** [comment]
> @shawkins I don't see this PR as way to address the case where I want to stop the informer.

Sorry we may have our wires crossed - I don't mean that this pr is a replacement for #3029 - only that it's making changes around the notion of stopping in some of the same classes as that pr.

I'm advocating that we get #3029 committed next, so that I can continue with other changes without much conflict - https://github.com/fabric8io/kubernetes-client/pull/3008#issuecomment-827112497

**Comment by shawkins** [comment]
I'm going to close this pr for a bit - I think some of these changes could be refined in a broader context.

**Comment by shawkins** [comment]
After more review the changes do seem valid.  I'll follow-up with a separate pr https://github.com/shawkins/kubernetes-client/pull/1 with further refinement around closing.

**Comment by manusa** [comment]
I tried, but I can't rebase your branch and fix the conflicts. Could you please resolve conflicts so we can merge?

**Comment by shawkins** [comment]
@manusa it's written as a follow-up to this pr, so it's dependent upon these changes.  Are you asking to include those changes with this pr?

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by manusa** [comment]
I just meant to rebase this branch onto master and resolve the changelog conflicts.

**Comment by shawkins** [comment]
resolved the readme conflict

**Comment by manusa** [comment]
Relates to: #2010

**Pull request merged**
