### PR TITLE
fix(#1273): customResources can't be used with Cluster scoped CRDs.

### LINKED ISSUE #1273: customResources can't be used with Cluster scoped CRDs.
Custom resources can have scope set to "Cluster".. CustomResourceOperationsImpl doesn't override isResourceNamespaced from BaseOperation. Because of this no resource create/update actions are possible.

### PR DESCRIPTION
**Pull request by mgorniew**
Simple change to fix #1273. Scope from CRD will be used. Method CustomResourceOperationsImpl.isResourceNamespaced will return true only if scope is set to "Namespaced.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by oscerd** [comment]
There are troubles on CircleCI

**Comment by rohanKanojia** [comment]
[merge]

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
