### PR TITLE
Rootpaths

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by iocanel** [comment]
[merge]

**Comment by jimmidyson** [comment]
Could we move `RootPaths` in kubernetes-model into model package? No need for separate package for root.

**Comment by iocanel** [comment]
No problem with me.

**Comment by jimmidyson** [comment]
Fixed in kubernetes-model. I'm not working today (as you can see ;)) so would you be able to release the model 1.0.2 & update client accordingly?

**Pull request merged**
