### PR TITLE
fixes portforwarding when there are more services with the same name in multiple namespaces

### PR DESCRIPTION
**Pull request by BJMg**
I encountered an incorrect port forwarding (on service) when I had more than one namespace. In each namespace there were services with the same name. When I called portForward on service it randomly chose one of these services instead of the service with current namespace.
This pull request should remedy this behaviour.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@BJMg : Could you please add a line to CHANGELOG regarding this?

**Comment by BJMg** [comment]
> @BJMg : Could you please add a line to CHANGELOG regarding this?

Thanks for accepting. It is done.

**Comment by rohanKanojia** [comment]
There is a minor conflict, Could you please resolve it? I think we are good to merge after that.

**Pull request merged**
