### PR TITLE
Upgrade to okhttp 3.6

### PR DESCRIPTION
**Pull request by jimmidyson**
@iocanel @chirino Would appreciate quick review please to make sure I haven't done anything stoopid.

### CODE REVIEW

**Comment by oscerd** [comment]
Sorry @jimmidyson . You were faster

**Comment by jimmidyson** [comment]
@oscerd Like a :racehorse: ...

**Comment by iocanel** [comment]
For starters, I find it extremely annoying that we can't coordinate ourselves and we work on the same things.

Now, I find it even more annoying that you beat me to it. :-)

**Comment by iocanel** [comment]
[merde]

**Comment by iocanel** [comment]
[merge]

**Pull request merged**
