### PR TITLE
fix: Use correct plural form in OpenshiftRole

### LINKED ISSUE #1473: OpenshiftRoles can't be listed due to wrong API endpoint URL
Version used: `v4.2.0`

Listing OpenshiftRoles fails with the following exception:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://<cluster-url>:8443/apis/authorization.openshift.io/v1/namespaces/dsimansk/openshiftroles?labelSelector=%21xtf.cz%2Fkeep. Message: Forbidden! User rhoarqe/api-ocp-dynamic-rhoar:8443 doesn't have permission. openshiftroles.authorization.openshift.io is forbidden: User "rhoarqe" cannot list openshiftroles.authorization.openshift.io in the namespace "dsimansk": no RBAC policy matched.
	at io.vertx.openshift.jdbc.JdbcIT.initialize(JdbcIT.java:46)
```

The correct endpoint is: `/apis/authorization.openshift.io/v1/namespaces/<namespace>/roles` without the `openshift` prefix.

From the http client 
```
INFO: <-- 403 Forbidden https://<cluster-url>:8443/apis/authorization.openshift.io/v1/namespaces/dsimansk/openshiftroles?labelSelector=%21xtf.cz%2Fkeep (125ms)
```

It works fine for OpenShiftRoleBinding
```
INFO: <-- 200 OK https://<cluster-url>:8443/apis/authorization.openshift.io/v1/namespaces/dsimansk/rolebindings?labelSelector=%21xtf.cz%2Fkeep (128ms)
Apr 02, 2019 11:17:26 AM okhttp3.internal.platform.Platform log
```

### PR DESCRIPTION
**Pull request by dsimansk**
Fix #1473

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by rohanKanojia** [comment]
@dsimansk : Hi, Thanks for this fix. You forgot to add license header in the second file. Also, would be awesome if you could add a line to CHANGELOG regarding this change :-)

**Comment by dsimansk** [comment]
@rohanKanojia updated, thanks for the heads up.

**Comment by rohanKanojia** [comment]
@dsimansk : Thanks :+1:

**Comment by rohanKanojia** [comment]
[merge[

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
