### PR TITLE
Move Sonar analysis to Java 11

### PR DESCRIPTION
**Pull request by jorsol**
## Description

Fix warning "The version of Java (1.8.0_275) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 11."

https://sonarcloud.io/documentation/appendices/move-analysis-java-11/

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

<!--

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by rohanKanojia** [comment]
Building project with Java 8 and then running analysis on Java 11 seems a bit weird. Maybe we should switch this entire job to work with Java 11? WDYT?

**Comment by jorsol** [comment]
> Building project with Java 8 and then running analysis on Java 11 seems a bit weird. Maybe we should switch this entire job to work with Java 11? WDYT?

It's possible to run the build on one version and the scan on another version (https://community.sonarsource.com/t/re-move-to-java-11-java-8-deprecated/25275/2), but yes, I think it's recommended to switch the entire job to Java 11.

**Comment by manusa** [comment]
I think reports won't be affected for one approach or the other.
Anyway, workflow looks less complicated this way (everything Java 11)

**Review by manusa — APPROVED** [review]
LGTM, thank you!

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
