### PR TITLE
deps: bump OkHttp to 3.14.9

### PR DESCRIPTION
**Pull request by manusa**
## Description
deps: bump OkHttp to 3.14.9

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
We need a 3.14.9 bundle too.

**Comment by manusa** [comment]
> We need a 3.14.9 bundle too.

I upgraded the ServiceMix bundle dependency to 3.14.1_2, but it's based on 3.14.1. I'm unsure of the behavior this might cause.

**Comment by oscerd** [comment]
It might work, but some of the problems will show up only in OSGi runtime at runtime.. The best solution is going ahead with this PR. We'll need to add a 3.14.9 bundle to the next Servicemix bundles release and then upgrade here.

**Comment by mkdev0101** [comment]
Any plans to upgrade to 4.10.x which has fix for CVE PRISMA-2022-0239 (https://github.com/square/okhttp/issues/6738) ?

**Review by sunix — APPROVED** [review]

**Comment by manusa** [comment]
Bundle version has been updated too ([3.14.9_1](https://repo1.maven.org/maven2/org/apache/servicemix/bundles/org.apache.servicemix.bundles.okhttp/3.14.9_1/))

**Comment by manusa** [comment]
Considering Quarkus no longer depends on the OkHttp client (at least for production), we should move forward to use OkHttp 4 instead.

Closing this PR, and #5134 in favor of #2632

**Pull request closed without merging**
