### PR TITLE
fix: properly return full resource name for resources with empty group

### LINKED ISSUE #3712: `HasMetadata.getFullResourceName` is incorrect when group is empty (which happens for "historic" resources such as `Pod`)
### Describe the bug

`getFullResourceName` returns `pods.` instead of `pods` for example.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

Call `getFullResourceName` on a resource with an empty group.

### Expected behavior

Proper full resource name.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22.3@latest

### Environment

macOS

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by metacosm**
Fixes #3712

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by rohanKanojia — APPROVED** [review]

**Review by shawkins — APPROVED** [review]
The changes look good.  A test would be great.

**Comment by rohanKanojia** [comment]
test seems to be failing:
```
Error:  Failures: 
Error:    HasMetadataTest.fullResourceNameShouldConcatenatePluralAndGroup:41 expected: <women.fabric8.io> but was: <womans.fabric8.io>
[INFO] 
Error:  Tests run: 94, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by metacosm** [comment]
Yes, working on it…

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
