### PR TITLE
Load request config when intercepting request

### PR DESCRIPTION
**Pull request by lulf**
This fixes an issue where the request config given in withRequestConfig is not applied.

### CODE REVIEW

**Comment by piyush1594** [comment]
Hey @lulf 

Thanks for the PR. Can you please add this to CHANGELOG.md and also can you please refer to the issue which gets resolved by this. Thanks

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
[merge]

**Comment by oscerd** [comment]
[merge]

**Comment by lulf** [comment]
@piyush1594  See #1038

**Comment by piyush1594** [comment]
Thanks @lulf

**Pull request merged**
