### PR TITLE
Fix #3372: Add generatedTypesPrefix option to Model Generator

### LINKED ISSUE #3372: Remove hardcoded check in schema generator to resolve types
During JSONSchema2Pojo upgrade, generators were updated to generate two different kind of fields `javaType` and `existingJavaType`. Right now I see a hardcoded check to distinguish a type (whether it's `javaType`(to be generated) or `existingJavaType`(already existing)):

https://github.com/fabric8io/kubernetes-client/blob/fca47f8950f60617db32e66c70c59c34807ffb7d/generator/pkg/schemagen/generate.go#L290-L296

This forces anyone using the generator to have its package prefixed with `io.fabric8`; otherwise, all types would be generated as `existingJavaType`. We should make our generator more generic so that users can pass this parameter

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #3372 
Instead of assuming a hardcoded value "io.fabric8", allow this parameter
to be configured from the client which will be using the generator in
order to be more flexible in terms of generate model package naming.

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [X] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by manusa** [comment]
The commit message (+PR title) is really misleading should probably changed to:
`fix:  fabric8io#3372 Add generatedTypesPrefix option to Model Generator`

**Comment by manusa** [comment]
Why is this breaking?

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by rohanKanojia** [comment]
If someone is using `github.com/fabric8io/kubernetes-client/generator/pkg/schemagen` as go module in their project for generating schema, they need to add a package prefix to `schemagen.GenerateSchema` call

**Pull request merged**
