### PR TITLE
Fix rolling update error in FullExample according to PR-2272 (#2555)

### LINKED ISSUE #2555: Error occurred while running FullExample
Running with version 4.12.0, full error stack:

```shell script
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.dsl.internal.apps.v1.RollableScalableResourceOperation.edit(RollableScalableResourceOperation.java:163)
	at io.fabric8.kubernetes.client.dsl.internal.apps.v1.RollableScalableResourceOperation.edit(RollableScalableResourceOperation.java:44)
	at io.fabric8.kubernetes.examples.FullExample.main(FullExample.java:156)
Caused by: java.lang.NoSuchMethodException: io.fabric8.kubernetes.api.model.DoneableReplicationController.<init>(io.fabric8.kubernetes.api.model.ReplicationController, io.fabric8.kubernetes.api.builder.Visitor)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at io.fabric8.kubernetes.client.dsl.internal.apps.v1.RollableScalableResourceOperation.edit(RollableScalableResourceOperation.java:161)
	... 2 more
[main] ERROR io.fabric8.kubernetes.examples.FullExample - An error has occurred.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.dsl.internal.apps.v1.RollableScalableResourceOperation.edit(RollableScalableResourceOperation.java:163)
	at io.fabric8.kubernetes.client.dsl.internal.apps.v1.RollableScalableResourceOperation.edit(RollableScalableResourceOperation.java:44)
	at io.fabric8.kubernetes.examples.FullExample.main(FullExample.java:156)
Caused by: java.lang.NoSuchMethodException: io.fabric8.kubernetes.api.model.DoneableReplicationController.<init>(io.fabric8.kubernetes.api.model.ReplicationController, io.fabric8.kubernetes.api.builder.Visitor)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at io.fabric8.kubernetes.client.dsl.internal.apps.v1.RollableScalableResourceOperation.edit(RollableScalableResourceOperation.java:161)
	... 2 more
```

### PR DESCRIPTION
**Pull request by dixingxing0**
Fixes #2555 

## Type of change
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
LGTM, thx

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
[merge]

**Comment by rohanKanojia** [comment]
[merge]

**Comment by manusa** [comment]
[merge]

**Pull request merged**
