### PR TITLE
Fix kubeconfig path on windows - thanks to @jmandawg

### LINKED ISSUE #350: on windows if we can't find ~/.kube we should look in %HOMEDRIVER%\%HOMEPATH%
which seems to be where oc.exe puts things

see thread:
https://groups.google.com/forum/#!topic/fabric8/7Iq4NQo2twY

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #350

### CODE REVIEW

**Comment by jimmidyson** [comment]
Thanks @jmandawg

**Comment by jimmidyson** [comment]
[merge]

**Comment by jmandawg** [comment]
Sorry, I forgot the null check, better to be safe than sorry.

[config.java.patch.txt](https://github.com/fabric8io/kubernetes-client/files/200832/config.java.patch.txt)

**Comment by jimmidyson** [comment]
Sorry that was my fault when I swapped the length check for isEmpty - will fix up later.

**Pull request merged**
