### PR TITLE
Separate client jars from shaded jars.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by iocanel** [comment]
@jimmidyson I want your input on this!

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
@iocanel can you rebase please?

**Comment by iocanel** [comment]
retest this please

**Comment by jimmidyson** [comment]
@iocanel Much better!

So we shade kubernetes client inside openshift client too?

**Comment by iocanel** [comment]
No need to shade 2MB worth of dependencies twice.

**Comment by iocanel** [comment]
[merge]

**Comment by iocanel** [comment]
[merge]

**Pull request merged**
