### PR TITLE
chore: Switch reconnect backoff message in wach manager to debug level

### PR DESCRIPTION
**Pull request by rhuss**
info level seems to be inappropriate for this internal processing message as this regularly happens and does not really add much information, looks more like random noise.

Its valuable for debugging though, so I suggest to move this from "info" to "debug" level.

### CODE REVIEW

**Comment by oscerd** [comment]
ok to test

**Comment by piyush1594** [comment]
ok to test

**Comment by oscerd** [comment]
ok to test

**Comment by oscerd** [comment]
[merge]

**Pull request merged**
