### PR TITLE
#914: Add possibility to change MaxRequests on Dispatcher in HttpClie…

### PR DESCRIPTION
**Pull request by thorbenvh8**
…ntUtils
#914 
Thanks :)

### CODE REVIEW

**Comment by iocanel** [comment]
Overall looks good, though I am trying to understand, how it plays with `maximum requests per host`

What happens when both are set?  It seems that out of the box we set 64 concurrent request but only 5 per host. Given that I can't think of a case where multiple hosts are involved does that mean that the limit is still 5?

**Comment by thorbenvh8** [comment]
64 is the default value in the dispatcher, I dont know why its 64 i just used that. The default value for maxRequestsPerHost in the dispatcher is 5, what is the default value in the k8s client. I just used whats default.

**Comment by iocanel** [comment]
ok to test

**Comment by asacbp** [comment]
when do you think will we you have time to bake a release with this pull request? thanks!

**Comment by iocanel** [comment]
[merge]

**Pull request merged**
