### PR TITLE
remove job extensions/v1beta1 from backward compatibility

### PR DESCRIPTION
**Pull request by itsmurugappan**
## Description

Fixes the issue #2300 . Removes job extensions/v1beta1 from backward compatibility interceptor. As job has been removed from extensions/v1beta1 .

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@itsmurugappan : Was your issue resolved with this change?

**Comment by itsmurugappan** [comment]
Yes it was. Thank you @rohanKanojia

**Comment by rohanKanojia** [comment]
Np, Thanks a lot for your contribution :+1:

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
