### PR TITLE
Chore: Fix Status initialization errors in kubernetes-examples/

### PR DESCRIPTION
**Pull request by rohanKanojia**
We added support for automatically instantiating Spec and Status in https://github.com/fabric8io/kubernetes-client/pull/2739 but somehow missed updating our examples, due to that I was facing status instantiation errors like these:
```
Caused by: java.lang.IllegalArgumentException: Cannot instantiate Status, consider overriding initStatus: Cannot instantiate interface/abstract type io.fabric8.kubernetes.api.model.KubernetesResource
        at io.fabric8.kubernetes.client.CustomResource.genericInit(CustomResource.java:342)
```

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by manusa** [comment]
Hi @metacosm 
Not sure if you saw this.
I'm not sure if anyone would actually build a CustomResource with no spec field (or void) (goes against convention), but the automatic instantiation feature breaks this use case.
Should we consider this use case and provide a solution?

**Comment by metacosm** [comment]
Yes, we should. Will take a look tomorrow.

**Comment by metacosm** [comment]
> Hi @metacosm
> Not sure if you saw this.
> I'm not sure if anyone would actually build a CustomResource with no spec field (or void) (goes against convention), but the automatic instantiation feature breaks this use case.
> Should we consider this use case and provide a solution?

So, actually, I'm not sure what use case you want to make sure works properly… The case where someone doesn't want to provide a spec class? In that case, they should use `CustomResource<Void, Status>` and it should work.

**Comment by manusa** [comment]
:flushed:  Wow, for some reason I read the changes in the opposite way (Void being removed instead of added).
I'll check later on, but it seems everything should be fine. Sorry for the inconvenience.

**Comment by metacosm** [comment]
> 😳 Wow, for some reason I read the changes in the opposite way (Void being removed instead of added).
> I'll check later on, but it seems everything should be fine. Sorry for the inconvenience.

No inconvenience, was just wondering if I had missed something… 😄

**Review by manusa — APPROVED** [review]
LGTM, thx

**Pull request merged**
