### PR TITLE
Remove unused argument and exceptions

### PR DESCRIPTION
**Pull request by Alameyo**
I believe unused code can be removed.

### CODE REVIEW

**Comment by rohanKanojia** [comment]
ok to test

**Comment by gastaldi** [comment]
@Alameyo LGTM, but I'd go even further and remove that method completely (moving the SSL initialization body to the `SSLContext sslContext(Config config)` method)  ;)

**Comment by gastaldi** [comment]
Hm, or maybe not now that I look into `HttpClientUtils#createHttpClient`. Your changes are good ;)

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
