### PR TITLE
issue #711 KeyStore tries to load both default keystore files

### PR DESCRIPTION
**Pull request by MatousJobanek**
When KeyStore is initialized it tries to load keystore file "~/.keystore" with the default passphrase "changeit"
if the file is not present or if there is any problem when the file is loaded, it tries to load the file "java_jre_path/lib/security/cacerts"
if none of the files can be loaded, then an empty KeyStore is created.

### CODE REVIEW

**Comment by jimmidyson** [comment]
This is looking really good - sorry for the slow review!

I just read the following details from http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#InstallationAndCustomization and more further down on that page (sorry not linkable...):

```
If a null KeyStore parameter is passed to the SunJSSE PKIX or SunX509 TrustManagerFactory, then the factory uses the following process to try to find trust material:

If the javax.net.ssl.trustStore property is defined, then the TrustManagerFactory attempts to find a file using the file name specified by that system property, and uses that file for the KeyStore parameter. If the javax.net.ssl.trustStorePassword system property is also defined, then its value is used to check the integrity of the data in the truststore before opening it.

If the javax.net.ssl.trustStore property is defined but the specified file does not exist, then a default TrustManager using an empty keystore is created.

If the javax.net.ssl.trustStore system property was not specified, then:
if the file java-home/lib/security/jssecacerts exists, that file is used;
if the file java-home/lib/security/cacerts exists, that file is used;
if neither of these files exists, then the SSL cipher suite is anonymous, does not perform any authentication, and thus does not need a truststore.
For information about what java-home refers to, see The Installation Directory.

The factory looks for a file specified via the javax.net.ssl.trustStore security property or for the jssecacerts file before checking for a cacerts file. Therefore, you can provide a JSSE-specific set of trusted root certificates separate from ones that might be present in cacerts for code-signing purposes.
```

So this should really support system properties `javax.net.ssl.trustStore` and `javax.net.ssl.keyStore` before looking for defaults paths. Does that sound reasonable?

**Comment by MatousJobanek** [comment]
Good point @jimmidyson 
Please, take a look at my latest commit - I've added a check of the system properties there.
The only thing I'm not sure about is if we should check the `~/.keystore` file automatically. It is a default location for the `keytool`, but there is no mention about the file in the document. WDYT?

**Comment by iocanel** [comment]
ok to test

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
@MatousJobanek Sorry for the delay on this. I would prefer to stick to just the documented keystore/truststore locations so can you please remove the $HOME/.keystore default? Thanks!

**Comment by jimmidyson** [comment]
Thanks @MatousJobanek! [merge]

**Pull request merged**
