### PR TITLE
#548: DeploymentConfig reaper now also reaps the deployer pod.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Could you check if that's consistent with openshift experience?

**Comment by iocanel** [comment]
@jimmidyson: My understanding is that if the deployer is present at the time we delete the `dc`, it won't get deleted, by the command line client.

Still, I don't really see a reason to keep it around.

**Comment by jimmidyson** [comment]
Have you had a look at the OpenShift client code to see what it does on delete?

**Comment by jimmidyson** [comment]
See https://github.com/openshift/origin/blob/master/pkg/client/deploymentconfigs.go#L85 - just deletes the DC itself, no reaping at all. I'm kind of confused why the deployer pod stays around tbh. From what I see, the deployer pod is GCed after a short period, just like any terminated pod.

**Comment by jimmidyson** [comment]
Plus take a look at http://kubernetes.io/docs/user-guide/garbage-collection/. Not sure 100%if it applies to openshift yet, but a better approach in general.

**Comment by iocanel** [comment]
The deployer may be left behind, if there is an error, or the DeploymentConfig gets wiped while the deployer is running. I don't know if there are other cases too.

Maybe there are other cases too, but I don't see any hard in deleting it.

**Pull request closed without merging**
