### PR TITLE
[CD] Release 1.3.75

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
[merge]

**Comment by yongk802** [comment]
Hey guys, can we please include my pull request in this release?

https://github.com/fabric8io/kubernetes-client/pull/341

It fixes a bug that's preventing integration tests from passing on our CI server.

**Comment by jimmidyson** [comment]
I'll kick off a new release for you now - 1.3.75 is already done I'm afraid.

**Comment by jimmidyson** [comment]
[merge]

**Comment by yongk802** [comment]
Ah ok, thanks!

**Comment by yongk802** [comment]
Jimmi,

Thanks for doing this build. Do you know when it will be available and in the meantime, do you post SNAPSHOT builds for this artifact anywhere? I tried looking here, but I see one hasn't been posted in a long time:

https://oss.sonatype.org/content/repositories/snapshots/io/fabric8/kubernetes-client/

**Comment by jimmidyson** [comment]
@yongk802 Sorry release got stuck behind another release that hung... Should be available a bit later. We don't publish snapshots - too many moving/changing stuff between releases so unless we really need to we don't publish snapshots normally.

**Comment by yongk802** [comment]
Ah, no worries. Thanks for the update!

**Comment by jimmidyson** [comment]
@yongk802 Eventually 1.3.76 is released & available in maven central - enjoy!

**Comment by yongk802** [comment]
Awesome, I see it, thanks!

**Pull request merged**
