### PR TITLE
Fix #2391. Fix createOrReplace() for extensions.v1beta1

### LINKED ISSUE #2391: Calling createOrReplace() on client.extensions().deployments().inNamespace() or client.apps().deployments().inNamespace() does not call the correct API version.
I'm currently trying to use the client to replace an existing deployment using the `extensions/v1beta1` API version, rather than `v1` as the client sets as default. I initialize the client with: 
```java 
Config config = new ConfigBuilder().withApiVersion("extensions/v1beta1").build(); 
client = new DefaultKubernetesClient(config);
```

And initialize the Deployment with `DeploymentBuilder(). withApiVersion("extensions/v1beta1")`

and attempt to create the deployment with 
```java
client.extensions().deployments().inNamespace(apiManifest.getNamespace()).createOrReplace(deployment);
```
which should perform a PUT request at `apis/extensions/v1beta1/namespaces/{namespace}/deployments/{deploy}`, given that I am running with api version `extensions/v1beta1` and calling with `extensions.deployments()` rather than `apps.deployments()`. 

However, it instead makes a PUT to `apps/v1`. This returns the error:
`Message: the API version in the data (extensions/v1beta1) does not match the expected API version (apps/v1)`

If the resource does not exist prior to creation, it instead fails with:
`Message: the API version in the data (extensions/v1beta1) does not match the expected API version (apps/v1).`

Digging into it, this seems to be a bug in expected functionality. The api version is hardcoded in the context in  `DeploymentOperationsImpl`: https://github.com/fabric8io/kubernetes-client/blob/50c1e8d86db5dc375c25f187a6ce2e1c6a69f2b5/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/DeploymentOperationsImpl.java#L73-L80 
 
If this is not a bug, is there any way to make a request with this version? If not, what is the purpose of setting the apiVersion in the client?

### PR DESCRIPTION
**Pull request by anshlykov**
## Description

Closes #2391

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@anshlykov: Is this PR ready for review? If yes, could you please mark it ready for review?

**Review by oscerd — APPROVED** [review]

**Review by manusa — APPROVED** [review]

**Comment by anshlykov** [comment]
@rohanKanojia will you have a chance to review?

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@anshlykov: There is a minor conflict. Could you please address it? I think we can proceed to merge after that :-) . Also, Do you think we should file an issue for getting rid of duplication as mentioned in your comment https://github.com/fabric8io/kubernetes-client/pull/2409#issuecomment-678788787 so that we don't forget about refactoring this :smile:

**Comment by rohanKanojia** [comment]
[merge]

**Comment by rohanKanojia** [comment]
@anshlykov: Sorry for requesting one change again, I just noticed there are a few [sonar code smells](https://sonarcloud.io/project/issues?id=fabric8io_kubernetes-client&open=AXQDQwLyRC-NlxSEAZI-&pullRequest=2409&resolved=false&types=CODE_SMELL) which can easily be addressed. Could you please address them too?

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
[merge]

**Pull request merged**
