### PR TITLE
wrap input stream used to load certs in a try so they're automatically closed

### PR DESCRIPTION
**Pull request by ddl-audi**
## Description
There are a few file descriptor leaks in cert utils: Fix https://github.com/fabric8io/kubernetes-client/issues/3062
## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by ddl-audi** [comment]
The original failure was due to a flaky test that has been disabled in this commit: 6b95d496db7d5577bebd224c7d5c340bdf3c006a

I made a couple mistakes rebasing on master to get that incorporated so it took couple forces to fix.

@rohanKanojia I hope I didn't break any workflows, but please do let me know if I have to fix anything/resubmit from a different fork :)

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by oscerd — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Comment by ddl-audi** [comment]
Can someone advise me on how to triger a run / re-run of the failed build pipeline steps?
It appears the most recent failure was due to a jacoco error
`Error:  Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.7:report (default-report) on project kubernetes-karaf-itests: An error has occurred in JaCoCo report generation. Error while creating report: null: EOFException -> [Help 1]`

**Comment by rohanKanojia** [comment]
@ddl-audi : Sorry for the inconvenience. I've restarted the workflow

**Comment by ddl-audi** [comment]
I did something while rebasing on master (again) and caused github to close this PR. I'm going to open a fresh one

**Comment by ddl-audi** [comment]
Super sorry for the inconvenience, I moved the PR to https://github.com/fabric8io/kubernetes-client/pull/3134 instead of trying to get github to recognize that this PR actually should be tracking a diff

**Pull request closed without merging**
