### PR TITLE
Adding test scope to test dependencies

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by jpechane** [comment]
This PR fixes issue with apiman iPaaS Docker build - it pulls openshift-client-tests jar instead of openshift-client jar which breaks authentication interceptor.

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
[merge]

**Comment by jimmidyson** [comment]
Thanks @jpechane!

**Pull request merged**
