### PR TITLE
fix: crd-gen includes only enum values and discard enum fields

### LINKED ISSUE #4225: [crd-gen] Enum fields written in generated crd yaml
### Describe the bug

When the crd-gen tool tries to generate schema properties from an enum, both values and fields are written in the generated crd yaml.

### Fabric8 Kubernetes Client version

5.12.2

### Steps to reproduce

Create an enum with values and at least a field and put it into Spec. 
Example:

```
@Group("com.example")
@Version("mycrd")
@Plural("mycrds")
public class MyCRD extends CustomResource<MyCRDSpec, Void> implements Namespaced {

  public class MyCRDSpec {

    private Test test;

    public enum Test {
      A("test-a"),
      B("test-b");

      private final String field1;

      Test(String field1) {
        this.field1 = field1;
      }

      public String getField1() {
        return field1;
      }
    }
  }
}


```

Exec `mvn clean compile`

the generated file target/classes/META-INF/fabric8/mycrds.com.example-v1.yml will contain:
```
# Generated by Fabric8 CRDGenerator, manual edits might get overwritten!
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.com.example
spec:
  group: com.example
  names:
    kind: MyCRD
    plural: mycrds
    singular: mycrd
  scope: Namespaced
  versions:
  - name: mycrd
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              test:
                enum:
                - A
                - B
                - field1
                type: string
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true

```

### Expected behavior

A crd with just enum values and without enum fields:
```

# Generated by Fabric8 CRDGenerator, manual edits might get overwritten!
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.com.example
spec:
  group: com.example
  names:
    kind: MyCRD
    plural: mycrds
    singular: mycrd
  scope: Namespaced
  versions:
  - name: mycrd
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              test:
                enum:
                - A
                - B
                type: string
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true

```

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22.3@latest

### Environment

Windows

### Fabric8 Kubernetes Client Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leoandrea7**
## Description

Fix #4225 
## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by andreaTP** [comment]
I took a look at this issue and cannot find a proper check to correctly include/exclude enum's instances.

Specifically given the test here:
https://github.com/sundrio/sundrio/blob/b7091f8fbe792596258d6bf3a10c05bc3a415bd4/adapters/api/src/test/java/io/sundr/adapter/testing/AbstractAdapterTest.java#L206

We include all the needed properties, but we don't know how to discriminate actual values of the Enum from other methods/accessos/constructors.

Maybe @metacosm or @iocanel can help.

Alternatively, it should be enough to "workaround" this issue by considering the `JsonIgnore` annotation on enum properties (I can open a separate issue for it if needed).

**Comment by leoandrea7** [comment]
@andreaTP maybe you should add a filter [here ](https://github.com/sundrio/sundrio/blob/b7091f8fbe792596258d6bf3a10c05bc3a415bd4/adapters/api/src/test/java/io/sundr/adapter/testing/AbstractAdapterTest.java#L204)like the filter i added with this PR

**Comment by andreaTP** [comment]
@leoandrea7 couldn't find any way to discriminate the actual enum values from other properties :-(

**Comment by leoandrea7** [comment]
@andreaTP you are absolutely right...The problem is that TypeDef class does not have a method that return just enum values..I tried to fetch enum with `Class.forName(def.getFullyQualifiedName())` in order to use .values() directly but there is classloader problems for test..

**Comment by leoandrea7** [comment]
@andreaTP After some thought, I think your test case with an enum containing a field of the same type as the enum itself is a very infrequent case. For now it would be better to merge this solution which solves most of the use cases and I could add in the docs of the crd-gen a new section (titled limitation or known problems) in which I specify that this particular case is not yet supported. Then if in the future the sundrio library will introduce a specific method to recover only the values of an enum through the TypeDef class then we will also solve the use case you have proposed. This would solve most of the use cases for enums containing fields. What do you think?

**Comment by andreaTP** [comment]
I don't think this case is infrequent, and anyhow, unfortunately, it's semantically incorrect.
I would suggest that we move on fixing JsonIgnore behavior in enums so that there will be a viable workaround for your use case(possibly re-using the more generic Properties parser logic).

Meanwhile, we can add the necessary information in Sundrio cc. @iocanel and move on from there.

**Comment by andreaTP** [comment]
Submitted #4294 should provide a workaround also for this issue.

**Comment by manusa** [comment]
Hi #4294 has been merged. Is this PR providing something else?

**Comment by andreaTP** [comment]
@manusa , yes, this PR is providing something different, but, to have a robust implementation we need to bubble up information changing `sundrio` first.

**Comment by andreaTP** [comment]
@shawkins do you mind fixing the conflicts?
As discussed in the other issue, I have no objection to moving this forward at this point.

**Review by manusa — APPROVED** [review]

**Pull request merged**
