### PR TITLE
fix: properly extract resource metadata from URI on HTTP request failures

### LINKED ISSUE #4049: `RequestMetadata.from` method doesn't properly extract components
If the request URI starts with a `/`, the segments have empty components which results in the method not properly extracting the components.

### PR DESCRIPTION
**Pull request by metacosm**
## Description
Fixes #4049

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by rohanKanojia** [comment]
Duplicate of #4051

**Comment by shawkins** [comment]
@rohanKanojia the other is against 5.12

**Comment by rohanKanojia** [comment]
From what I remember we usually cherry-pick commits on our own while releasing patch versions.

**Comment by metacosm** [comment]
> From what I remember we usually cherry-pick commits on our own while releasing patch versions.

So should I close the other PR?

**Comment by rohanKanojia** [comment]
No, let's leave it to Marc when he's releasing next version of 5.12.x.

**Comment by metacosm** [comment]
> No, let's leave it to Marc when he's releasing next version of 5.12.x.

So not sure what I should do… To be clear, I'd rather close the other PR and let @manusa deal with merging it back to 5.12.x but that might be difficult to track. That'd definitely be easier for me because that means I don't have to update the other PR :)

**Comment by rohanKanojia** [comment]
okay, you can close the PR :+1: .

**Review by manusa — APPROVED** [review]

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
