### PR TITLE
Fixes #767: adding lock replace

### LINKED ISSUE #767: Unable to leverage optimistic locking during patch/replace
Currently:
- `.patch()` ignores the `resourceVersion` field while computing the diff
- `.replace()` updates the resource version with latest version found on server (trying 10 times to get the most recent one).

There seems to be no way to do **optimistic locking** of resources (e.g. the first one who tries to update a resource wins).

Libraries doing leader election like [camel-master](https://github.com/fabric8io/fabric8-ipaas/blob/master/camel-master/src/main/java/io/fabric8/camel/master/KubernetesLock.java#L183) simply cannot work: once the first leader loses the leadership, anybody becomes the leader... this is elsewhere called *anarchy*. 

Deleting the resource and recreating it is not an option in the case of camel-master, since it's shared.

@iocanel, @jstrachan thoughts?

### PR DESCRIPTION
**Pull request by nicolaferraro**
Adding a `.lockResourceVersion("...")` to replace to perform optimistic locking.

### CODE REVIEW

**Comment by nicolaferraro** [comment]
Ping @iocanel

**Comment by iocanel** [comment]
@nicolaferraro: Sorry for the delay! 

Now, this will have to go in 2.5.x since it introduces and uses a new interface in the DSL.

**Comment by nicolaferraro** [comment]
It's related to https://github.com/fabric8io/kubernetes-client/issues/767

**Comment by iocanel** [comment]
This should have been part of 2.5 but, that didn't happen so I am bumping to 2.6.

**Comment by nicolaferraro** [comment]
Is there something I can do to get this merged (it has been waiting a lot :wink: now)?

I don't think it's such a breaking change in the DSL, since it just adds a new method. Anyway, I can also bump global version to 2.6-SNAPSHOT in this PR if it's needed.

**Comment by oscerd** [comment]
Maybe you can switch to 2.6-SNAPSHOT and then we can merge.

**Comment by iocanel** [comment]
I bumped to 2.6-SNAPSHOT, so I think we are good to go

**Comment by iocanel** [comment]
@nicolaferraro: sorry for the delay. This should have made it to the 2.5.x but it slipped.

Regarding, the change not being breaking. It doesn't really matter how big or small a change is. Changes to the public api needs at least a minor version bump.

**Comment by nicolaferraro** [comment]
Thanks @iocanel, I understand. It stayed here for 2 months mainly because I forgot about it :)

Thanks for meeting it.

**Pull request merged**
