### PR TITLE
chore(camel-k): Update Fabric8 CamelK Extension model to v1.7.0 (#3670)

### LINKED ISSUE #3670: Camel-K Extension: Point latest released version 1.7.0
### Is your task related to a problem? Please describe

It's still pointing 1.3.0

### Describe the solution you'd like

Pointing to 1.7.0

### Describe alternatives you've considered

_No response_

### Additional context

First iteration fails with

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project camel-k-model-v1alpha1: Compilation failure: Compilation failure: 
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/io/fabric8/camelk/v1alpha1/KameletSpec.java:[17,28] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: package io.fabric8.camelk.v1
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/io/fabric8/camelk/v1alpha1/KameletSpec.java:[79,13] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: class io.fabric8.camelk.v1alpha1.KameletSpec
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/io/fabric8/camelk/v1alpha1/KameletSpec.java:[102,163] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: class io.fabric8.camelk.v1alpha1.KameletSpec
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/io/fabric8/camelk/v1alpha1/KameletSpec.java:[164,12] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: class io.fabric8.camelk.v1alpha1.KameletSpec
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/io/fabric8/camelk/v1alpha1/KameletSpec.java:[169,29] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: class io.fabric8.camelk.v1alpha1.KameletSpec
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/annotations/io/fabric8/camelk/v1alpha1/KameletSpecFluent.java:[79,10] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: interface io.fabric8.camelk.v1alpha1.KameletSpecFluent<A>
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/annotations/io/fabric8/camelk/v1alpha1/KameletSpecFluent.java:[80,25] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: interface io.fabric8.camelk.v1alpha1.KameletSpecFluent<A>
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/annotations/io/fabric8/camelk/v1alpha1/KameletSpecFluentImpl.java:[40,11] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: class io.fabric8.camelk.v1alpha1.KameletSpecFluentImpl<A>
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/annotations/io/fabric8/camelk/v1alpha1/KameletSpecFluentImpl.java:[199,10] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: class io.fabric8.camelk.v1alpha1.KameletSpecFluentImpl<A>
[ERROR] /home/oscerd/workspace/miscellanea/kubernetes-client/extensions/camel-k/model-v1alpha1/target/generated-sources/annotations/io/fabric8/camelk/v1alpha1/KameletSpecFluentImpl.java:[202,25] cannot find symbol
[ERROR]   symbol:   class Template
[ERROR]   location: class io.fabric8.camelk.v1alpha1.KameletSpecFluentImpl<A>
[ERROR] -> [Help 1]
```

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description
Fix #3670 

+ Bump Go Module dependencies in Camel Extension Generators to v1.7.0

Signed-off-by: Rohan Kumar <rohaan@redhat.com>

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [X] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Thanks a lot for looking at this.

**Review by lburgazzoli — APPROVED** [review]

**Comment by rohanKanojia** [comment]
No problem at all, Thanks a lot for bringing it to our team's attention.

**Comment by rohanKanojia** [comment]
Bdw, I didn't check if there was any new resource(CRD) added in the newer version. Do you know if there is any new CRD added to camelk API? We'll need to add it's model and expose it via extension DSL

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
