### PR TITLE
Chore #1168 : Upgrade to Java 8

### PR DESCRIPTION
**Pull request by rohanKanojia**
#1168

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@oscerd : It build fine on my system. Do we have to make any changes on CI side as well?

**Comment by oscerd** [comment]
[test]

**Comment by oscerd** [comment]
Not sure, seems to be a problem with Jenkins job configuration

**Comment by oscerd** [comment]
It was the configuration of the job. Now it is running.

**Comment by oscerd** [comment]
[merge]

**Comment by oscerd** [comment]
[merge]

**Comment by rohanKanojia** [comment]
:clap:

**Pull request merged**
