### PR TITLE
Added support for StorageClass

### PR DESCRIPTION
**Pull request by tejasparikh**
https://github.com/fabric8io/kubernetes-client/issues/869 Added support for StorageClass resource.

### CODE REVIEW

**Comment by iocanel** [comment]
ok to test

**Comment by iocanel** [comment]
Please add missing license headers.
This can do it for you.

    mvn -N license:format

**Comment by tejasparikh** [comment]
@iocanel I have updated the license headers

**Comment by oscerd** [comment]
Everything looks good, lets merge!

**Comment by oscerd** [comment]
[merge]

**Pull request merged**
