### PR TITLE
Attach to pod functionality

### LINKED ISSUE #4333: Attach to pod feature
### Is your enhancement related to a problem? Please describe

For our current project, we need the ability to attach to the container in a pod to send stdin and read stdout. If I understood correctly, currently there is no way to do it.

### Describe the solution you'd like

Implement `kubectl attach` equivalent the same way as `kubectl exec` is implemented. The main concern regarding the implementation of such feature is that its' DSL would clash the existing one for `exec` (e.g. `redirectingInput().redirectingOutput().exec("...")`). In my point of view, the DSL should be extended instead of copying, i.e.:
```java
ExecWatch execResult = client.pods().withName("...").inContainer("session").redirectingInput().exec("ls");
AttachWatch attachResult = client.pods().withName("...").inContainer("session").redirectingInput().attach("ls");
```

### Describe alternatives you've considered

The alternative way to support such case would be to give a user the ability to use WebSockets directly [as it is implemented in official kubernetes-client](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-15/src/main/java/io/kubernetes/client/examples/WebSocketsExample.java) (though, just to mention, official kubernetes-client has the `attach` feature). I don't like such approach, but it may be easier to implement.

### Additional context

I'm ready to try to implement this feature by myself after syntax & requirements will be clear.

### PR DESCRIPTION
**Pull request by kuzznya**
## Description

Implement attachment to the main process of the pod (the equivalent of `kubectl attach`) in almost the same way as `exec` is implemented. `Execable` interface and `ExecWatch` were reused because for me it is reasonable to use the same classes for `exec` and `attach`. I decided not to rename them to have simpler names though it can be discussed.

The example and `kubectl attach` equivalent are added, as well as unit & integration tests.

Fix #4333 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by kuzznya** [comment]
Hi @shawkins, could you please help me with running PR checks? I don't understand why they are not executed. If it is because this PR is in draft state, then I can mark it as "Ready for review", because all the development is done, I just wanted to get all these PR checks finished before marking is as ready.

**Comment by shawkins** [comment]
@kuzznya I'm not sure why the job isn't completing.  @manusa any ideas?

**Comment by manusa** [comment]
> @kuzznya I'm not sure why the job isn't completing. @manusa any ideas?

AFAIK Sometimes (especially when some systems are down), GitHub Actions misses some of the events and workflows aren't triggered.

I've rebased your branch and forced push it, pipelines should run now

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by shawkins — APPROVED** [review]
LGTM

**Pull request merged**
