### PR TITLE
Fix my mistake: set cascade deletion to true by default

### PR DESCRIPTION
**Pull request by rohanKanojia**
Follow up PR as per discussion here: https://github.com/fabric8io/kubernetes-client/pull/1521/
Setting cascading to true instead of false

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@deiwin @jglick : I've changed that cascading flag to `true`. Could you guys please test it out on your systems to see if it's actually fixing your problems? Otherwise, I would look deeper into this. Would be great if you could give me some reproducible scenario.

**Comment by deiwin** [comment]
I don't use this library directly, so this is difficult, but something like the following should verify it:

**Given**
1) Setup with `kubectl` in shell:
```
kubectl run test --image=ubuntu --restart=Never --command -- sleep infinity
uid=$(kubectl get pod/test -o=jsonpath='{.metadata.uid}')
kubectl run deploy-test --image=ubuntu --replicas=2 --overrides='{"metadata":{"ownerReferences":[{"apiVersion":"v1","kind":"Pod","controller":true,"blockOwnerDeletion":true,"name":"test","uid":"'"$uid"'"}]}}' --command -- sleep infinity
```
2) Then execute the following with the library, as done [here](https://github.com/jenkinsci/kubernetes-plugin/blob/b0439fad480070b599adc93caf62f7a11326a2ed/src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesSlave.java#L294):
```
client.pods().inNamespace('default').withName('test').delete();
```

**Expected**
```
$ kubectl get deploy/deploy-test
No resources found.
Error from server (NotFound): deployments.extensions "deploy-test" not found
```

**Actual current behavior**
```
$ kubectl get deploy/deploy-test
NAME          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy-test   2         2         2            2           8s
```

**Test cleanup**
```
kubectl delete deploy/deploy-test pod/test
```

**Comment by rohanKanojia** [comment]
@deiwin : Hi, I tested using your use case but it doesn't seem to be working as expected with this patch. I tested on `4.1.3` also but that also is giving the same result.

**Comment by rohanKanojia** [comment]
@deiwin : Thanks for the test case, it seems to be working . Here are the logs:
```
~/work/repos/kubernetes-client-demo : $ kubectl run test --image=ubuntu --restart=Never --command -- sleep infinity
pod/test created
~/work/repos/kubernetes-client-demo : $ uid=$(kubectl get pod/test -o=jsonpath='{.metadata.uid}')
~/work/repos/kubernetes-client-demo : $ kubectl get pods
NAME   READY   STATUS    RESTARTS   AGE
test   1/1     Running   0          10s
~/work/repos/kubernetes-client-demo : $ kubectl run deploy-test --image=ubuntu --replicas=2 --overrides='{"metadata":{"ownerReferences":[{"apiVersion":"v1","kind":"Pod","controller":true,"blockOwnerDeletion":true,"name":"test","uid":"'"$uid"'"}]}}' --command -- sleep infinity
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/deploy-test created
~/work/repos/kubernetes-client-demo : $ kubectl get pods
NAME                           READY   STATUS              RESTARTS   AGE
deploy-test-84bdc89bc7-gsvpt   1/1     Running             0          10s
deploy-test-84bdc89bc7-p2xk8   0/1     ContainerCreating   0          10s
test                           1/1     Running             0          34s
~/work/repos/kubernetes-client-demo : $ kubectl get deployment
NAME          READY   UP-TO-DATE   AVAILABLE   AGE
deploy-test   2/2     2            2           15s
~/work/repos/kubernetes-client-demo : $ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
deploy-test-84bdc89bc7-gsvpt   1/1     Running   0          22s
deploy-test-84bdc89bc7-p2xk8   1/1     Running   0          22s
test                           1/1     Running   0          46s
~/work/repos/kubernetes-client-demo : $ kubectl get pod^C
~/work/repos/kubernetes-client-demo : $ -search)`mvn': mvn exec:java -Dexec.mainClass="io.fabric8.ClientDemo"
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< io.fabric8:kubernetes-client-demo >------------------
[INFO] Building kubernetes-client-demo 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ kubernetes-client-demo ---
Jul 10, 2019 11:31:07 AM io.fabric8.ClientDemo main
INFO: Creating Kuberntes client
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jul 10, 2019 11:31:08 AM io.fabric8.ClientDemo main
INFO: Kubernetes client successfully created
[WARNING] thread Thread[OkHttp ConnectionPool,5,io.fabric8.ClientDemo] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[OkHttp ConnectionPool,5,io.fabric8.ClientDemo] will linger despite being asked to die via interruption
[WARNING] thread Thread[OkHttp Http2Connection,5,io.fabric8.ClientDemo] will linger despite being asked to die via interruption
[WARNING] thread Thread[Okio Watchdog,5,io.fabric8.ClientDemo] will linger despite being asked to die via interruption
[WARNING] NOTE: 3 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=io.fabric8.ClientDemo,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:776)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:328)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.571 s
[INFO] Finished at: 2019-07-10T11:31:23+05:30
[INFO] ------------------------------------------------------------------------
~/work/repos/kubernetes-client-demo : $ kubectl get deploy/deploy-test
Error from server (NotFound): deployments.extensions "deploy-test" not found
~/work/repos/kubernetes-client-demo : $ kubectl get deploy/deploy-test
Error from server (NotFound): deployments.extensions "deploy-test" not found
~/work/repos/kubernetes-client-demo : $ 

```

**Comment by rohanKanojia** [comment]
@deiwin : strange, this test case is working for 4.3.0 as well :confused:

**Comment by deiwin** [comment]
Hmm. What Kubernetes version are you testing on? I'm using
```
kubectl version --short
Client Version: v1.11.3
Server Version: v1.11.8-eks-7c34c0
```

**Comment by deiwin** [comment]
And can you also share the code you used, please?

**Comment by jglick** [comment]
> Could you guys please test it out on your systems to see if it's actually fixing your problems?

I have asked for details from the user originally reporting a regression. No need to wait on us if you can confirm a regression and a fix by other means.

**Comment by rohanKanojia** [comment]
ah, sorry, it's working when I explicitly provide cascading flag:
```
client.pods().inNamespace("default").withName("test").cascading(true).delete();
```

**Comment by deiwin** [comment]
And without the explicit `.cascading(true)`, does it fail on 4.3.0 as I described?

**Comment by rohanKanojia** [comment]
yes, it fails.

**Comment by rohanKanojia** [comment]
It fails on this patch also.

**Comment by deiwin** [comment]
So the patch does not help? 😮

**Comment by rohanKanojia** [comment]
yeah, will need to look deeper as of why it doesn't help. But isn't it desired behavior? If you want cascade deletion then provide cascading flag? Is deletion in kubernetes cascading by default?

**Comment by deiwin** [comment]
We should probably test 4.1.3 as well, because if my understanding is correct, then in 4.1.3 it should delete deployment without `.cascading(true)`, but in 4.3.0 it doesn't anymore.

>  But isn't it desired behavior? If you want cascade deletion then provide cascading flag? Is deletion in kubernetes cascading by default?

If I do e.g. `kubectl delete` for the pod, then the deployment will be deleted.

**Comment by rohanKanojia** [comment]
oh, okay.

**Comment by rohanKanojia** [comment]
I will update this patch to replicate this desired behavior

**Comment by rohanKanojia** [comment]
> We should probably test 4.1.3 as well, because if my understanding is correct, then in 4.1.3 it should delete deployment without .cascading(true), but in 4.3.0 it doesn't anymore.

I checked on 4.1.3 doesn't work there as well.

**Comment by deiwin** [comment]
Just to be absolutely clear, are you saying that the behavior is exactly the same for 4.1.3 and 4.3.0 with `client.pods().inNamespace("default").withName("test").delete();` without `.cascading(true)`?

**Comment by rohanKanojia** [comment]
yes, as per my observation

**Comment by rohanKanojia** [comment]
okay, so

on 4.1.3 it's working without .cascading(true) flag
on 4.3.0 it's not working without .cascading(true) flag
on this patch it's not working without .cascading(true) flag :-(

**Comment by rohanKanojia** [comment]
@deiwin : So now for this updated patch, your test case is working as expected.

**Comment by deiwin** [comment]
Great! Thank you!

**Comment by jglick** [comment]
I did get a test case from the user reporting a regression, but have not yet had a chance to work it up into JUnit format and check against this patch. I hope to be able to do that on Monday.

**Comment by rohanKanojia** [comment]
@jglick : Thanks, You would get this fix in 4.3.1

**Comment by rohanKanojia** [comment]
[merge]

**Comment by zhanjiejun** [comment]
Did the 4.3.1 release fix the problem: 
kubeClient.pods().inAnyNamespace.withField("spec.nodeName", "node1").delete()
without cascading?

**Comment by rohanKanojia** [comment]
@zhanjiejun : Doesn't cascading deletion work for parent resources only? Could you please share your pod spec? I tried your code but in my case pod was owned by a deployment so it got created again. But when I tried it with some orphan pod then pod was deleted.

I did all this on 4.6.0

**Comment by zhanjiejun** [comment]
@rohanKanojia 
I have been using version 4.2.1, and found the problem recently.
I want to set 'node1' unschedulable and delete all pods on 'node1', just like the command 'kubectl drain node1' .

So I used **'kubeClient.pods().inAnyNamespace.withField("spec.nodeName", "node1").delete()'** .
But old pods on 'node1' were in status 'Termenating' constantly (I did not notice these orphan pods) , and new pod were created on other nodes by deployment.

Set cascade to true can solve the problem.
But pods delete can not set **cascading(true)** like single pod delete as below:
kubeClient.pods().inNamespace("test").withName("test").cascading(true).delete()

**'I did all this on 4.6.0'** means you have solved the problem on version 4.6.0, set cascade deletion to true by default?

**Pull request merged**
