### PR TITLE
[crd-generator] Add support for 'default'

### LINKED ISSUE #5410: CRD Generation - Defaulting Support
While the crd-generator currently supports annotations such as `@Pattern`, `@Min`, `@Max`,  `@Required`, etc, which helps to enforce constraints on CRD fields, there is no way of specifying default values. I would appreciate built-in support for setting default values when generating the CustomResourceDefinition.

Reference: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting

I suggest implementing a mechanism that allows to define such default values for the CRD fields by using annotations, similar to how existing annotations work. For example:

```java
public class MyCustomResourceSpec {
    // ... Other annotations
    @Required
    @DefaultValue("example")
    private String exampleValue;
}
```

Corresponding `default: example` will be generated in the output CRD, such as:

```yaml
properties:
  spec:
    properties:
      exampleValue:
        type: string
        default: "example"
      required:
      - exampleValue
```

### PR DESCRIPTION
**Pull request by andreaTP**
## Description
Fix #5410 

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [X] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [X] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/main/CHANGELOG.md) entry regarding this change
 - [X] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by manusa — APPROVED** [review]
The annotation looks good to me.
However, what's the expectation for new instances of the given type?
Who is responsible for setting the value?
Will the cluster's API service set this value if I send a POST request with an entity missing it?

**Review by oscerd — APPROVED** [review]

**Comment by andreaTP** [comment]
> However, what's the expectation for new instances of the given type?

We are doing nothing from the client perspective, everything will be handled by kubernetes itself following [this spec](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting)

> Who is responsible for setting the value?
Will the cluster's API service set this value if I send a POST request with an entity missing it?

Yes, as shown in the example on the Kubernetes docs, the API server will set it.

**Comment by manusa** [comment]
Sounds good, thx for the clarification.

Since we discussed this internally a couple of weeks ago, I'll wait for @shawkins blessing before merging.

**Comment by andreaTP** [comment]
This should be aligned with the discussion in the meeting.
Rebased and ready for final review 👍

**Review by manusa — APPROVED** [review]

**Pull request merged**
