### PR TITLE
More Usage of diamond operator

### PR DESCRIPTION
**Pull request by dipsonu10**
Reference #3740

## Description
removal of redundant generic type specification 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry regarding this change
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
These files are generated and persisted to VCS for performance reasons.
They shouldn't be manually modified (hence the reason why the `Kubernetes Model Generator Build` pipeline fails.

**Comment by dipsonu10** [comment]
So, which folders should not be changed?

**Comment by dipsonu10** [comment]
As it's my first PR could you say from where should I start

**Comment by manusa** [comment]
> As it's my first PR could you say from where should I start

I'm not sure what issue you are trying to fix. It would be good to ask for clarification in the issue that you are trying to fix.

> So, which folders should not be changed?

Any directory `**/src/generated/**` should be out of bounds for any manual changes.

**Comment by dipsonu10** [comment]
Okay will remember

**Pull request closed without merging**
