### PR TITLE
Fix #5257: Add ErrorStreamMessage and StatusStreamMessage to ease mocking of pods/exec requests

### LINKED ISSUE #5257: Improve mocking capabilities
### Is your enhancement related to a problem? Please describe

It's hard to mock `pods/exec` calls for other stream IDs than stdout:
```java
server.expect()
    .withPath("/api/v1/namespaces/test/pods/pod1/exec?command=ls&container=debug&stdout=true")
    .andUpgradeToWebSocket()
    .open(new OutputStreamMessage(expectedOutput))
    .done()
    .always();
```

### Describe the solution you'd like

The client should provide `ErrorStreamMessage` and `StatusStreamMessage` to support mocking like:
```java
server.expect()
  .withPath("/api/v1/namespaces/test/pods/pod1/exec?command=ls&container=default&stderr=true")
  .andUpgradeToWebSocket()
  .open(new ErrorStreamMessage(expectedError))
  .done()
  .always();
```
```java
server.expect()
  .withPath("/api/v1/namespaces/test/pods/pod1/exec?command=ls&container=default&stdout=true")
  .andUpgradeToWebSocket()
  .open(new StatusStreamMessage(1))
  .done()
  .always();
```

### Describe alternatives you've considered

I've written the classes for our project, but this needs some code duplication, because we cannot re-use the private method `getBodyBytes()` from `OutputStreamMessage`.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Donnerbart**
## Description

Fixes #5257

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] I Added [CHANGELOG](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md) entry regarding this change
 - [x] I have implemented unit tests to cover my changes
 - [x] I have added/updated the [javadocs](https://www.javadoc.io/doc/io.fabric8/kubernetes-client/latest/index.html) and other [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=fabric8io_kubernetes-client) report
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift
 - [x] I tested my code in my own tests

### CODE REVIEW

**Comment by Donnerbart** [comment]
The existing classes of `kubernetes-server-mock` have no JavaDoc and are not mentioned in the documentation. So I guess it's okay to tick that off the checklist.

The license and spotless checks are passing locally. I guess for the SonarCloud report someone needs to trigger the builds first.

Since this is not production code, I'm not sure what to do about the `I tested my code in Kubernetes/OpenShift` part. I've added the same code to our custom operator to write unit tests and there it works fine.

**Comment by Donnerbart** [comment]
Thanks for running the tests. I don't understand the Sonar report though. It claims that there is missing code coverage on the new classes, but they are used in `PodTest`. Do the tests have to be in the same module to count?

**Comment by Donnerbart** [comment]
I've checked all code smells with the SonarLint plugin locally and added unit tests in the same module for all touched and new classes. Let's hope SonarCloud is happy now :)

**Comment by Donnerbart** [comment]
I've added the missing license headers to the new test files.

**Comment by Donnerbart** [comment]
Fix the spotless violation (sorry for the many pushes, it's a totally different tech stack for me).

**Review by shawkins — APPROVED** [review]
These look much better for testing execs thank you

**Review by rohanKanojia — APPROVED** [review]

**Comment by Donnerbart** [comment]
I've rebased the branch to solve the conflict in the `CHANGELOG.md`. No further changes or merge conflicts.

Any change to get this merged into the 6.9 release?

**Comment by Donnerbart** [comment]
Looks like all E2E failed:
```
Error:  Failed to execute goal on project kubernetes-itests: Could not resolve dependencies for project io.fabric8:kubernetes-itests:jar:6.9-SNAPSHOT: The following artifacts could not be resolved: io.fabric8:kubernetes-junit-jupiter-autodetected:jar:6.9-SNAPSHOT, io.fabric8:openshift-client:jar:6.9-SNAPSHOT, io.fabric8:kubernetes-client-api:jar:tests:6.9-SNAPSHOT: Could not find artifact io.fabric8:kubernetes-junit-jupiter-autodetected:jar:6.9-SNAPSHOT -> [Help 1]
```
The PR is based on the latest `main` branch and I didn't change anything regarding the module setup. So I'm not sure if the root cause is in this PR or not.

**Comment by Donnerbart** [comment]
Rebased with `main` branch and resolved the merge conflict in `CHANGELOG.md`. No further changes.

**Pull request merged**
