### PR TITLE
Upgrade jobs to v1

### PR DESCRIPTION
**Pull request by joan38**
This is not an alpha version anymore

### CODE REVIEW

**Comment by joan38** [comment]
There is it's sister PR https://github.com/fabric8io/kubernetes-model/pull/215
But this can be merged before the model one without breaking.

**Comment by joan38** [comment]
Flaky test, it passes on my machine

**Comment by joan38** [comment]
I just saw that there was a PR open for quiet a while for the same thing https://github.com/fabric8io/kubernetes-client/pull/779

**Comment by ucosty** [comment]
I'd definitely like to see this get merged.

**Comment by iocanel** [comment]
ok to test

**Comment by oscerd** [comment]
[merge]

**Comment by joan38** [comment]
Cheers @iocanel and @oscerd

**Pull request merged**
